# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually

from .common import MAX_MSG, parse_args, parse_args_rest
from .help_ import help_link_message, ALIAS_TEMPLATES
from .templates import cmd_templates
from .anim import cmd_anim, edit_with_anim
from .ai import cmd_ai, register_ai_mode_handler
from .translate import cmd_translate
from .ping import cmd_ping
from .weather import cmd_weather
from .notes import cmd_notes
from .reminders import cmd_remind, start_reminder_worker
from .qr import cmd_qr
from .alias import cmd_alias
from .prefix import cmd_prefix
from .version import cmd_version
from .url_tools import cmd_url
from .connections import cmd_connections
from .anti_delete import cmd_anti_delete, register_anti_delete_handlers
from .voice import cmd_voice
from .pin import cmd_pin
from .online import cmd_online, cmd_track, cmd_seen
from .yandex_music import cmd_yandex_music_now_playing

__all__ = [
    "MAX_MSG",
    "parse_args",
    "parse_args_rest",
    "help_link_message",
    "ALIAS_TEMPLATES",
    "cmd_templates",
    "cmd_anim",
    "edit_with_anim",
    "cmd_ai",
    "register_ai_mode_handler",
    "cmd_translate",
    "cmd_ping",
    "cmd_weather",
    "cmd_notes",
    "cmd_remind",
    "start_reminder_worker",
    "cmd_qr",
    "cmd_alias",
    "cmd_prefix",
    "cmd_version",
    "cmd_url",
    "cmd_connections",
    "cmd_anti_delete",
    "register_anti_delete_handlers",
    "cmd_voice",
    "cmd_pin",
    "cmd_online",
    "cmd_track",
    "cmd_seen",
    "cmd_yandex_music_now_playing",
]
