"""Команда .axs alias."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from ..store import alias_delete, alias_get, alias_list, alias_set
from .common import MAX_MSG, blockquote_html, parse_args, parse_args_rest


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_alias(event, prefix, tail, user_id, respond)


async def cmd_alias(event, prefix: str, tail: str, user_id: int, respond) -> bool:
    args, rest = parse_args_rest(tail, 2)
    sub = (args[0] if args else "").lower()
    if sub == "list" or (not sub and not rest):
        items = alias_list(user_id)
        if not items:
            await respond(blockquote_html(f"Алиасов нет. Добавить: <code>{prefix} alias add &lt;алиас&gt; &lt;команда&gt;</code>"), parse_mode="html")
            return True
        lines = ["<b>Алиасы:</b>"] + [f"• <code>.{alias}</code> → <code>{(cmd[:50] + ('…' if len(cmd) > 50 else ''))}</code>" for alias, cmd in items]
        await respond(blockquote_html("\n".join(lines)[:MAX_MSG - 50]), parse_mode="html")
        return True
    if sub == "add":
        alias_name = (args[1] if len(args) > 1 else None) or ""
        command = rest.strip()
        if not alias_name or not command:
            await respond(blockquote_html(f"Формат: <code>{prefix} alias add &lt;алиас&gt; &lt;команда&gt;</code>. Пример: <code>{prefix} alias add w weather</code>"), parse_mode="html")
            return True
        alias_name = alias_name.lower().strip()
        if alias_name.startswith("."):
            alias_name = alias_name[1:]
        if not alias_name or len(alias_name) > 64:
            await respond(blockquote_html("Алиас: 1–64 символа, без точки в начале."), parse_mode="html")
            return True
        alias_set(user_id, alias_name, command)
        await respond(blockquote_html(f"Добавлено: <code>.{alias_name}</code> → <code>{command[:100]}</code>"), parse_mode="html")
        return True
    if sub == "remove" or sub == "delete":
        alias_name = (args[1] if len(args) > 1 else rest.split()[0] if rest else "").strip()
        if not alias_name:
            await respond(blockquote_html(f"Формат: <code>{prefix} alias remove &lt;алиас&gt;</code>"), parse_mode="html")
            return True
        if alias_name.startswith("."):
            alias_name = alias_name[1:]
        if alias_delete(user_id, alias_name):
            await respond(blockquote_html(f"Алиас <code>.{alias_name}</code> удалён."), parse_mode="html")
        else:
            await respond(blockquote_html(f"Алиас <code>.{alias_name}</code> не найден."), parse_mode="html")
        return True
    return False
