"""Команда .axs anim и анимация редактирования ответа."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



import asyncio
from ..store import ANIM_MODES, ANIM_TYPE, anim_get, anim_set
from .common import MAX_MSG, blockquote_html, parse_args


async def edit_with_anim(target, text: str, user_id: int) -> None:
    """target — event (user) или сообщение-ответ (bot); у обоих есть .edit()."""
    mode = anim_get(user_id)
    cut = text[:MAX_MSG]
    if mode != ANIM_TYPE:
        await target.edit(cut)
        return
    chunk = 80
    prev = ""
    for i in range(0, len(cut), chunk):
        prev = cut[: i + chunk]
        await target.edit(prev)
        await asyncio.sleep(0.15)
    if prev != cut:
        await target.edit(cut)


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_anim(event, prefix, tail, user_id, respond)


async def cmd_anim(event, prefix: str, tail: str, user_id: int, respond) -> bool:
    args = parse_args(tail)
    mode = args[0] if args else None
    if not mode:
        current = anim_get(user_id)
        await respond(blockquote_html(f"<b>Анимация ответа:</b> {current}\nИзменить: <code>{prefix} anim instant</code> или <code>{prefix} anim type</code>"), parse_mode="html")
        return True
    mode = mode.lower()
    if mode not in ANIM_MODES:
        await respond(blockquote_html("Допустимые режимы: <code>instant</code> | <code>type</code>"), parse_mode="html")
        return True
    anim_set(user_id, mode)
    await respond(blockquote_html(f"Режим анимации: <b>{mode}</b>"), parse_mode="html")
    return True
