"""Команда .axs anti-delete и обработчики удаления/редактирования сообщений.

Логика:
- для каждого Telegram‑аккаунта (user client) используем свой account_id (me.id);
- для каждого чата можно включить/выключить антиделит;
- все данные храним в отдельной БД, указанной в AD_DATABASE_URL (см. ad_store).
"""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import asyncio
import html
import os
import tempfile
from typing import Optional, Tuple

import requests
from telethon import TelegramClient, events

from ..ad_store import (
    ad_user_upsert,
    anti_delete_cache_add,
    anti_delete_cache_find,
    anti_delete_cache_remove,
    anti_delete_get,
    anti_delete_log_add,
    anti_delete_log_list,
    anti_delete_set,
)
from .common import MAX_MSG, blockquote_html, parse_args

logger = __import__("logging").getLogger(__name__)

# Кэш get_me() по клиенту (60s), чтобы не дёргать API на каждое событие
import time as _time
_AD_ME_CACHE: dict[int, tuple[float, object]] = {}
_AD_ME_CACHE_TTL = 60.0


async def _get_me_cached_ad(client) -> object:
    cid = id(client)
    now = _time.monotonic()
    if cid in _AD_ME_CACHE:
        me, cached_at = _AD_ME_CACHE[cid]
        if now - cached_at < _AD_ME_CACHE_TTL:
            return me
    me = await client.get_me()
    _AD_ME_CACHE[cid] = (me, now)
    return me


# Зарегистрированные аккаунты (чтобы не дёргать БД лишний раз)
_REGISTERED_ACCOUNTS: set[int] = set()

# Ключ: (account_id, chat_id, msg_id)
ANTI_MSG_CACHE: dict[tuple[int, int, int], object] = {}
ANTI_MEDIA_DIR = os.path.join(tempfile.gettempdir(), "apixs_anti_delete")
# Значение: {"mode": "channel", "channel_id": int, "msg_id": int} или {"mode": "local", "path": str, "media_type": str}
ANTI_MEDIA_FILES: dict[tuple[int, int, int], dict] = {}


def build_media_label(msg) -> str:
    """Короткое описание сообщения (для медиа/голосовых)."""
    text = (getattr(msg, "message", None) or "").strip()
    if text:
        return text
    voice = getattr(msg, "voice", None)
    if voice is not None:
        dur = None
        try:
            attrs = getattr(voice, "attributes", None) or []
            if attrs:
                dur = getattr(attrs[0], "duration", None)
        except Exception:
            dur = None
        if dur is not None:
            return f"[Голосовое сообщение ~{dur} с]"
        return "[Голосовое сообщение]"
    if getattr(msg, "photo", None) is not None:
        return "[Фото]"
    if getattr(msg, "audio", None) is not None:
        return "[Аудио]"
    if getattr(msg, "video", None) is not None:
        return "[Видео]"
    if getattr(msg, "document", None) is not None:
        return "[Документ]"
    return "(медиа/без текста)"


def get_media_type(msg) -> Optional[str]:
    if getattr(msg, "voice", None) is not None:
        return "voice"
    if getattr(msg, "photo", None) is not None:
        return "photo"
    if getattr(msg, "video", None) is not None:
        return "video"
    if getattr(msg, "document", None) is not None or getattr(msg, "audio", None) is not None:
        return "document"
    return None


def _get_bot_target(account_id: Optional[int] = None) -> Optional[int]:
    """Чат, куда бот отправляет anti-delete.

    Приоритет (под твой сценарий):
    1) account_id — писать СРАЗУ в личку владельцу аккаунта
    2) ANTI_LOG_CHAT_ID (если нужен общий лог-чат)
    3) ANTI_DELETE_BOT_CHAT_ID (fallback из .env)
    """
    if account_id:
        return int(account_id)
    raw_log = (os.getenv("ANTI_LOG_CHAT_ID") or "").strip()
    if raw_log:
        try:
            return int(raw_log)
        except ValueError:
            pass
    raw_fallback = (os.getenv("ANTI_DELETE_BOT_CHAT_ID") or "").strip()
    if raw_fallback:
        try:
            return int(raw_fallback)
        except ValueError:
            pass
    return None


def _send_via_bot(text: str, account_id: Optional[int] = None) -> bool:
    """Отправка в чат через бота (TELEGRAM_BOT_TOKEN + ANTI_DELETE_BOT_CHAT_ID / account_id).

    Возвращает True только если Telegram API вернул ok=True.
    В логах видно причину ошибки, если что-то пошло не так.
    """
    token = (os.getenv("TELEGRAM_BOT_TOKEN") or "").strip()
    target = _get_bot_target(account_id)
    if not token or target is None:
        logger.debug("anti-delete bot not configured: token/target missing")
        return False
    try:
        resp = requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={
                "chat_id": target,
                "text": text,
                "parse_mode": "HTML",
                "disable_web_page_preview": True,
            },
            timeout=10,
        )
        if resp.status_code != 200:
            logger.warning(
                "anti-delete bot HTTP %s: %s",
                resp.status_code,
                (resp.text or "")[:500],
            )
            return False
        try:
            data = resp.json()
        except Exception:
            data = {}
        if not data.get("ok", False):
            logger.warning(
                "anti-delete bot API error: %s",
                str(data.get("description") or data)[:300],
            )
            return False
        return True
    except Exception as e:
        logger.warning("anti-delete bot send error: %s", e)
        return False


def _get_media_channel_id() -> Optional[int]:
    """ID канала для хранения медиа (ANTI_DELETE_MEDIA_CHANNEL). Бот должен быть добавлен как админ."""
    raw = (os.getenv("ANTI_DELETE_MEDIA_CHANNEL") or "").strip()
    if not raw:
        return None
    try:
        return int(raw)
    except ValueError:
        return None


def _forward_via_bot(from_chat_id: int, message_id: int, to_chat_id: int) -> Optional[int]:
    """Пересылает сообщение через бота. Возвращает message_id в to_chat_id или None."""
    token = (os.getenv("TELEGRAM_BOT_TOKEN") or "").strip()
    if not token:
        return None
    try:
        resp = requests.post(
            f"https://api.telegram.org/bot{token}/forwardMessage",
            json={
                "chat_id": to_chat_id,
                "from_chat_id": from_chat_id,
                "message_id": message_id,
            },
            timeout=15,
        )
        if resp.status_code != 200:
            logger.warning("anti-delete forward bot HTTP %s: %s", resp.status_code, (resp.text or "")[:300])
            return None
        try:
            data = resp.json()
        except Exception:
            data = {}
        if not data.get("ok", False):
            logger.warning("anti-delete forward bot API: %s", str(data.get("description") or data)[:300])
            return None
        result = data.get("result") or {}
        return int(result.get("message_id", 0)) or None
    except Exception as e:
        logger.warning("anti-delete forward via bot error: %s", e)
        return None


def _delete_via_bot(chat_id: int, message_id: int) -> bool:
    """Удаляет сообщение из чата через бота."""
    token = (os.getenv("TELEGRAM_BOT_TOKEN") or "").strip()
    if not token:
        return False
    try:
        resp = requests.post(
            f"https://api.telegram.org/bot{token}/deleteMessage",
            json={"chat_id": chat_id, "message_id": message_id},
            timeout=10,
        )
        if resp.status_code != 200:
            logger.warning("anti-delete delete bot HTTP %s: %s", resp.status_code, (resp.text or "")[:300])
            return False
        try:
            data = resp.json()
        except Exception:
            data = {}
        return bool(data.get("ok", False))
    except Exception as e:
        logger.warning("anti-delete delete via bot error: %s", e)
        return False


async def send_anti_delete_notification(
    client: TelegramClient,
    cid: int,
    sid: Optional[int],
    msg_id: int,
    text: str,
    account_id: Optional[int] = None,
) -> None:
    """Отправляет уведомление о удалённом сообщении через бота в настроенный чат."""
    try:
        chat_ent = await client.get_entity(cid)
        # Для чатов/пользователей сначала стараемся показать @username/публичный тег,
        # а уже потом локальное имя/название.
        uname = getattr(chat_ent, "username", None)
        if uname:
            chat_name = f"@{uname}"
        else:
            chat_name = (
                getattr(chat_ent, "title", None)
                or getattr(chat_ent, "first_name", None)
                or str(cid)
            )
    except Exception:
        chat_name = str(cid)

    sender_str = "неизвестен"
    if sid:
        try:
            s_ent = await client.get_entity(sid)
            uname = getattr(s_ent, "username", None)
            first = (getattr(s_ent, "first_name", None) or "").strip()
            last = (getattr(s_ent, "last_name", None) or "").strip()
            display = (first + (" " + last if last else "")).strip() or uname or str(sid)
            if uname:
                sender_str = f'<a href="https://t.me/{uname}">{html.escape(display)}</a>'
            else:
                sender_str = html.escape(display)
        except Exception:
            sender_str = str(sid)

    preview = (text or "(медиа/без текста)").strip()
    if len(preview) > 500:
        preview = preview[:500] + "…"

    body = (
        "🗑 <b>Замечено удаление</b>\n\n"
        f"<blockquote>"
        f"💬  {chat_name}\n"
        f"👤  {sender_str}\n"
        f"🆔  <code>{msg_id}</code>"
        f"</blockquote>\n\n"
        f"<b>Текст:</b>\n"
        f"<blockquote expandable>{preview}</blockquote>"
    )

    if not await asyncio.to_thread(_send_via_bot, body, account_id):
        logger.debug("anti-delete notify: bot not configured (TELEGRAM_BOT_TOKEN/ANTI_DELETE_BOT_CHAT_ID)")


async def send_anti_edit_notification(
    client: TelegramClient,
    cid: int,
    sid: Optional[int],
    msg_id: int,
    old_text: str,
    new_text: str,
    account_id: Optional[int] = None,
) -> None:
    """Отправляет уведомление о редактировании сообщения через бота."""
    try:
        chat_ent = await client.get_entity(cid)
        uname = getattr(chat_ent, "username", None)
        if uname:
            chat_name = f"@{uname}"
        else:
            chat_name = (
                getattr(chat_ent, "title", None)
                or getattr(chat_ent, "first_name", None)
                or str(cid)
            )
    except Exception:
        chat_name = str(cid)

    sender_str = "неизвестен"
    if sid:
        try:
            s_ent = await client.get_entity(sid)
            uname = getattr(s_ent, "username", None)
            first = (getattr(s_ent, "first_name", None) or "").strip()
            last = (getattr(s_ent, "last_name", None) or "").strip()
            display = (first + (" " + last if last else "")).strip() or uname or str(sid)
            if uname:
                sender_str = f'<a href="https://t.me/{uname}">{html.escape(display)}</a>'
            else:
                sender_str = html.escape(display)
        except Exception:
            sender_str = str(sid)

    old_preview = (old_text or "(старый текст недоступен)").strip()
    new_preview = (new_text or "(новый текст пуст)").strip()
    if len(old_preview) > 500:
        old_preview = old_preview[:500] + "…"
    if len(new_preview) > 500:
        new_preview = new_preview[:500] + "…"

    body = (
        "✏️ <b>Замечено редактирование</b>\n\n"
        f"<blockquote>"
        f"💬  {chat_name}\n"
        f"👤  {sender_str}\n"
        f"🆔  <code>{msg_id}</code>"
        f"</blockquote>\n\n"
        f"<b>До:</b>\n"
        f"<blockquote expandable>{old_preview}</blockquote>\n\n"
        f"<b>После:</b>\n"
        f"<blockquote expandable>{new_preview}</blockquote>"
    )
    if not await asyncio.to_thread(_send_via_bot, body, account_id):
        logger.debug("anti-edit notify: bot not configured")


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_anti_delete(event, prefix, tail, user_id, respond, account_id=user_id)


async def cmd_anti_delete(
    event,
    prefix: str,
    tail: str,
    user_id: int,
    respond,
    account_id: int = 0,
) -> bool:
    """Команда .axs anti-delete (или .ad)."""
    if account_id == 0:
        account_id = user_id
    parts = parse_args(tail)
    sub = (parts[0] if parts else "").lower()
    n_str = (parts[1] if len(parts) > 1 else "").strip()
    try:
        limit = int(n_str) if n_str else 30
    except Exception:
        limit = 30
    limit = max(1, min(200, limit))
    chat_id = event.chat_id

    if sub == "on":
        await asyncio.to_thread(anti_delete_set, chat_id, True, account_id)
        await respond(blockquote_html("Anti-delete включён для этого чата."), parse_mode="html")
        return True
    if sub == "off":
        await asyncio.to_thread(anti_delete_set, chat_id, False, account_id)
        await respond(blockquote_html("Anti-delete выключен для этого чата."), parse_mode="html")
        return True
    if sub == "test":
        ok = await asyncio.to_thread(
            _send_via_bot,
            "✅ Anti-delete test message: уведомления настроены.",
            account_id,
        )
        if ok:
            await respond(blockquote_html("Тестовое уведомление отправлено. Проверьте ЛС/чат бота."), parse_mode="html")
        else:
            await respond(blockquote_html("Не удалось отправить тест. Проверьте токен и настройки бота."), parse_mode="html")
        return True
    if sub in ("list", "last", ""):
        rows = await asyncio.to_thread(anti_delete_log_list, chat_id, limit, account_id)
        if not rows:
            await respond(blockquote_html("Нет сохранённых удалённых сообщений."), parse_mode="html")
            return True
        lines = ["<b>Удалённые (последние {}):</b>".format(limit), ""]
        for cid, msg_id, text, sid, deleted_at in rows:
            preview = (text or "(медиа/пусто)")[:80]
            if len(text or "") > 80:
                preview += "…"
            ts = (
                deleted_at.strftime("%d.%m %H:%M")
                if getattr(deleted_at, "strftime", None)
                else str(deleted_at)
            )
            lines.append(f"• [{ts}] {msg_id} — {preview}")
        content = "\n".join(lines)[:MAX_MSG - 50]
        await respond(blockquote_html(content), parse_mode="html")
        return True
    await respond(blockquote_html(
        f"<code>{prefix} anti-delete on</code> | <code>off</code> | <code>list [N]</code> | <code>test</code>"
    ), parse_mode="html")
    return True


def register_anti_delete_handlers(client: TelegramClient, account_name: str = "unknown") -> None:
    """Регистрирует обработчики кэша, удаления и редактирования сообщений.

    account_id берётся из client.get_me().id — то есть у каждого user‑клиента
    свой независимый антиделит и своя БД-запись.
    """

    @client.on(events.NewMessage())
    async def on_anti_delete_cache(event):
        # Только входящие сообщения (ЛС и чаты). Группы тоже логируем.
        if event.out:
            return
        # Не трогаем обычные каналы (broadcast), работаем только с личками/группами/супергруппами
        if getattr(event, "is_channel", False) and not getattr(event, "is_group", False):
            return
        try:
            me = await _get_me_cached_ad(event.client)
            account_id = me.id if me else 0
        except Exception:
            return

        try:
            sender = await event.get_sender()
            if sender and getattr(sender, "bot", False):
                return
        except Exception:
            sender = None

        # Глобальное отключение anti-delete из личного кабинета
        try:
            from ..store import user_settings_get_anti_delete_enabled
            if not await asyncio.to_thread(user_settings_get_anti_delete_enabled, account_id):
                return
        except Exception:
            pass
        # Уважаем тумблеры из личного кабинета: выключить антиделит в группах/каналах
        try:
            from ..store import user_settings_get_auto_delete
            settings = await asyncio.to_thread(user_settings_get_auto_delete, account_id)
        except Exception:
            settings = {"groups": True, "channels": True}
        is_group = bool(getattr(event, "is_group", False))
        is_channel = bool(getattr(event, "is_channel", False)) and not is_group
        if is_group and not bool(settings.get("groups", True)):
            return
        if is_channel and not bool(settings.get("channels", True)):
            return

        if account_id and account_id not in _REGISTERED_ACCOUNTS:
            try:
                await asyncio.to_thread(ad_user_upsert, account_id, account_name)
            except Exception as e:
                logger.debug("ad_user_upsert error: %s", e)
            _REGISTERED_ACCOUNTS.add(account_id)
        if not await asyncio.to_thread(anti_delete_get, event.chat_id, account_id):
            return
        text = build_media_label(event.message)
        try:
            await asyncio.to_thread(
                anti_delete_cache_add,
                event.chat_id,
                event.message.id,
                text,
                event.sender_id,
                False,
                account_id,
            )
            ANTI_MSG_CACHE[(account_id, event.chat_id, event.message.id)] = event.message
            media_type = get_media_type(event.message)
            if media_type is not None and getattr(event.message, "media", None):
                channel_id = _get_media_channel_id()
                if channel_id is not None:
                    fwd_id = await asyncio.to_thread(
                        _forward_via_bot,
                        event.chat_id,
                        event.message.id,
                        channel_id,
                    )
                    if fwd_id is not None:
                        ANTI_MEDIA_FILES[(account_id, event.chat_id, event.message.id)] = {
                            "mode": "channel",
                            "channel_id": channel_id,
                            "msg_id": fwd_id,
                        }
                    else:
                        channel_id = None
                if channel_id is None:
                    try:
                        os.makedirs(ANTI_MEDIA_DIR, exist_ok=True)
                        base = os.path.join(
                            ANTI_MEDIA_DIR,
                            f"{account_id}_{event.chat_id}_{event.message.id}",
                        )
                        path = await client.download_media(event.message, file=base)
                        if path and os.path.isfile(path):
                            ANTI_MEDIA_FILES[
                                (account_id, event.chat_id, event.message.id)
                            ] = {"mode": "local", "path": path, "media_type": media_type}
                    except Exception as e:
                        logger.debug("anti-delete media download: %s", e)
        except Exception as e:
            logger.debug("anti-delete cache add: %s", e)

    @client.on(events.MessageDeleted())
    async def on_message_deleted(event):
        try:
            me = await _get_me_cached_ad(event.client)
            account_id = me.id if me else 0
        except Exception:
            return
        chat_id = getattr(event, "chat_id", None)
        # Не реагируем на удаления в обычных каналах (broadcast)
        if getattr(event, "is_channel", False) and not getattr(event, "is_group", False):
            return
        ids = getattr(event, "deleted_ids", None)
        if ids is None:
            mid = getattr(event, "deleted_id", None)
            ids = [mid] if mid is not None else []

        try:
            from ..store import user_settings_get_anti_delete_enabled
            if not await asyncio.to_thread(user_settings_get_anti_delete_enabled, account_id):
                return
        except Exception:
            pass
        try:
            from ..store import user_settings_get_auto_delete
            settings = await asyncio.to_thread(user_settings_get_auto_delete, account_id)
        except Exception:
            settings = {"groups": True, "channels": True}
        is_group = bool(getattr(event, "is_group", False))
        is_channel = bool(getattr(event, "is_channel", False)) and not is_group

        for msg_id in ids:
            try:
                row = await asyncio.to_thread(anti_delete_cache_find, chat_id, msg_id, account_id)
                if not row:
                    continue
                cid, text, sid, is_bot = row

                if int(is_bot or 0) == 1:
                    await asyncio.to_thread(anti_delete_cache_remove, cid, msg_id, account_id)
                    ANTI_MSG_CACHE.pop((account_id, cid, msg_id), None)
                    media_entry = ANTI_MEDIA_FILES.pop((account_id, cid, msg_id), None)
                    if media_entry is not None:
                        if isinstance(media_entry, dict) and media_entry.get("mode") == "channel":
                            await asyncio.to_thread(_delete_via_bot, media_entry["channel_id"], media_entry["msg_id"])
                        else:
                            path = media_entry[0] if isinstance(media_entry, tuple) else media_entry.get("path", "")
                            if path and os.path.isfile(path):
                                try:
                                    os.remove(path)
                                except OSError:
                                    pass
                    continue

                if is_group and not bool(settings.get("groups", True)):
                    await asyncio.to_thread(anti_delete_cache_remove, cid, msg_id, account_id)
                    ANTI_MSG_CACHE.pop((account_id, cid, msg_id), None)
                    continue
                if is_channel and not bool(settings.get("channels", True)):
                    await asyncio.to_thread(anti_delete_cache_remove, cid, msg_id, account_id)
                    ANTI_MSG_CACHE.pop((account_id, cid, msg_id), None)
                    continue
                await asyncio.to_thread(anti_delete_log_add, cid, msg_id, text, sid, account_id)
                await asyncio.to_thread(anti_delete_cache_remove, cid, msg_id, account_id)
                try:
                    target = _get_bot_target(account_id)
                    msg = ANTI_MSG_CACHE.pop((account_id, cid, msg_id), None)
                    media_entry = ANTI_MEDIA_FILES.pop((account_id, cid, msg_id), None)
                    if target is not None:
                        if msg is not None:
                            try:
                                await client.forward_messages(target, msg, from_peer=cid)
                            except Exception:
                                try:
                                    await asyncio.to_thread(
                                        _send_via_bot,
                                        "🗑 Удалено сообщение (не удалось переслать):\n\n{}".format(
                                            html.escape((text or "(пусто)")[:2000])
                                        ),
                                        account_id,
                                    )
                                except Exception:
                                    pass
                        elif media_entry is not None:
                            if isinstance(media_entry, dict) and media_entry.get("mode") == "channel":
                                ch_id = media_entry.get("channel_id")
                                m_id = media_entry.get("msg_id")
                                if ch_id is not None and m_id is not None:
                                    await asyncio.to_thread(_forward_via_bot, ch_id, m_id, target)
                                    await asyncio.to_thread(_delete_via_bot, ch_id, m_id)
                            else:
                                path = media_entry[0] if isinstance(media_entry, tuple) else media_entry.get("path")
                                media_type = media_entry[1] if isinstance(media_entry, tuple) else media_entry.get("media_type", "")
                                if path and os.path.isfile(path):
                                    try:
                                        await client.send_file(
                                            target, path, voice=(media_type == "voice")
                                        )
                                    except Exception:
                                        pass
                    if media_entry is not None:
                        if isinstance(media_entry, dict) and media_entry.get("mode") == "local":
                            path = media_entry.get("path", "")
                            if path and os.path.isfile(path):
                                try:
                                    os.remove(path)
                                except OSError:
                                    pass
                        elif isinstance(media_entry, tuple):
                            path = media_entry[0]
                            if path and os.path.isfile(path):
                                try:
                                    os.remove(path)
                                except OSError:
                                    pass
                except Exception:
                    logger.exception("anti-delete forward error")

                # Уведомление в личку владельцу аккаунта с понятными данными
                try:
                    await send_anti_delete_notification(
                        client,
                        cid,
                        sid,
                        msg_id,
                        text or "(медиа/без текста)",
                        account_id=account_id,
                    )
                except Exception as e:
                    logger.debug("anti-delete notify send error: %s", e)
            except Exception as e:
                logger.debug("anti-delete log: %s", e)

    @client.on(events.MessageEdited())
    async def on_message_edited(event):
        # Только входящие личные сообщения
        if event.out or not event.is_private:
            return
        try:
            me = await _get_me_cached_ad(event.client)
            account_id = me.id if me else 0
        except Exception:
            return
        try:
            from ..store import user_settings_get_anti_delete_enabled
            if not await asyncio.to_thread(user_settings_get_anti_delete_enabled, account_id):
                return
        except Exception:
            pass
        try:
            sender = await event.get_sender()
            if sender and getattr(sender, "bot", False):
                return
        except Exception:
            pass
        chat_id = event.chat_id
        if not await asyncio.to_thread(anti_delete_get, chat_id, account_id):
            return
        new_text = getattr(event.message, "message", None) or ""
        msg_id = event.message.id
        sender_id = event.sender_id
        try:
            old_msg = ANTI_MSG_CACHE.get((account_id, chat_id, msg_id))
            if old_msg is not None:
                old_text_mem = (getattr(old_msg, "message", None) or "")
                if (old_text_mem or "").strip() == (new_text or "").strip():
                    await asyncio.to_thread(anti_delete_cache_add, chat_id, msg_id, new_text, sender_id, False, account_id)
                    ANTI_MSG_CACHE[(account_id, chat_id, msg_id)] = event.message
                    return

            row = await asyncio.to_thread(anti_delete_cache_find, chat_id, msg_id, account_id)
            if not row:
                await asyncio.to_thread(anti_delete_cache_add, chat_id, msg_id, new_text, sender_id, False, account_id)
                return
            old_text = row[1] or ""
            if (old_text or "").strip() == (new_text or "").strip():
                await asyncio.to_thread(anti_delete_cache_add, chat_id, msg_id, new_text, sender_id, False, account_id)
                return
            await send_anti_edit_notification(
                client, chat_id, sender_id, msg_id, old_text, new_text, account_id=account_id
            )
            await asyncio.to_thread(anti_delete_cache_add, chat_id, msg_id, new_text, sender_id, False, account_id)
            ANTI_MSG_CACHE[(account_id, chat_id, msg_id)] = event.message
        except Exception as e:
            logger.debug("anti-edit log: %s", e)

