"""Общие утилиты для команд: парсинг аргументов, лимиты, формат ответа."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



MAX_MSG = 4000


def blockquote_html(html: str) -> str:
    """Оборачивает HTML-фрагмент в <blockquote> для единого вида ответов (как в ping)."""
    return f"<blockquote>{html}</blockquote>"


def html_escape(s: str) -> str:
    """Экранирует HTML-спецсимволы в строке (для вставки в blockquote)."""
    if not s:
        return ""
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))[:MAX_MSG]


def parse_args(tail: str) -> list[str]:
    return [x.strip() for x in tail.split() if x.strip()]


def parse_args_rest(tail: str, n: int) -> tuple[list[str], str]:
    """Первые n токенов в args, остаток в rest (без лишних пробелов по краям)."""
    parts = parse_args(tail)
    if len(parts) <= n:
        return (parts, "")
    args = parts[:n]
    rest = " ".join(parts[n:]).strip()
    return (args, rest)
