"""Команда .axs connections — расширенный статус системы и соединений."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import os
import time
import psutil
from datetime import datetime
from typing import Optional

from ..store import status_metrics_sum_since_seconds
from .common import MAX_MSG, blockquote_html

START_TIME = time.monotonic()

def _fmt_ms(ms: float) -> str:
    return f"{ms:.1f}ms" if ms < 100 else f"{int(ms)}ms"

def _get_uptime() -> str:
    uptime_seconds = int(time.monotonic() - START_TIME)
    days, rem = divmod(uptime_seconds, 86400)
    hours, rem = divmod(rem, 3600)
    minutes, seconds = divmod(rem, 60)
    
    parts = []
    if days > 0: parts.append(f"{days}d")
    if hours > 0: parts.append(f"{hours}h")
    if minutes > 0: parts.append(f"{minutes}m")
    if not parts: parts.append(f"{seconds}s")
    return " ".join(parts)


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_connections(event, prefix, respond)


async def cmd_connections(event, prefix: str, respond) -> bool:
    """
    .axs connections
    Показывает детальный статус: Сеть, БД, Система, Активность.
    """
    tg_status = "🔴 ERR"
    tg_info = "disconnected"
    tg_ping = "n/a"
    
    try:
        if event.client.is_connected():
            t_start = time.monotonic()
            await event.client.get_me()
            tg_ping = _fmt_ms((time.monotonic() - t_start) * 1000)
            
            me = await event.client.get_me()
            tg_status = "🟢 OK"
            tg_info = f"@{me.username}" if me.username else f"ID: {me.id}"
    except Exception as e:
        tg_info = str(e)[:30]

    # 2. Database (MySQL) Status
    db_status = "🔴 ERR"
    db_latency = "n/a"
    try:
        t_start = time.monotonic()
        cmd_60 = status_metrics_sum_since_seconds("command_executed", 60)
        ai_60 = status_metrics_sum_since_seconds("ai_request", 60)
        db_latency = _fmt_ms((time.monotonic() - t_start) * 1000)
        db_status = "🟢 OK"
    except Exception as e:
        cmd_60 = ai_60 = 0
        db_latency = "n/a"

    # 3. System Resources
    try:
        process = psutil.Process(os.getpid())
        ram_usage = process.memory_info().rss / 1024 / 1024  # MB
        cpu_usage = process.cpu_percent(interval=None)
    except:
        ram_usage = cpu_usage = 0

    lines = [
        "<b>System Status</b>",
        f"Telegram: {tg_status} <code>{tg_ping}</code> — <i>{tg_info}</i>",
        f"MySQL: {db_status} <code>{db_latency}</code>",
        f"Uptime: <code>{_get_uptime()}</code> · RAM: <code>{ram_usage:.1f} MB</code> · CPU: <code>{cpu_usage}%</code>",
        f"Commands: <code>{cmd_60}</code>/min · AI: <code>{ai_60}</code>/min",
        f"<i>{datetime.now().strftime('%H:%M:%S')}</i>",
    ]
    content = "\n".join(lines)[:MAX_MSG - 50]
    await respond(blockquote_html(content), parse_mode="html")
    return True