"""
.axs dl <url>  — скачать видео с TikTok, YouTube, Instagram Reels, Twitter/X.
Шорткат: .dl <url>
"""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import asyncio
import os
import re
import shutil
import tempfile
from typing import Optional

from .common import blockquote_html, html_escape, parse_args

# ─── Константы ────────────────────────────────────────────────────────────────

_SIZE_LIMIT_BOT  = 300 * 1024 * 1024        # 300 MB
_SIZE_LIMIT_USER = 5   * 1024 * 1024 * 1024  # 5 GB
_DOWNLOAD_TIMEOUT = 120                       # секунд

_SOURCE_PATTERNS: list[tuple[str, str]] = [
    (r"tiktok\.com|vm\.tiktok\.com|vt\.tiktok\.com", "TikTok"),
    (r"youtube\.com|youtu\.be",                       "YouTube"),
    (r"instagram\.com",                               "Instagram"),
    (r"twitter\.com|x\.com",                          "Twitter/X"),
    (r"vk\.com|vkvideo\.ru",                          "ВКонтакте"),
    (r"ok\.ru",                                       "Одноклассники"),
    (r"twitch\.tv",                                   "Twitch"),
    (r"reddit\.com|redd\.it",                         "Reddit"),
    (r"facebook\.com|fb\.watch|fb\.com",              "Facebook"),
    (r"vimeo\.com",                                   "Vimeo"),
    (r"rutube\.ru",                                   "Rutube"),
    (r"dailymotion\.com|dai\.ly",                     "Dailymotion"),
]

# ─── Вспомогательные функции ──────────────────────────────────────────────────

def _detect_source(url: str) -> str:
    for pattern, name in _SOURCE_PATTERNS:
        if re.search(pattern, url, re.IGNORECASE):
            return name
    return "Video"


def _is_supported(url: str) -> bool:
    return any(re.search(p, url, re.IGNORECASE) for p, _ in _SOURCE_PATTERNS)


def _make_progress(percent: int, width: int = 10) -> str:
    filled = int(width * percent / 100)
    bar = "█" * filled + "▱" * (width - filled)
    return f"{bar} {percent}%"


def _status_text(pct: int, source: str) -> str:
    if pct < 100:
        return (
            f"⬇️ <b>Скачиваю видео...</b>\n"
            f"\n"
            f"<code>{_make_progress(pct)}</code>\n"
            f"\n"
            f"📡 Источник: <b>{source}</b>\n"
            f"\n"
            f'🌐 <a href="https://YOUR_DOMAIN">Скачано при помощи ApiXS</a>'
        )
    return (
        f"⬇️ <b>Скачиваю видео...</b>\n"
        f"\n"
        f"<code>{_make_progress(100)}</code>\n"
        f"\n"
        f"📦 <b>Отправляю файл...</b>\n"
        f"\n"
        f'🌐 <a href="https://YOUR_DOMAIN">Скачано при помощи ApiXS</a>'
    )


def _cleanup(path: str) -> None:
    try:
        shutil.rmtree(path, ignore_errors=True)
    except Exception:
        pass


def _cleanup_file(path: Optional[str]) -> None:
    if path:
        try:
            os.remove(path)
        except Exception:
            pass


# ─── Обработчик команды ───────────────────────────────────────────────────────

async def handle(
    event,
    tail: str,
    user_id: int,
    respond,
    config=None,
    prefix: str = ".axs",
    **kwargs,
) -> None:
    url = tail.strip()

    if not url:
        await respond(
            blockquote_html(
                f"Формат: <code>{prefix} dl &lt;url&gt;</code>\n\n"
                "Поддерживаемые платформы:\n"
                "TikTok · YouTube · Instagram · Twitter/X\n"
                "ВКонтакте · Одноклассники · Twitch\n"
                "Reddit · Facebook · Vimeo · Rutube · Dailymotion"
            ),
            parse_mode="html",
        )
        return

    if not re.match(r"^https?://", url, re.IGNORECASE):
        url = "https://" + url

    if not _is_supported(url):
        await respond(
            blockquote_html(
                "❌ <b>Ссылка не поддерживается</b>\n\n"
                "Поддерживаемые платформы:\n"
                "TikTok · YouTube · Instagram · Twitter/X\n"
                "ВКонтакте · Одноклассники · Twitch\n"
                "Reddit · Facebook · Vimeo · Rutube · Dailymotion"
            ),
            parse_mode="html",
        )
        return

    try:
        import yt_dlp  # noqa: F401
    except ImportError:
        await respond(
            blockquote_html(
                "❌ <b>yt-dlp не установлен</b>\n"
                "<code>pip install yt-dlp</code>"
            ),
            parse_mode="html",
        )
        return

    is_bot   = getattr(config, "is_bot", False)
    size_limit = _SIZE_LIMIT_BOT if is_bot else _SIZE_LIMIT_USER
    source   = _detect_source(url)
    loop     = asyncio.get_event_loop()

    await respond(blockquote_html(_status_text(0, source)), parse_mode="html", link_preview=False)

    # ── Progress-хук (вызывается из потока yt-dlp) ──────────────────────────
    last_reported: dict[str, int] = {"pct": -1}

    def _progress_hook(d: dict) -> None:
        if d["status"] != "downloading":
            return
        total      = d.get("total_bytes") or d.get("total_bytes_estimate") or 0
        downloaded = d.get("downloaded_bytes") or 0
        if total <= 0:
            return
        rounded = (int(downloaded / total * 100) // 20) * 20
        if rounded == last_reported["pct"]:
            return
        last_reported["pct"] = rounded
        try:
            asyncio.run_coroutine_threadsafe(
                event.edit(
                    blockquote_html(_status_text(rounded, source)),
                    parse_mode="html",
                    link_preview=False,
                ),
                loop,
            ).result(timeout=5)
        except Exception:
            pass

    # ── Настройки yt-dlp по платформе ───────────────────────────────────────
    tmp_dir      = tempfile.mkdtemp(prefix="axs_dl_")
    tmp_template = os.path.join(tmp_dir, "%(id)s.%(ext)s")

    is_tiktok  = bool(re.search(r"tiktok\.com", url, re.IGNORECASE))
    is_youtube = bool(re.search(r"youtube\.com|youtu\.be", url, re.IGNORECASE))

    # Cookies — приоритет: DL_COOKIES_B64 (Railway) > DL_COOKIES_FILE > DL_COOKIES_BROWSER
    cookies_file    = os.getenv("DL_COOKIES_FILE", "").strip()
    cookies_browser = os.getenv("DL_COOKIES_BROWSER", "").strip()
    cookies_b64     = os.getenv("DL_COOKIES_B64", "").strip()

    _tmp_cookies_path: Optional[str] = None
    if cookies_b64:
        try:
            import base64 as _b64
            decoded = _b64.b64decode(cookies_b64)
            _tmp_cookie_fd, _tmp_cookies_path = tempfile.mkstemp(suffix=".txt", prefix="axs_ck_")
            with os.fdopen(_tmp_cookie_fd, "wb") as _f:
                _f.write(decoded)
        except Exception:
            _tmp_cookies_path = None

    def _apply_cookies(opts: dict) -> dict:
        if _tmp_cookies_path:
            opts["cookiefile"] = _tmp_cookies_path
        elif cookies_file and os.path.isfile(cookies_file):
            opts["cookiefile"] = cookies_file
        elif cookies_browser:
            opts["cookiesfrombrowser"] = (cookies_browser,)
        return opts

    if is_tiktok:
        ydl_opts: dict = _apply_cookies({
            "outtmpl": tmp_template,
            "format": "best",
            "quiet": True,
            "no_warnings": True,
            "progress_hooks": [_progress_hook],
            "extractor_args": {
                "tiktok": {
                    "api_hostname": "api22-normal-c-useast2a.tiktokv.com",
                },
            },
        })
    elif is_youtube:
        ydl_opts = _apply_cookies({
            "outtmpl": tmp_template,
            "format": (
                "bestvideo[ext=mp4][height<=720]+bestaudio[ext=m4a]"
                "/best[ext=mp4][height<=720]/best"
            ),
            "quiet": True,
            "no_warnings": True,
            "merge_output_format": "mp4",
            "progress_hooks": [_progress_hook],
            # Android-клиент обходит bot-check без cookies на большинстве видео
            "extractor_args": {
                "youtube": {
                    "player_client": ["android", "web"],
                },
            },
        })
    else:
        ydl_opts = _apply_cookies({
            "outtmpl": tmp_template,
            "format": "best",
            "quiet": True,
            "no_warnings": True,
            "progress_hooks": [_progress_hook],
        })

    # ── Синхронная функция скачивания (для run_in_executor) ─────────────────
    def _do_download() -> tuple[Optional[str], str, Optional[str]]:
        import yt_dlp as _yt

        try:
            with _yt.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(url, download=True)
                if info is None:
                    return None, "Video", "Не удалось получить информацию о видео"

                vid_title: str = (info.get("title") or "Video")

                # yt-dlp может менять расширение, ищем реальный файл
                base = os.path.splitext(ydl.prepare_filename(info))[0]
                for ext in ("mp4", "webm", "mkv", "mov", "avi", "m4v"):
                    candidate = f"{base}.{ext}"
                    if os.path.exists(candidate):
                        return candidate, vid_title, None

                # Fallback: любой файл в tmp_dir
                for fname in os.listdir(tmp_dir):
                    fpath = os.path.join(tmp_dir, fname)
                    if os.path.isfile(fpath):
                        return fpath, vid_title, None

                return None, vid_title, "Файл после скачивания не найден"

        except Exception as exc:
            msg = str(exc)
            if re.search(r"private|закрыт", msg, re.IGNORECASE):
                return None, "Video", "Приватное видео — доступ закрыт"
            if re.search(r"not supported|no suitable", msg, re.IGNORECASE):
                return None, "Video", "Ссылка не поддерживается yt-dlp"
            return None, "Video", msg[:300]

    # ── Запускаем скачивание ─────────────────────────────────────────────────
    video_path: Optional[str] = None
    title      = "Video"
    error_msg: Optional[str] = None

    try:
        video_path, title, error_msg = await asyncio.wait_for(
            loop.run_in_executor(None, _do_download),
            timeout=_DOWNLOAD_TIMEOUT,
        )
    except asyncio.TimeoutError:
        error_msg = f"Превышен таймаут ({_DOWNLOAD_TIMEOUT} сек)"
    except Exception as exc:
        error_msg = str(exc)[:300]

    # ── Обработка ошибок ─────────────────────────────────────────────────────
    if error_msg or not video_path:
        reason = error_msg or "Неизвестная ошибка"
        try:
            await event.edit(
                blockquote_html(
                    f"❌ <b>Не удалось скачать</b>\n<code>{html_escape(reason)}</code>"
                ),
                parse_mode="html",
                link_preview=False,
            )
        except Exception:
            pass
        _cleanup(tmp_dir)
        _cleanup_file(_tmp_cookies_path)
        return

    # ── Проверка размера ─────────────────────────────────────────────────────
    fsize = os.path.getsize(video_path)
    if fsize > size_limit:
        limit_str = "50 МБ" if is_bot else "2 ГБ"
        size_mb   = fsize // 1024 // 1024
        try:
            await event.edit(
                blockquote_html(
                    f"❌ <b>Файл слишком большой</b>\n"
                    f"Размер: {size_mb} МБ, лимит: {limit_str}"
                ),
                parse_mode="html",
                link_preview=False,
            )
        except Exception:
            pass
        _cleanup(tmp_dir)
        _cleanup_file(_tmp_cookies_path)
        return

    # ── «Отправляю...» ───────────────────────────────────────────────────────
    try:
        await event.edit(
            blockquote_html(_status_text(100, source)),
            parse_mode="html",
            link_preview=False,
        )
    except Exception:
        pass

    # ── Отправка файла ───────────────────────────────────────────────────────
    caption = (
        f"🎬 <b>{html_escape(title)}</b>\n"
        f"\n"
        f"📡 {source}\n"
        f'🔗 <a href="{url}">Оригинал</a>\n'
        f"\n"
        f'<a href="https://YOUR_DOMAIN">Скачано при помощи ApiXS</a>'
    )

    try:
        await event.client.send_file(
            event.chat_id,
            video_path,
            caption=caption,
            parse_mode="html",
        )
    except Exception as exc:
        try:
            await event.edit(
                blockquote_html(
                    f"❌ <b>Ошибка отправки файла</b>\n<code>{html_escape(str(exc)[:200])}</code>"
                ),
                parse_mode="html",
                link_preview=False,
            )
        except Exception:
            pass
        _cleanup(tmp_dir)
        _cleanup_file(_tmp_cookies_path)
        return

    try:
        await event.delete()
    except Exception:
        pass

    _cleanup(tmp_dir)
    _cleanup_file(_tmp_cookies_path)
