"""Справка и алиасы команд."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



ALIAS_TEMPLATES = ("list", "add", "get", "edit", "delete")

HELP_URL = "https://YOUR_DOMAIN/help"


def help_link_message(prefix: str) -> str:
    """Сообщение со ссылкой на справку (HTML с blockquote)."""
    return (
        "<blockquote><b>Справка ApiXS</b><br><br>"
        "Префикс: <code>{p}</code><br>"
        "Полная справка: {url}</blockquote>"
    ).format(url=HELP_URL, p=prefix)
