"""Команда .axs improve — улучшение фото через бесплатный AI (Hugging Face) с опциональным промптом."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import base64
import os
import tempfile
import asyncio
from typing import Optional

import requests
from telethon.tl.custom.message import Message

from .common import MAX_MSG, blockquote_html

logger = __import__("logging").getLogger(__name__)

# Модель по умолчанию: инструкции по редактированию изображения
HF_IMPROVE_MODEL = os.getenv("HF_IMPROVE_MODEL", "timbrooks/instruct-pix2pix")
DEFAULT_PROMPT = "improve quality, enhance details, high resolution"


async def _get_message_with_photo(event) -> Optional[Message]:
    """Фото: из текущего сообщения (команда в подписи) или из ответа."""
    msg = event.message
    if getattr(msg, "photo", None) is not None:
        return msg
    reply = await event.get_reply_message()
    if reply and getattr(reply, "photo", None) is not None:
        return reply
    return None


def _improve_image_sync(image_bytes: bytes, prompt: str, token: str) -> Optional[bytes]:
    """Синхронный вызов HF Inference API: image-to-image с промптом. Возвращает байты картинки или None."""
    model = (os.getenv("HF_IMPROVE_MODEL") or HF_IMPROVE_MODEL).strip()
    url = f"https://api-inference.huggingface.co/models/{model}"
    headers = {"Authorization": f"Bearer {token}"}
    b64 = base64.b64encode(image_bytes).decode("ascii")
    body = {"inputs": b64, "parameters": {"prompt": prompt[:500]}}
    try:
        r = requests.post(url, headers=headers, json=body, timeout=60)
        if r.status_code == 503:
            # модель загружается
            err = (r.json() or {}).get("error", "Model is loading")
            raise RuntimeError(err)
        r.raise_for_status()
        return r.content
    except requests.exceptions.RequestException as e:
        logger.debug("HF improve request error: %s", e)
        raise
    except Exception as e:
        logger.debug("HF improve error: %s", e)
        raise


async def handle(
    event,
    tail: str,
    user_id: int,
    respond,
    config=None,
    prefix: str = ".axs",
    t_start=None,
) -> None:
    """Улучшение фото: ответ на фото или фото в одном сообщении с командой; опционально свой промпт."""
    token = (os.getenv("HF_TOKEN") or os.getenv("HUGGINGFACE_TOKEN") or "").strip()
    if not token:
        await respond(blockquote_html("Требуется HF_TOKEN в .env. Создать: https://huggingface.co/settings/tokens"), parse_mode="html")
        return

    msg_with_photo = await _get_message_with_photo(event)
    if msg_with_photo is None:
        await respond(blockquote_html(f"Приложите фото к команде или ответьте на фото. Пример: <code>{prefix} improve</code> или <code>{prefix} improve сделай ярче</code>"), parse_mode="html")
        return

    user_prompt = (tail or "").strip()
    prompt = user_prompt if user_prompt else DEFAULT_PROMPT

    tmp_in = tempfile.mktemp(prefix="apixs_improve_", suffix=".jpg")
    try:
        path = await event.client.download_media(msg_with_photo, file=tmp_in)
        if not path or not os.path.isfile(path):
            await respond(blockquote_html("Не удалось скачать фото."), parse_mode="html")
            return
        size = os.path.getsize(path)
        if size > 10 * 1024 * 1024:
            await respond(blockquote_html("Максимальный размер фото: 10 МБ."), parse_mode="html")
            return

        with open(path, "rb") as f:
            image_bytes = f.read()

        status_msg = "Улучшаю через AI…" if not user_prompt else f"Улучшаю с промптом: «{user_prompt[:80]}{'…' if len(user_prompt) > 80 else ''}»"
        if config and getattr(config, "is_bot", False):
            target = await event.reply(status_msg)
        else:
            try:
                await event.edit(status_msg)
                target = event
            except Exception:
                target = await event.reply(status_msg)

        loop = asyncio.get_running_loop()
        try:
            out_bytes = await loop.run_in_executor(
                None,
                lambda: _improve_image_sync(image_bytes, prompt, token),
            )
        except RuntimeError as e:
            err = str(e)
            if "loading" in err.lower():
                await target.edit(blockquote_html("Модель HF загружается. Повторите через минуту."), parse_mode="html")
            else:
                await target.edit(blockquote_html("Ошибка HF: " + err[:300]), parse_mode="html")
            return
        except Exception as e:
            logger.exception("improve HF error: %s", e)
            await target.edit(blockquote_html("Ошибка улучшения. Проверьте HF_TOKEN и лимиты API."), parse_mode="html")
            return

        if not out_bytes or len(out_bytes) < 100:
            await target.edit(blockquote_html("Пустой или неверный ответ от сервера."), parse_mode="html")
            return

        out_path = tempfile.mktemp(prefix="apixs_improve_out_", suffix=".png")
        try:
            with open(out_path, "wb") as f:
                f.write(out_bytes)
            caption = f"✨ Улучшено" + (f"\nПромпт: {user_prompt[:200]}" if user_prompt else "")
            await event.client.send_file(
                event.chat_id,
                out_path,
                caption=caption[:MAX_MSG],
                reply_to=event.id,
            )
            try:
                await target.delete()
            except Exception:
                pass
        finally:
            try:
                if os.path.isfile(out_path):
                    os.remove(out_path)
            except OSError:
                pass
    finally:
        try:
            if os.path.isfile(tmp_in):
                os.remove(tmp_in)
        except OSError:
            pass
