"""Команда .axs notes."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from ..store import notes_add, notes_delete, notes_last, notes_search
from .common import MAX_MSG, blockquote_html, parse_args


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_notes(event, prefix, tail, user_id, respond)


async def cmd_notes(event, prefix: str, tail: str, user_id: int, respond) -> bool:
    args = parse_args(tail)
    sub = (args[0] if args else "").lower()
    rest = " ".join(args[1:]).strip() if len(args) > 1 else ""
    if sub == "add":
        text = rest.strip()
        if not text:
            await respond(blockquote_html(f"Формат: <code>{prefix} notes add &lt;текст&gt;</code>"), parse_mode="html")
            return True
        nid = notes_add(user_id, text)
        await respond(blockquote_html(f"Заметка #<code>{nid}</code> сохранена."), parse_mode="html")
        return True
    if sub == "last":
        n_str = (args[1] if len(args) > 1 else "10").strip()
        try:
            limit = int(n_str) if n_str else 10
        except ValueError:
            limit = 10
        limit = max(1, min(100, limit))
        rows = notes_last(user_id, limit=limit)
        if not rows:
            await respond(blockquote_html(f"Заметок нет. Добавить: <code>{prefix} notes add &lt;текст&gt;</code>"), parse_mode="html")
            return True
        lines = []
        for nid, text, created_at in rows:
            ts = created_at.strftime("%d.%m %H:%M") if getattr(created_at, "strftime", None) else str(created_at)
            preview = (text or "")[:60] + ("…" if len(text or "") > 60 else "")
            lines.append(f"• #<code>{nid}</code> [{ts}] {preview}")
        content = ("Последние заметки:\n\n" + "\n".join(lines))[:MAX_MSG - 50]
        await respond(blockquote_html(content), parse_mode="html")
        return True
    if sub in ("del", "delete", "rm"):
        nid_str = (args[1] if len(args) > 1 else rest.split()[0] if rest else "").strip()
        if not nid_str:
            await respond(blockquote_html(f"Формат: <code>{prefix} notes del &lt;номер&gt;</code>"), parse_mode="html")
            return True
        try:
            nid = int(nid_str)
        except ValueError:
            await respond(blockquote_html("Укажите номер заметки (число)."), parse_mode="html")
            return True
        if notes_delete(user_id, nid):
            await respond(blockquote_html(f"Заметка #<code>{nid}</code> удалена."), parse_mode="html")
        else:
            await respond(blockquote_html(f"Заметка #<code>{nid}</code> не найдена."), parse_mode="html")
        return True
    if sub == "search":
        query = rest.strip()
        if not query:
            await respond(blockquote_html(f"Формат: <code>{prefix} notes search &lt;слово&gt;</code>"), parse_mode="html")
            return True
        rows = notes_search(user_id, query, limit=20)
        if not rows:
            await respond(blockquote_html(f"По запросу «{query[:50]}» ничего не найдено."), parse_mode="html")
            return True
        lines = []
        for nid, text, created_at in rows:
            ts = created_at.strftime("%d.%m %H:%M") if getattr(created_at, "strftime", None) else str(created_at)
            preview = (text or "")[:80] + ("…" if len(text or "") > 80 else "")
            lines.append(f"• #<code>{nid}</code> [{ts}] {preview}")
        content = ("Результаты:\n\n" + "\n".join(lines))[:MAX_MSG - 50]
        await respond(blockquote_html(content), parse_mode="html")
        return True
    if not sub or sub == "list":
        rows = notes_last(user_id, limit=5)
        if not rows:
            await respond(blockquote_html(
                "<b>Заметки</b>\n\n"
                f"• <code>{prefix} notes add &lt;текст&gt;</code> — добавить\n"
                f"• <code>{prefix} notes last [N]</code> — последние N\n"
                f"• <code>{prefix} notes search &lt;слово&gt;</code> — поиск\n"
                f"• <code>{prefix} notes del &lt;номер&gt;</code> — удалить"
            ), parse_mode="html")
            return True
        lines = ["<b>Последние заметки:</b>"] + [
            f"• #<code>{nid}</code> {(text or '')[:50]}{'…' if len(text or '') > 50 else ''}"
            for nid, text, _ in rows
        ]
        await respond(blockquote_html("\n".join(lines)[:MAX_MSG - 50]), parse_mode="html")
        return True
    return False
