"""Команды .axs online / track / seen — отслеживание онлайн-статуса."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import asyncio
import os
import time
from datetime import datetime
from typing import Optional

from telethon import TelegramClient
from telethon.tl import types

from ..store import (
    online_log_add,
    online_log_last,
    online_log_list,
    online_track_list,
    online_track_set_last_status,
    online_track_stop,
    online_track_upsert,
    online_watch_list,
    online_watch_remove,
    online_watch_upsert,
    user_settings_get_seen_date_format,
)
from .anti_delete import _send_via_bot
from .common import MAX_MSG, blockquote_html, parse_args

logger = __import__("logging").getLogger(__name__)


def _status_key(user) -> str:
    st = getattr(user, "status", None)
    if st is None or isinstance(st, types.UserStatusEmpty):
        return "hidden"
    if isinstance(st, types.UserStatusOnline):
        return "online"
    if isinstance(st, types.UserStatusOffline):
        return "offline"
    if isinstance(st, types.UserStatusRecently):
        return "recently"
    if isinstance(st, types.UserStatusLastWeek):
        return "last_week"
    if isinstance(st, types.UserStatusLastMonth):
        return "last_month"
    return "unknown"


def _pretty_username(user, fallback: str = "") -> str:
    uname = getattr(user, "username", None)
    if uname:
        return "@" + uname
    if fallback:
        s = fallback.strip()
        if s.startswith("@"):
            return s
        return "@" + s if s else str(getattr(user, "id", "") or "")
    return str(getattr(user, "id", "") or "")


def _fmt_dt(dt: Optional[datetime]) -> str:
    if not dt:
        return "—"
    try:
        return dt.strftime("%d.%m.%Y %H:%M")
    except Exception:
        return str(dt)


def _fmt_dt_user(dt: Optional[datetime], user_id: int) -> str:
    """Формат даты с учётом настройки пользователя (short / long / relative)."""
    if not dt:
        return "—"
    try:
        fmt = user_settings_get_seen_date_format(user_id)
    except Exception:
        fmt = "short"
    if fmt == "relative":
        now = datetime.utcnow()
        if getattr(dt, "tzinfo", None):
            try:
                from datetime import timezone
                now = datetime.now(timezone.utc)
            except Exception:
                pass
        d = dt.date() if hasattr(dt, "date") else dt
        n = now.date() if hasattr(now, "date") else now
        from datetime import timedelta
        if d == n:
            return "сегодня " + dt.strftime("%H:%M")
        if d == n - timedelta(days=1):
            return "вчера " + dt.strftime("%H:%M")
        return dt.strftime("%d.%m %H:%M")
    if fmt == "long":
        return dt.strftime("%d.%m.%Y, %H:%M")
    return dt.strftime("%d.%m.%Y %H:%M")


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_online(event, tail, user_id, respond)


async def cmd_online(event, tail: str, user_id: int, respond) -> bool:
    """Однократное уведомление, когда пользователь появится онлайн."""
    parts = parse_args(tail)
    if not parts:
        await respond(blockquote_html("Формат: <code>online &lt;username&gt;</code>"), parse_mode="html")
        return True
    username = parts[0].strip()
    try:
        ent = await event.client.get_entity(username)
    except Exception as e:
        logger.debug("online get_entity: %s", e)
        await respond(blockquote_html("Пользователь не найден."), parse_mode="html")
        return True
    if not isinstance(ent, types.User):
        await respond(blockquote_html("Укажите пользователя (не канал/чат)."), parse_mode="html")
        return True
    if _status_key(ent) == "hidden":
        await respond(blockquote_html("Онлайн-статус скрыт. Уведомление недоступно."), parse_mode="html")
        return True
    online_watch_upsert(user_id, int(ent.id), (getattr(ent, "username", None) or username).lstrip("@"))
    await respond(blockquote_html("Слежка за {} включена. Уведомлю при появлении онлайн.".format(_pretty_username(ent, username))), parse_mode="html")
    return True


async def cmd_track(event, tail: str, user_id: int, respond) -> bool:
    """Постоянное логирование онлайн/офлайн активности."""
    parts = parse_args(tail)
    if not parts:
        await respond(blockquote_html(
            "<code>track &lt;username&gt;</code> — начать<br>"
            "<code>track stop &lt;username&gt;</code><br>"
            "<code>track list</code><br>"
            "<code>track log &lt;username&gt; [N]</code>"
        ), parse_mode="html")
        return True

    sub = parts[0].lower()
    if sub == "list":
        rows = online_track_list(user_id, only_active=True, limit=200)
        if not rows:
            await respond(blockquote_html("Активных слежек нет."), parse_mode="html")
            return True
        lines = ["<b>Слежки:</b>"]
        for r in rows:
            u = (r.get("target_username") or "").strip()
            label = ("@" + u) if u else str(r.get("target_id") or "")
            lines.append(f"• {label} — {r.get('last_status') or 'unknown'}")
        await respond(blockquote_html("\n".join(lines)[:MAX_MSG - 50]), parse_mode="html")
        return True

    if sub == "stop":
        if len(parts) < 2:
            await respond(blockquote_html("Формат: <code>track stop &lt;username&gt;</code>"), parse_mode="html")
            return True
        username = parts[1].strip()
        try:
            ent = await event.client.get_entity(username)
        except Exception:
            await respond(blockquote_html("Пользователь не найден."), parse_mode="html")
            return True
        if not isinstance(ent, types.User):
            await respond(blockquote_html("Укажите пользователя (не канал/чат)."), parse_mode="html")
            return True
        online_track_stop(user_id, int(ent.id))
        await respond(blockquote_html("Слежка за {} остановлена.".format(_pretty_username(ent, username))), parse_mode="html")
        return True

    if sub == "log":
        if len(parts) < 2:
            await respond(blockquote_html("Формат: <code>track log &lt;username&gt; [N]</code>"), parse_mode="html")
            return True
        username = parts[1].strip()
        n = 20
        if len(parts) >= 3:
            try:
                n = int(parts[2])
            except Exception:
                n = 20
        n = max(1, min(100, n))
        try:
            ent = await event.client.get_entity(username)
        except Exception:
            await respond(blockquote_html("Пользователь не найден."), parse_mode="html")
            return True
        if not isinstance(ent, types.User):
            await respond(blockquote_html("Укажите пользователя (не канал/чат)."), parse_mode="html")
            return True
        rows = online_log_list(user_id, int(ent.id), limit=n)
        if not rows:
            await respond(blockquote_html("Записей лога нет."), parse_mode="html")
            return True
        lines = [f"<b>Лог {_pretty_username(ent, username)}:</b>"]
        for r in rows:
            st = (r.get("status") or "").strip()
            dt = r.get("recorded_at")
            lines.append(f"• {_fmt_dt_user(dt, user_id)} — {st}")
        await respond(blockquote_html("\n".join(lines)[:MAX_MSG - 50]), parse_mode="html")
        return True

    username = parts[0].strip()
    try:
        ent = await event.client.get_entity(username)
    except Exception:
        await respond(blockquote_html("Пользователь не найден."), parse_mode="html")
        return True
    if not isinstance(ent, types.User):
        await respond(blockquote_html("Укажите пользователя (не канал/чат)."), parse_mode="html")
        return True
    if _status_key(ent) == "hidden":
        await respond(blockquote_html("Онлайн-статус скрыт. Трекинг недоступен."), parse_mode="html")
        return True
    online_track_upsert(user_id, int(ent.id), (getattr(ent, "username", None) or username).lstrip("@"), is_active=True)
    await respond(blockquote_html("Слежка за {} запущена.".format(_pretty_username(ent, username))), parse_mode="html")
    return True


async def cmd_seen(event, tail: str, user_id: int, respond) -> bool:
    """Показывает когда пользователь последний раз был онлайн."""
    parts = parse_args(tail)
    if not parts:
        await respond(blockquote_html("Формат: <code>seen &lt;username&gt;</code>"), parse_mode="html")
        return True
    username = parts[0].strip()
    try:
        ent = await event.client.get_entity(username)
    except Exception:
        await respond(blockquote_html("Пользователь не найден."), parse_mode="html")
        return True
    if not isinstance(ent, types.User):
        await respond(blockquote_html("Укажите пользователя (не канал/чат)."), parse_mode="html")
        return True

    st = getattr(ent, "status", None)
    sk = _status_key(ent)
    if sk == "hidden":
        await respond(blockquote_html("Онлайн-статус скрыт."), parse_mode="html")
        return True
    if sk == "online":
        await respond(blockquote_html("{} — сейчас онлайн.".format(_pretty_username(ent, username))), parse_mode="html")
        return True
    if sk == "recently":
        await respond(blockquote_html("{} — был(а) недавно.".format(_pretty_username(ent, username))), parse_mode="html")
        return True
    if sk == "last_week":
        await respond(blockquote_html("{} — на этой неделе.".format(_pretty_username(ent, username))), parse_mode="html")
        return True
    if sk == "last_month":
        await respond(blockquote_html("{} — в этом месяце.".format(_pretty_username(ent, username))), parse_mode="html")
        return True
    if isinstance(st, types.UserStatusOffline):
        dt = getattr(st, "was_online", None)
        last = online_log_last(user_id, int(ent.id))
        if last and (last.get("status") == "offline") and last.get("recorded_at"):
            await respond(blockquote_html(
                "{} — был(а) онлайн: {} (по логам)".format(
                    _pretty_username(ent, username),
                    _fmt_dt_user(last.get("recorded_at"), user_id),
                )
            ), parse_mode="html")
            return True
        await respond(blockquote_html("{} — был(а) онлайн: {}".format(_pretty_username(ent, username), _fmt_dt_user(dt, user_id))), parse_mode="html")
        return True

    await respond(blockquote_html("Статус не определён."), parse_mode="html")
    return True


async def _online_worker_loop(client: TelegramClient, watcher_id: int) -> None:
    interval = 60
    raw = (os.getenv("ONLINE_CHECK_INTERVAL") or "").strip()
    if raw:
        try:
            interval = max(15, int(raw))
        except Exception:
            interval = 60

    while True:
        t0 = time.monotonic()
        try:
            # one-shot watches
            watches = await asyncio.to_thread(online_watch_list, watcher_id, 500) or []
            for w in watches:
                tid = int(w.get("target_id") or 0)
                if tid <= 0:
                    continue
                try:
                    u = await client.get_entity(tid)
                except Exception:
                    continue
                if not isinstance(u, types.User):
                    continue
                if _status_key(u) == "online":
                    label = _pretty_username(u, (w.get("target_username") or ""))
                    await asyncio.to_thread(_send_via_bot, f"🟢 {label} сейчас онлайн.", watcher_id)
                    await asyncio.to_thread(online_watch_remove, watcher_id, tid)

            # trackers
            tracks = await asyncio.to_thread(lambda: online_track_list(watcher_id, only_active=True, limit=500)) or []
            for tr in tracks:
                tid = int(tr.get("target_id") or 0)
                if tid <= 0:
                    continue
                try:
                    u = await client.get_entity(tid)
                except Exception:
                    continue
                if not isinstance(u, types.User):
                    continue
                new_status = _status_key(u)
                if new_status == "hidden":
                    continue
                old_status = (tr.get("last_status") or "unknown status").strip().lower()
                if old_status != new_status:
                    await asyncio.to_thread(online_log_add, watcher_id, tid, new_status)
                    await asyncio.to_thread(online_track_set_last_status, watcher_id, tid, new_status)
                    label = _pretty_username(u, (tr.get("target_username") or ""))
                    await asyncio.to_thread(_send_via_bot, f"👣 {label}: {old_status} → {new_status}", watcher_id)
        except Exception as e:
            logger.debug("online worker: %s", e)

        elapsed = time.monotonic() - t0
        sleep_for = max(1.0, float(interval) - elapsed)
        await asyncio.sleep(sleep_for)

