"""Команда .axs pin / unpin — управление закрепами сообщений."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

from .common import blockquote_html, parse_args

logger = __import__("logging").getLogger(__name__)


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_pin(event, (tail or "pin").strip(), respond)


async def cmd_pin(event, tail: str, respond) -> bool:
    """Закрепить/открепить сообщение в чате."""
    parts = parse_args(tail)
    sub = (parts[0] if parts else "").lower()

    if sub == "list":
        try:
            pinned = await event.client.get_pinned_message(event.chat_id)
        except Exception as e:
            logger.debug("get_pinned_message error: %s", e)
            pinned = None
        if not pinned:
            await respond(blockquote_html("В чате нет закреплённого сообщения."), parse_mode="html")
            return True
        preview = (getattr(pinned, "text", None) or getattr(pinned, "message", None) or "(медиа)")[:80]
        if len(preview or "") > 80:
            preview = (preview or "")[:77] + "…"
        await respond(blockquote_html(f"<b>Закреплено:</b> {preview or '(пусто)'}\nID: <code>{pinned.id}</code>"), parse_mode="html")
        return True

    if sub == "unpin":
        try:
            await event.client.unpin_message(event.chat_id)
        except Exception as e:
            logger.debug("unpin error: %s", e)
            await respond(blockquote_html("Не удалось открепить сообщение."), parse_mode="html")
            return True
        try:
            await event.delete()
        except Exception:
            pass
        return True

    notify = False
    if sub == "notify":
        notify = True
    elif sub not in ("", "silent"):
        # Если первая часть не распознана как режим — считаем, что режим по умолчанию (silent),
        # а текст — лишний.
        notify = False

    reply = await event.get_reply_message()
    if not reply:
        await respond(blockquote_html("Ответьте на сообщение и отправьте <code>pin</code>. Список: <code>pin list</code>."), parse_mode="html")
        return True

    try:
        await event.client.pin_message(event.chat_id, reply, notify=notify)
    except Exception as e:
        logger.debug("pin error: %s", e)
        await respond(blockquote_html("Не удалось закрепить сообщение."), parse_mode="html")
        return True

    try:
        await event.delete()
    except Exception:
        pass
    return True

