"""
.axs ping
Показывает пинг до бота.
"""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



import time


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> None:
    t_start = kwargs.get("t_start", time.monotonic())
    await cmd_ping(event, t_start, respond)

PING_TIERS = [
    (50,   "⚡", "молниеносно"),
    (150,  "✅", "отлично"),
    (400,  "🟡", "приемлемо"),
    (1000, "🟠", "медленно"),
    (3000, "🔴", "плохо"),
    (None, "💀", "критично"),
]


async def cmd_ping(event, t_start: float, respond) -> None:
    elapsed_ms = (time.monotonic() - t_start) * 1000

    icon, label = "💀", "критично"
    for threshold, ic, lbl in PING_TIERS:
        if threshold is None or elapsed_ms < threshold:
            icon, label = ic, lbl
            break

    if elapsed_ms >= 1000:
        time_str = f"{elapsed_ms / 1000:.2f}с ({elapsed_ms:.0f}мс)"
    else:
        time_str = f"{elapsed_ms:.1f}мс"

    await respond(f"<blockquote><b>Pong! Ответ от сервера.</b>\n\n{icon} <b>{time_str}</b> — {label}</blockquote>", parse_mode="html")