"""Команда .axs prefix — кастомный префикс для каждого пользователя."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from ..store import prefix_get, prefix_set, prefix_reset
from .common import blockquote_html, parse_args


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_prefix(event, prefix, tail, user_id, respond)


async def cmd_prefix(event, prefix: str, tail: str, user_id: int, respond) -> bool:
    """prefix [set] <префикс> | prefix reset"""
    args = parse_args(tail)
    sub = (args[0] if args else "").lower()
    if sub == "reset":
        prefix_reset(user_id)
        await respond(blockquote_html(f"Префикс сброшен. По умолчанию: <code>{prefix}</code>"), parse_mode="html")
        return True
    if sub == "set" and len(args) > 1:
        new = (args[1] or "").strip()
    elif sub and not sub.startswith("."):
        new = "." + sub.strip()
    elif args:
        new = (args[0] or "").strip()
    else:
        current = prefix_get(user_id)
        if current:
            await respond(blockquote_html(f"Текущий префикс: <code>{current}</code>\nСброс: <code>{prefix} prefix reset</code>"), parse_mode="html")
        else:
            await respond(blockquote_html(f"По умолчанию: <code>{prefix}</code>\nУстановить: <code>{prefix} prefix set .api</code>"), parse_mode="html")
        return True
    if not new:
        await respond(blockquote_html(f"Укажи префикс. Пример: <code>{prefix} prefix set .api</code>"), parse_mode="html")
        return True
    if not new.startswith("."):
        new = "." + new.lstrip()
    if len(new) > 32:
        await respond(blockquote_html("Лимит: 32 символа. Пример: <code>.api</code>"), parse_mode="html")
        return True
    prefix_set(user_id, new)
    await respond(blockquote_html(f"Префикс сохранён: <code>{new}</code>"), parse_mode="html")
    return True
