"""Команда .axs qr."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



import io
import qrcode
from .common import MAX_MSG, blockquote_html


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_qr(event, (tail or "").strip(), respond)


async def cmd_qr(event, text: str, respond) -> bool:
    if not text or not text.strip():
        await respond(blockquote_html("Формат: <code>qr &lt;текст или ссылка&gt;</code>"), parse_mode="html")
        return True
    data = text.strip()[:2000]
    try:
        qr = qrcode.QRCode(version=1, box_size=10, border=4)
        qr.add_data(data)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        buf.seek(0)
        await event.client.send_file(event.chat_id, buf, filename="qr.png")
    except Exception as e:
        await respond(blockquote_html("Ошибка генерации QR: " + str(e)[:200]), parse_mode="html")
    return True
