"""Команда .axs remind и фоновая задача доставки."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import re
import os
import logging
import asyncio
import requests
from datetime import datetime, timedelta
from typing import Optional, Set

import pytz
from .common import MAX_MSG, blockquote_html, parse_args

from ..store import reminders_add, reminders_list, reminders_due, reminders_delete, status_metrics_cleanup

logger = logging.getLogger("ApiXS.Reminders")
REMIND_TZ = pytz.timezone("Asia/Yekaterinburg")

def _fmt_dt(dt: datetime) -> str:
    """Красивое форматирование даты."""
    now = datetime.now(REMIND_TZ).replace(tzinfo=None)
    if dt.date() == now.date():
        return f"Сегодня в {dt.strftime('%H:%M')}"
    if dt.date() == (now + timedelta(days=1)).date():
        return f"Завтра в {dt.strftime('%H:%M')}"
    return dt.strftime("%d.%m %H:%M")

def _get_allowed_user_ids() -> Set[str]:
    """Собирает разрешенные ID для безопасности."""
    allowed: Set[str] = set()
    try:
        from ApiXS.config import load_config
        config = load_config()
        for acc in config.telegram_accounts:
            if acc.get("allowed_users"):
                allowed.update(str(u) for u in acc["allowed_users"])
    except Exception:
        pass
    return allowed

def _send_reminder_via_bot(chat_id: int, text: str) -> bool:
    """Отправка уведомления через Bot API."""
    token = (os.getenv("REMINDER_BOT_TOKEN") or os.getenv("TELEGRAM_BOT_TOKEN") or "").strip()
    if not token: return False
    try:
        r = requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={
                "chat_id": chat_id, 
                "text": text, 
                "parse_mode": "HTML", 
                "disable_web_page_preview": True
            },
            timeout=10,
        )
        return r.ok
    except: return False

def _parse_remind_time(s: str) -> Optional[datetime]:
    """Парсинг времени (2h, 30m, 15:00, завтра 10:00)."""
    s = s.strip().lower()
    now = datetime.now(REMIND_TZ)
    
    # 2h, 30m
    m = re.match(r"^(\d+)\s*(h|m|min|мин|ч|час|часов)$", s)
    if m:
        n = int(m.group(1))
        unit = m.group(2)
        if unit in ("h", "ч", "час", "часов"):
            return (now + timedelta(hours=n)).replace(tzinfo=None)
        return (now + timedelta(minutes=n)).replace(tzinfo=None)
    
    # 15:30
    m = re.match(r"^(\d{1,2}):(\d{2})$", s)
    if m:
        h, mi = int(m.group(1)), int(m.group(2))
        target = now.replace(hour=h, minute=mi, second=0, microsecond=0)
        if target <= now: target += timedelta(days=1)
        return target.replace(tzinfo=None)
        
    # завтра 10:00
    m = re.match(r"^(завтра|tomorrow)\s+(\d{1,2}):(\d{2})$", s)
    if m:
        h, mi = int(m.group(2)), int(m.group(3))
        return (now + timedelta(days=1)).replace(hour=h, minute=mi, second=0, microsecond=0).replace(tzinfo=None)
    
    return None

_METRICS_CLEANUP_INTERVAL_SEC = 300  # 5 минут

async def _reminder_worker(client=None, user_id: int = 0) -> None:
    """Фоновый процесс проверки напоминаний и периодической очистки метрик. DB/HTTP в to_thread."""
    import time as _time
    allowed_ids = _get_allowed_user_ids()
    last_metrics_cleanup = 0.0
    while True:
        try:
            now_naive = datetime.now(REMIND_TZ).replace(tzinfo=None)
            rows = await asyncio.to_thread(reminders_due, 50, now_naive)
            for rid, uid, chat_id, remind_at, text in rows:
                if str(uid) not in allowed_ids and uid != user_id:
                    continue
                msg = (
                    "<b>🔔 НАПОМИНАНИЕ</b>\n"
                    "<code>" + "—" * 20 + "</code>\n"
                    f"{text}\n"
                    "<code>" + "—" * 20 + "</code>\n"
                    f"<i>Установлено на: {_fmt_dt(remind_at)}</i>"
                )
                sent = await asyncio.to_thread(_send_reminder_via_bot, uid, msg)
                if sent:
                    await asyncio.to_thread(reminders_delete, rid)
                elif client and user_id != 0 and uid == user_id:
                    await client.send_message("me", msg, parse_mode="html")
                    await asyncio.to_thread(reminders_delete, rid)
            now_ts = _time.time()
            if now_ts - last_metrics_cleanup >= _METRICS_CLEANUP_INTERVAL_SEC:
                try:
                    await asyncio.to_thread(status_metrics_cleanup)
                    last_metrics_cleanup = now_ts
                except Exception as ce:
                    logger.debug("metrics cleanup: %s", ce)
                try:
                    from ..ad_store import anti_delete_cache_cleanup
                    await asyncio.to_thread(anti_delete_cache_cleanup)
                except Exception:
                    pass
        except Exception as e:
            logger.error(f"Worker error: {e}")
        await asyncio.sleep(45)

def start_reminder_worker(client=None, user_id: int = 0, loop=None) -> Optional[asyncio.Task]:
    if client is None: return None
    l = loop or asyncio.get_event_loop()
    return l.create_task(_reminder_worker(client, user_id))


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_remind(event, prefix, tail, user_id, respond)


async def cmd_remind(event, prefix: str, tail: str, user_id: int, respond) -> bool:
    args = parse_args(tail)
    sub = (args[0] if args else "").lower()
    
    # --- СПИСОК ---
    if sub == "list":
        rows = await asyncio.to_thread(reminders_list, user_id, 20)
        if not rows:
            return await respond(blockquote_html("<b>Активных напоминаний нет.</b>"), parse_mode="html")
        lines = ["<b>Напоминания:</b>", ""]
        for rid, _, _, r_at, text, _ in rows:
            preview = (text or "")[:40] + ("..." if len(text or "") > 40 else "")
            lines.append(f"#<code>{rid:02}</code> | <b>{_fmt_dt(r_at)}</b>\n└ <i>{preview}</i>")
        content = "\n".join(lines)[:MAX_MSG - 50]
        return await respond(blockquote_html(content), parse_mode="html")

    if sub in ("cancel", "del", "rm"):
        try:
            rid = int(args[1])
            if await asyncio.to_thread(reminders_delete, rid):
                await respond(blockquote_html(f"Напоминание #<code>{rid}</code> отменено."), parse_mode="html")
            else:
                await respond(blockquote_html(f"Напоминание #<code>{rid}</code> не найдено."), parse_mode="html")
        except (ValueError, IndexError):
            await respond(blockquote_html(f"Формат: <code>{prefix} remind cancel [номер]</code>"), parse_mode="html")
        return True

    if not sub or len(args) < 2:
        msg = (
            "<b>Напоминания</b>\n\n"
            f"• <code>{prefix} remind 15m [текст]</code> — через 15 мин\n"
            f"• <code>{prefix} remind 2h [текст]</code> — через 2 ч\n"
            f"• <code>{prefix} remind 10:00 [текст]</code> — в указанное время\n"
            f"• <code>{prefix} remind list</code> — список\n"
            f"• <code>{prefix} remind cancel [ID]</code> — отменить"
        )
        return await respond(blockquote_html(msg), parse_mode="html")

    remind_dt = _parse_remind_time(sub)
    if not remind_dt:
        return await respond(blockquote_html("Неверный формат времени. Примеры: <code>10m</code>, <code>2h</code>, <code>18:00</code>"), parse_mode="html")

    text = " ".join(args[1:]).strip()
    rid = await asyncio.to_thread(reminders_add, user_id, event.chat_id, remind_dt, text)
    await respond(
        blockquote_html(
            f"Напоминание #<code>{rid}</code> создано. Сработает: <b>{_fmt_dt(remind_dt)}</b>. Придёт в ЛС."
        ),
        parse_mode="html"
    )
    return True