"""Защита от утечек: фильтрация токенов и ключей из логов и ответов."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



import os
import re
from typing import List


def _get_sensitive_patterns() -> List[str]:
    """Список паттернов для поиска токенов/ключей."""
    patterns = []
    # Telegram bot tokens: 123456789:ABCdefGHIjklMNOpqrsTUVwxyz
    patterns.append(r"\b\d{8,10}:[A-Za-z0-9_-]{35}\b")
    # API keys (Groq, Google и др.): gsk_..., AIza...
    patterns.append(r"\b(gsk_|sk-|AIza)[A-Za-z0-9_-]{20,}\b")
    # Database URLs: mysql://user:pass@host
    patterns.append(r"mysql://[^@]+@[^\s]+")
    patterns.append(r"postgres://[^@]+@[^\s]+")
    # Session strings (Telegram): длинные base64-подобные строки
    patterns.append(r"\b[A-Za-z0-9_-]{200,}\b")
    # Из env переменных
    token = (os.getenv("TELEGRAM_BOT_TOKEN") or "").strip()
    if token:
        patterns.append(re.escape(token))
    groq_key = (os.getenv("GROQ_API_KEY") or "").strip()
    if groq_key:
        patterns.append(re.escape(groq_key))
    db_url = (os.getenv("DATABASE_URL") or "").strip()
    if db_url:
        # Маскируем пароль в URL
        patterns.append(re.escape(db_url))
    return patterns


def sanitize_text(text: str) -> str:
    """Удаляет токены и ключи из текста, заменяя на [REDACTED]."""
    if not text:
        return text
    result = text
    for pattern in _get_sensitive_patterns():
        try:
            result = re.sub(pattern, "[REDACTED]", result)
        except Exception:
            pass
    return result
