"""Команда .axs templates — управление текстовыми заготовками."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import logging
from .common import MAX_MSG, blockquote_html, html_escape, parse_args_rest

from ..store import template_delete, template_get, template_set, templates_list

logger = logging.getLogger("ApiXS.Templates")


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_templates(event, prefix, tail, user_id, respond)


async def cmd_templates(event, prefix: str, tail: str, user_id: int, respond) -> bool:
    """
    Менеджер шаблонов.
    Команды: list, add/set, get, edit, del.
    """
    args, rest = parse_args_rest(tail, 2)
    sub = (args[0] if args else "").lower()

    if sub in ("list", "ls") or (not sub and not rest):
        items = templates_list(user_id)
        if not items:
            return await respond(blockquote_html(f"<b>Шаблоны пусты.</b> Создать: <code>{prefix} te add [имя] [текст]</code>"), parse_mode="html")
        lines = ["<b>Шаблоны:</b>", ""]
        for name, content in items:
            preview = (content or "").replace("\n", " ")
            if len(preview) > 35:
                preview = preview[:32] + "..."
            lines.append(f"• <b>{name}</b> — <i>{preview}</i>")
        lines.append(f"\n<code>{prefix} te get [имя]</code>")
        await respond(blockquote_html("\n".join(lines)[:MAX_MSG - 50]), parse_mode="html")
        return True

    if sub in ("add", "set", "edit"):
        name = args[1] if len(args) > 1 else None
        if not name or not rest:
            return await respond(blockquote_html(f"Формат: <code>{prefix} te add [имя] [текст]</code>"), parse_mode="html")
        template_set(user_id, name, rest)
        await respond(blockquote_html(f"Шаблон <code>{name}</code> сохранён."), parse_mode="html")
        return True

    if sub == "get":
        name = args[1] if len(args) > 1 else (rest.split()[0] if rest else None)
        if not name:
            return await respond(blockquote_html(f"Формат: <code>{prefix} te get [имя]</code>"), parse_mode="html")
        content = template_get(user_id, name)
        if content is None:
            return await respond(blockquote_html(f"Шаблон <code>{name}</code> не найден."), parse_mode="html")
        await respond(blockquote_html(html_escape(content)), parse_mode="html")
        return True

    if sub in ("delete", "del", "rm"):
        name = args[1] if len(args) > 1 else (rest.split()[0] if rest else None)
        if not name:
            return await respond(blockquote_html(f"Формат: <code>{prefix} te del [имя]</code>"), parse_mode="html")
        if not template_delete(user_id, name):
            return await respond(blockquote_html(f"Шаблон <code>{name}</code> не найден."), parse_mode="html")
        await respond(blockquote_html(f"Шаблон <code>{name}</code> удалён."), parse_mode="html")
        return True

    help_msg = (
        "<b>Шаблоны</b>\n"
        f"• <code>{prefix} te add [имя] [текст]</code> — создать\n"
        f"• <code>{prefix} te get [имя]</code> — получить\n"
        f"• <code>{prefix} te ls</code> — список\n"
        f"• <code>{prefix} te rm [имя]</code> — удалить"
    )
    await respond(blockquote_html(help_msg), parse_mode="html")
    return True