"""Команда .axs translate."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



import asyncio
import requests
from .common import MAX_MSG, blockquote_html, parse_args

TRANSLATE_URL = "https://api.mymemory.translated.net/get"
CYRILLIC = set("абвгдеёжзийклмнопрстуфхцчшщъыьэюя")
logger = __import__("logging").getLogger(__name__)


def _translate_sync(text: str, to_lang: str, from_lang: str | None = None) -> str:
    to_lang = (to_lang or "en").strip().lower()[:6]
    if from_lang is None:
        low = text.lower()
        from_lang = "ru" if any(c in CYRILLIC for c in low) else "en"
    else:
        from_lang = (from_lang or "en").strip().lower()[:6]
    langpair = "{}|{}".format(from_lang, to_lang)
    r = requests.get(
        TRANSLATE_URL,
        params={"q": text, "langpair": langpair},
        timeout=15,
    )
    r.raise_for_status()
    data = r.json()
    tr = (data.get("responseData") or {}).get("translatedText") or ""
    return (tr or "").strip()


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_translate(event, prefix, tail, user_id, respond)


async def cmd_translate(event, prefix: str, tail: str, user_id: int, respond) -> bool:
    parts = parse_args(tail)
    if len(parts) < 2:
        await respond(blockquote_html(f"Формат: <code>{prefix} translate &lt;язык&gt; &lt;текст&gt;</code>. Языки: en, ru, de, fr, es, it."), parse_mode="html")
        return True
    to_lang = parts[0].lower()
    text = " ".join(parts[1:])
    loop = asyncio.get_running_loop()
    try:
        out = await loop.run_in_executor(
            None,
            lambda: _translate_sync(text, to_lang),
        )
    except Exception as e:
        import re
        err_msg = str(e)
        err_msg = re.sub(r"\b\d{8,10}:[A-Za-z0-9_-]{35}\b", "[TOKEN]", err_msg)
        err_msg = re.sub(r"\b(gsk_|sk-|AIza)[A-Za-z0-9_-]{20,}\b", "[API_KEY]", err_msg)
        logger.exception("translate error: %s", err_msg)
        await respond(blockquote_html("Ошибка перевода: " + err_msg[:300]), parse_mode="html")
        return True
    if not out:
        await respond(blockquote_html("Пустой ответ от сервиса перевода."), parse_mode="html")
        return True
    await respond(blockquote_html(out[:MAX_MSG - 50]), parse_mode="html")
    return True
