"""Команда .axs url (short)."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import re
from typing import Optional
from urllib.parse import quote

import requests

from .common import MAX_MSG, blockquote_html, parse_args


_URL_RE = re.compile(r"^https?://", re.IGNORECASE)


def _is_probably_url(s: str) -> bool:
    s = (s or "").strip()
    if not s:
        return False
    return bool(_URL_RE.match(s))


def _shorten_isgd(url: str, timeout: int = 10) -> Optional[str]:
    api = "https://is.gd/create.php?format=simple&url={}".format(quote(url, safe=""))
    r = requests.get(api, timeout=timeout)
    if r.status_code == 200:
        out = (r.text or "").strip()
        if out.startswith("http"):
            return out
    return None


def _shorten_tinyurl(url: str, timeout: int = 10) -> Optional[str]:
    api = "https://tinyurl.com/api-create.php?url={}".format(quote(url, safe=""))
    r = requests.get(api, timeout=timeout)
    if r.status_code == 200:
        out = (r.text or "").strip()
        if out.startswith("http"):
            return out
    return None


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_url(event, prefix, tail, respond)


async def cmd_url(event, prefix: str, tail: str, respond) -> bool:
    """
    .axs url short <url>
    """
    parts = parse_args(tail)
    sub = (parts[0] if parts else "").lower()
    rest = " ".join(parts[1:]).strip() if len(parts) > 1 else ""

    if sub != "short":
        await respond(blockquote_html(f"Формат: <code>{prefix} url short &lt;url&gt;</code>"), parse_mode="html")
        return True

    url = (rest or "").strip()
    if not url and event.is_reply and event.reply_to_msg_id:
        try:
            rm = await event.get_reply_message()
            url = (getattr(rm, "message", None) or "").strip()
        except Exception:
            url = ""

    if not _is_probably_url(url):
        await respond(blockquote_html(f"Укажите ссылку или ответьте на сообщение со ссылкой. Пример: <code>{prefix} url short https://example.com</code>"), parse_mode="html")
        return True

    try:
        short = _shorten_isgd(url) or _shorten_tinyurl(url)
    except Exception:
        short = None

    if not short:
        await respond(blockquote_html("Сервис сокращения ссылок недоступен."), parse_mode="html")
        return True

    await respond(blockquote_html("Сокращённая ссылка: " + short)[:MAX_MSG], parse_mode="html")
    return True

