"""Команда .axs version."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



import os

from .common import MAX_MSG, blockquote_html
from ..config import APIXS_VERSION

VERSION = APIXS_VERSION


def _read_changelog() -> str:
    """
    Читает CHANGELOG.md из корня проекта (если есть),
    иначе возвращает встроенный список.
    """
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    p = os.path.join(root, "CHANGELOG.md")
    if os.path.exists(p):
        try:
            with open(p, "r", encoding="utf-8") as f:
                return f.read().strip()
        except Exception:
            pass
    return None


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_version(event, prefix, respond)


async def cmd_version(event, prefix: str, respond) -> bool:
    changelog_text = _read_changelog()
    body = (changelog_text or "—")[:MAX_MSG - 200]
    html = (
        f"<b>ApiXS v{VERSION}</b>\n\n"
        f"<b>Изменения:</b>\n{body}\n\n"
        "<b>@YOUR_USERNAME</b>"
    )
    await respond(blockquote_html(html)[:MAX_MSG], parse_mode="html")
    return True
