"""Команда .axs voice / .v — транскрибация голосовых и кружочков через Groq Whisper."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import asyncio
import os
import tempfile
from typing import Optional

import requests
from telethon.tl.custom.message import Message

from ..config import Config
from .common import MAX_MSG, blockquote_html

logger = __import__("logging").getLogger(__name__)


def _pick_media(msg: Message) -> Optional[object]:
    """Возвращает объект медиа, который подходит для транскрибации."""
    if getattr(msg, "voice", None) is not None:
        return msg.voice
    if getattr(msg, "audio", None) is not None:
        return msg.audio
    if getattr(msg, "video_note", None) is not None:
        return msg.video_note
    return None


def _sanitize_error(msg: str) -> str:
    """Убирает токены/ключи из текста ошибки."""
    if not msg:
        return msg
    import re

    msg = re.sub(r"\b\d{8,10}:[A-Za-z0-9_-]{35}\b", "[TOKEN]", msg)
    msg = re.sub(r"\b(gsk_|sk-|AIza)[A-Za-z0-9_-]{20,}\b", "[API_KEY]", msg)
    return msg


def _transcribe_sync(path: str, api_key: str, model: str) -> str:
    """Синхронный вызов Groq Whisper API."""
    url = "https://api.groq.com/openai/v1/audio/transcriptions"
    headers = {
        "Authorization": f"Bearer {api_key}",
    }
    with open(path, "rb") as f:
        files = {"file": (os.path.basename(path), f, "application/octet-stream")}
        data = {
            "model": model or "whisper-large-v3-turbo",
            "language": "ru",
        }
        resp = requests.post(url, headers=headers, files=files, data=data, timeout=60)
    resp.raise_for_status()
    data = resp.json()
    text = (data.get("text") or "").strip()
    return text


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    if config is None:
        from ..config import load_config
        config = load_config()
    return await cmd_voice(event, config, tail, user_id, respond, prefix=prefix)


async def cmd_voice(event, config: Config, tail: str, user_id: int, respond, *, prefix: Optional[str] = None) -> bool:
    """Транскрибация голосовых/аудио/кружочков через Groq Whisper."""
    p = prefix or config.command_prefix

    if not config.groq_api_key:
        await respond(blockquote_html("Транскрибация недоступна: GROQ_API_KEY не задан."), parse_mode="html")
        return True

    reply = await event.get_reply_message()
    if not reply:
        await respond(blockquote_html(f"Ответьте на голосовое/кружочек и отправьте <code>{p} v</code>."), parse_mode="html")
        return True

    media = _pick_media(reply)
    if media is None:
        await respond(blockquote_html("Нужно ответить на голосовое, аудио или кружочек."), parse_mode="html")
        return True

    tmp_path = tempfile.mktemp(prefix="apixs_voice_", suffix=".ogg")
    try:
        path = await event.client.download_media(reply, file=tmp_path)
        if not path or not os.path.isfile(path):
            await respond(blockquote_html("Не удалось скачать голосовое."), parse_mode="html")
            return True
        size = os.path.getsize(path)
        if size > 25 * 1024 * 1024:
            await respond(blockquote_html("Файл больше 25 МБ. Лимит Whisper — 25 МБ."), parse_mode="html")
            return True

        loop = asyncio.get_running_loop()
        whisper_model = (os.getenv("WHISPER_MODEL") or "whisper-large-v3-turbo").strip()
        if config.is_bot:
            target = await event.reply("<i>🎙 Распознаю голосовое…</i>", parse_mode="html")
        else:
            try:
                await event.edit("<i>🎙 Распознаю голосовое…</i>", parse_mode="html")
                target = event
            except Exception:
                target = await event.reply("<i>🎙 Распознаю голосовое…</i>", parse_mode="html")
        try:
            text = await loop.run_in_executor(
                None,
                lambda: _transcribe_sync(path, config.groq_api_key, whisper_model),
            )
        except Exception as e:
            err_msg = _sanitize_error(str(e))
            logger.exception("voice transcribe error: %s", err_msg)
            await target.edit(blockquote_html("Ошибка Groq Whisper: " + err_msg[:300]), parse_mode="html")
            return True

        if not text:
            await target.edit(blockquote_html("Пустой ответ от Whisper."), parse_mode="html")
            return True
        result = blockquote_html(f"<b>Расшифровка</b>\n\n{text}")
        await target.edit(result[:MAX_MSG], parse_mode="html")
        return True
    finally:
        try:
            if tmp_path and os.path.isfile(tmp_path):
                os.remove(tmp_path)
        except OSError:
            pass

