"""Команда .axs weather — исправленная версия для ApiXS."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



import asyncio
import requests
from urllib.parse import quote
from .common import MAX_MSG, blockquote_html

logger = __import__("logging").getLogger(__name__)


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> None:
    await cmd_weather(event, (tail or "").strip(), prefix, respond)


async def cmd_weather(event, city: str, prefix: str, respond) -> None:
    if not city or not city.strip():
        await respond(blockquote_html(f"Укажите город. Пример: <code>{prefix} weather Москва</code>"), parse_mode="html")
        return

    city = city.strip()[:100]
    url = f"https://wttr.in/{quote(city)}?m&lang=ru&format=%l|%C|%t|%f|%h|%w|%P"
    loop = asyncio.get_running_loop()

    try:
        def _get():
            headers = {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
                "Accept-Language": "ru-RU,ru;q=0.9"
            }
            r = requests.get(url, headers=headers, timeout=12)
            r.raise_for_status()
            return r.text.strip()

        out = await loop.run_in_executor(None, _get)
        if not out or "|" not in out:
            raise ValueError("Некорректный формат ответа")

        parts = out.split("|")
        loc, cond, temp, feels, hum, wind, press = parts
        body = (
            f"<b>Погода: {loc}</b>\n"
            f"Температура: {temp} (ощущается {feels})\n"
            f"Состояние: {cond}\n"
            f"Влажность: {hum} · Ветер: {wind} · Давление: {press}"
        )
        await respond(blockquote_html(body), parse_mode="html")

    except Exception as e:
        logger.debug("Weather error for %s: %s", city, e)
        await respond(blockquote_html(f"Не удалось получить погоду для «{city}». Попробуйте позже или город латиницей."), parse_mode="html")