# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually

from __future__ import annotations

import os
import io
import tempfile
import requests as req
from typing import Optional
from PIL import Image, ImageDraw, ImageFont, ImageOps, ImageFilter

from ..session_crypto import decrypt_session
from ..store import user_token_get
from .common import MAX_MSG, blockquote_html

logger = __import__("logging").getLogger(__name__)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FONTS_DIR = os.path.join(BASE_DIR, "assets", "fonts")

def _get_token_for_user(user_id: int) -> Optional[str]:
    enc = None
    try:
        enc = user_token_get(user_id, "yandex_music")
    except Exception as e:
        logger.debug("user_token_get ym: %s", e)
    if enc:
        try:
            return decrypt_session(enc)
        except Exception as e:
            logger.warning("decrypt ym token: %s", e)
    env_token = (os.getenv("YANDEX_MUSIC_TOKEN") or "").strip()
    return env_token or None

def _fmt_mmss(sec: int) -> str:
    sec = max(0, int(sec))
    m, s = divmod(sec, 60)
    return f"{m:02d}:{s:02d}"

async def _send_yandex_music_card(
    event,
    respond,
    title: str,
    artist_names: str,
    track_url: Optional[str],
    cover_url: Optional[str] = None,
    cover_uri: Optional[str] = None,
    progress_sec: Optional[int] = None,
    duration_sec: Optional[int] = None,
    is_paused: bool = False,
) -> None:
    card_path = None
    try:
        from PIL import Image, ImageDraw, ImageFont, ImageOps, ImageFilter
        from pathlib import Path
        import io, tempfile, requests as req

        CARD_W, CARD_H = 800, 400
        COVER_SIZE = 340
        PADDING = 30
        BG_COLOR = (18, 18, 18)

        cmd_dir = Path(__file__).resolve().parent
        logo_path = cmd_dir / "assets" / "images" / "yandex_logo.png"
        bold_f_path = os.path.join(FONTS_DIR, "DejaVuSans-Bold.ttf")
        reg_f_path = os.path.join(FONTS_DIR, "DejaVuSans.ttf")

        raw_img = None
        if cover_url:
            try:
                r = req.get(cover_url, timeout=8)
                if r.ok: raw_img = Image.open(io.BytesIO(r.content))
            except: pass
        if raw_img is None and cover_uri:
            url = "https://" + cover_uri.replace("%%", "400x400")
            try:
                r = req.get(url, timeout=8)
                if r.ok: raw_img = Image.open(io.BytesIO(r.content))
            except: pass
        if raw_img is None:
            raw_img = Image.new("RGB", (COVER_SIZE, COVER_SIZE), (30, 30, 30))

        bg = ImageOps.fit(raw_img.copy(), (CARD_W, CARD_H), Image.LANCZOS)
        bg = bg.filter(ImageFilter.GaussianBlur(radius=50))
        darken = Image.new("RGBA", (CARD_W, CARD_H), (10, 10, 10, 165))
        card = Image.new("RGBA", (CARD_W, CARD_H))
        card.paste(bg, (0, 0))
        card = Image.alpha_composite(card, darken).convert("RGB")
        draw = ImageDraw.Draw(card)

        cover_x, cover_y = PADDING, (CARD_H - COVER_SIZE) // 2
        shadow_mask = Image.new("L", (COVER_SIZE + 20, COVER_SIZE + 20), 0)
        ImageDraw.Draw(shadow_mask).rounded_rectangle([0, 0, COVER_SIZE + 20, COVER_SIZE + 20], radius=30, fill=110)
        card.paste((0, 0, 0), (cover_x - 10, cover_y - 10), mask=shadow_mask)

        def get_rounded(img, size, radius, bg_pixel):
            img = ImageOps.fit(img.convert("RGBA"), (size, size), Image.LANCZOS)
            mask = Image.new("L", (size*4, size*4), 0)
            ImageDraw.Draw(mask).rounded_rectangle([0, 0, size*4, size*4], radius=radius*4, fill=255)
            mask = mask.resize((size, size), Image.LANCZOS)
            res = Image.new("RGBA", (size, size), bg_pixel + (255,))
            res.paste(img, (0, 0), mask=mask)
            return res.convert("RGBA")

        rounded_cover = get_rounded(raw_img, COVER_SIZE, 25, card.getpixel((cover_x, cover_y)))
        if is_paused:
            p_overlay = Image.new("RGBA", (COVER_SIZE, COVER_SIZE), (0, 0, 0, 90))
            p_draw = ImageDraw.Draw(p_overlay)
            p_draw.rectangle([140, 120, 165, 220], fill=(255, 255, 255, 220))
            p_draw.rectangle([185, 120, 210, 220], fill=(255, 255, 255, 220))
            rounded_cover = Image.alpha_composite(rounded_cover, p_overlay)
        card.paste(rounded_cover, (cover_x, cover_y), mask=rounded_cover)

        text_x = cover_x + COVER_SIZE + PADDING
        max_w = CARD_W - text_x - PADDING
        def get_font(txt, path, start_s, m_w):
            s = start_s
            f = ImageFont.truetype(path, s)
            while f.getlength(txt) > m_w and s > 18:
                s -= 1
                f = ImageFont.truetype(path, s)
            return f

        f_title = get_font(title, bold_f_path, 36, max_w)
        draw.text((text_x, 90), title, font=f_title, fill=(255, 255, 255))
        f_artist = get_font(artist_names, reg_f_path, 26, max_w)
        draw.text((text_x, 145), artist_names, font=f_artist, fill=(180, 180, 180))

        if duration_sec and duration_sec > 0:
            bar_x1, bar_x2 = text_x, CARD_W - PADDING
            bar_y, bar_h = 260, 10
            draw.rounded_rectangle((bar_x1, bar_y, bar_x2, bar_y + bar_h), radius=5, fill=(60, 60, 60))
            ratio = max(0, min(1, (progress_sec or 0) / duration_sec))
            if ratio > 0:
                draw.rounded_rectangle((bar_x1, bar_y, bar_x1 + (bar_x2-bar_x1)*ratio, bar_y + bar_h), radius=5, fill=(255, 204, 0))
            f_lbl = ImageFont.truetype(reg_f_path, 18)
            draw.text((bar_x1, bar_y + 20), _fmt_mmss(progress_sec or 0), font=f_lbl, fill=(150, 150, 150))
            tw = draw.textbbox((0,0), _fmt_mmss(duration_sec), font=f_lbl)[2]
            draw.text((bar_x2 - tw, bar_y + 20), _fmt_mmss(duration_sec), font=f_lbl, fill=(150, 150, 150))

        sig_text = "Yandex Music" + (" (Paused)" if is_paused else "")
        f_sig = ImageFont.truetype(bold_f_path, 18)
        
        logo_icon = None
        if logo_path.exists():
            try:
                logo_icon = Image.open(str(logo_path)).convert("RGBA")
                icon_h = 26
                icon_w = int(logo_icon.width * (icon_h / logo_icon.height))
                logo_icon = logo_icon.resize((icon_w, icon_h), Image.LANCZOS)
            except Exception as e:
                logger.debug("ym card logo load: %s", e)

        gap = 10
        tw_sig = draw.textbbox((0, 0), sig_text, font=f_sig)[2]
        icon_w_f = logo_icon.width if logo_icon else 0
        total_w = icon_w_f + (gap if logo_icon else 0) + tw_sig
        
        r1_x, r1_y = text_x - 15, CARD_H - 80
        draw.rounded_rectangle((r1_x, r1_y, text_x + total_w + 15, CARD_H - 30), radius=12, fill=(0, 0, 0, 50))

        curr_x = text_x
        if logo_icon:
            card.paste(logo_icon, (curr_x, r1_y + (50 - logo_icon.height)//2), mask=logo_icon)
            curr_x += icon_w_f + gap
        
        draw.text((curr_x, r1_y + (50 - 18)//2 - 2), sig_text, font=f_sig, fill=(255, 204, 0))

        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            card.save(tmp.name, "PNG")
            card_path = tmp.name

    except Exception as e:
        logger.exception("ym card generate error")
        await event.reply(f"❌ Критическая ошибка генерации: {e}")
        card_path = None

    if card_path:
        # Эмодзи будут анимированными только при наличии Telegram Premium у юзера
        emoji_note = '<tg-emoji data-emoji-id="5188705588925702510">🎵</tg-emoji>'
        emoji_mic  = '<tg-emoji data-emoji-id="5382360961313152917">🎤</tg-emoji>'

        caption = f"{emoji_note} <b>{title}</b>\n{emoji_mic} {artist_names}"
        if track_url:
            emoji_music = '<tg-emoji data-emoji-id="5212941939053175244">🎧</tg-emoji>'
            caption += f'\n\n{emoji_music} | <a href="{track_url}">Открыть в Яндекс Музыке →</a>'
        
        try:
            await event.client.send_file(
                event.chat_id,
                card_path,
                caption=caption,
                parse_mode="html",
                reply_to=event.id,
            )
            try:
                await event.delete()
            except: pass
        finally:
            if os.path.exists(card_path):
                os.remove(card_path)
    else:
        await respond(blockquote_html(f"🎤 {artist_names}<br>🎵 {title}"), parse_mode="html")


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_yandex_music_now_playing(event, tail or "np", user_id, respond)


async def cmd_yandex_music_now_playing(event, tail: str, user_id: int, respond) -> bool:
    
    try:
        await event.edit("<code>⏳ Обработка...</code>", parse_mode="html")
    except Exception:
        pass 

    token = _get_token_for_user(user_id)
    if not token:
        await respond(blockquote_html("Токен Яндекс Музыки не настроен. Настройте в личном кабинете: YOUR_DOMAIN/user"), parse_mode="html")
        return True

    track_title: Optional[str] = None
    artist_names: Optional[str] = None
    track_url: Optional[str] = None
    cover_url: Optional[str] = None
    progress_sec: Optional[int] = None
    duration_sec: Optional[int] = None
    is_paused: bool = False

    try:
        import requests as req

        # 1. ПРОБУЕМ ВНЕШНИЙ API (дает прогресс и статус паузы)
        api_url = (os.getenv("YANDEX_MUSIC_API_URL") or "https://track.mipoh.ru").rstrip("/")
        headers = {
            "User-Agent": "Mozilla/5.0",
            "Accept": "application/json",
            "ya-token": token,
        }

        try:
            r = req.get(f"{api_url}/get_current_track_beta", headers=headers, timeout=8)
            if r.ok:
                data = r.json() or {}
                
                # Статус паузы
                is_paused = data.get("paused", False)
                
                # Парсим время (в JSON приходят строки, переводим в числа)
                try:
                    p_ms = int(data.get("progress_ms") or 0)
                    d_ms = int(data.get("duration_ms") or 0)
                    if d_ms > 0:
                        duration_sec = d_ms // 1000
                        progress_sec = p_ms // 1000
                except (ValueError, TypeError):
                    pass

                t_data = data.get("track") or {}
                track_title = (t_data.get("title") or "").strip()
                
                # Обработка артистов (может быть списком или строкой)
                raw_artist = t_data.get("artist", "")
                if isinstance(raw_artist, list):
                    artist_names = ", ".join([str(a).strip() for a in raw_artist if str(a).strip()])
                else:
                    artist_names = str(raw_artist).strip()

                if track_title and artist_names:
                    track_id = t_data.get("track_id")
                    if track_id:
                        track_url = f"https://music.yandex.ru/track/{track_id}"
                    cover_url = (t_data.get("img") or "").strip() or None
        
        except Exception as e:
            logger.debug("ym external api error: %s", e)

        # 2. ЕСЛИ ВНЕШНИЙ API НЕ ДАЛ РЕЗУЛЬТАТА — FALLBACK НА ЛОКАЛЬНУЮ БИБЛИОТЕКУ
        if not track_title or not artist_names:
            try:
                from yandex_music import Client
                client = Client(token).init()
                
                queues = client.queues_list()
                track = None
                for q in (queues or []):
                    try:
                        queue = client.queue(q.id)
                        current = queue.get_current_track()
                        if current:
                            track = current.fetch_track()
                            if track: break
                    except: continue

                if track:
                    track_title = (getattr(track, "title", None) or "Без названия").strip()
                    artists = getattr(track, "artists", None) or []
                    artist_names = ", ".join(
                        (getattr(a, "name", None) or "").strip()
                        for a in artists if getattr(a, "name", None)
                    ) or "Неизвестный исполнитель"
                    
                    albums = getattr(track, "albums", None) or []
                    if albums:
                        album = albums[0]
                        cover_url = "https://" + album.cover_uri.replace("%%", "1000x1000")
                        t_id = getattr(track, "id", None)
                        a_id = getattr(album, "id", None)
                        if t_id and a_id:
                            track_url = f"https://music.yandex.ru/album/{a_id}/track/{t_id}"
            except Exception as e:
                logger.debug("ym local library fallback error: %s", e)

        # 3. ОТПРАВКА РЕЗУЛЬТАТА
        if track_title and artist_names:
            await _send_yandex_music_card(
                event,
                respond,
                track_title,
                artist_names,
                track_url,
                cover_url=cover_url,
                progress_sec=progress_sec,
                duration_sec=duration_sec,
                is_paused=is_paused
            )
            return True
        else:
            await respond(blockquote_html("Сейчас ничего не играет."), parse_mode="html")
            return True

    except Exception as e:
        logger.exception("ym np command error")
        await respond(blockquote_html("Не удалось получить данные: " + str(e)[:200]), parse_mode="html")
        return True