"""Точка входа для .ynow — сейчас играет (Yandex Music)."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from .yandex_music import cmd_yandex_music_now_playing


async def handle(event, tail: str, user_id: int, respond, config=None, prefix: str = ".axs", **kwargs) -> bool:
    return await cmd_yandex_music_now_playing(event, tail or "np", user_id, respond)
