# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually

import asyncio
import logging
import os
import sys
import threading
import time
from dataclasses import replace
from pathlib import Path

from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent / ".env")

# Чтобы логи из ApiXS.commands.* отображались, настраиваем корневой логгер до импорта команд
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logging.getLogger("ApiXS").setLevel(logging.DEBUG)
logging.getLogger("ApiXS.commands").setLevel(logging.DEBUG)

from telethon.errors import FloodWaitError
from ApiXS.config import load_config
from ApiXS.groq_client import complete as groq_complete
from ApiXS.handler import create_telegram_client, install_handlers, register_online_tracker_worker
from ApiXS.commands import start_reminder_worker
from ApiXS.session_crypto import decrypt_session
from ApiXS import store as store_mod

async def _check_groq(config) -> None:
    await groq_complete(
        api_key=config.groq_api_key,
        model=config.groq_model,
        prompt="Hi",
        system=None,
        history=None,
    )


def _run_session(config, session_str: str, index: int, _is_first: bool, allowed_users: list | None = None, account_name: str = "unknown"):
    """Запускает одну сессию в отдельном потоке с собственным event loop."""
    # Даже если в .env задан TELEGRAM_BOT_TOKEN, user‑клиент должен работать как user, а не как bot.
    config = replace(config, telegram_bot_token=None)
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    client = create_telegram_client(config, session_str=session_str, loop=loop)
    loop.run_until_complete(client.connect())
    if not loop.run_until_complete(client.is_user_authorized()):
        logging.getLogger("ApiXS").warning("Session '%s' not authorized, skipping.", account_name)
        try:
            loop.run_until_complete(client.disconnect())
        except Exception:
            pass
        try:
            loop.close()
        except Exception:
            pass
        return
    install_handlers(client, config, allowed_users=allowed_users, account_name=account_name)
    if _is_first:
        try:
            me = loop.run_until_complete(client.get_me())
            user_id = me.id if me else 0
        except Exception:
            user_id = 0
        start_reminder_worker(client, user_id, loop)
        try:
            register_online_tracker_worker(client, user_id, loop)
        except Exception:
            pass
    with client:
        client.run_until_disconnected()


async def _run_bot_async(config):
    """Старт бота (подтверждения /start). Возвращает client для run_until_disconnected."""
    logger = logging.getLogger("ApiXS")
    client = create_telegram_client(config, loop=asyncio.get_running_loop())
    while True:
        try:
            await client.start(bot_token=config.telegram_bot_token)
            break
        except FloodWaitError as e:
            logger.warning("Telegram FloodWait: ждём %s с перед повторной попыткой входа бота.", e.seconds)
            await asyncio.sleep(e.seconds)
    install_handlers(client, config)
    try:
        start_reminder_worker(client, 0, asyncio.get_running_loop())
    except Exception:
        pass
    return client


def _run_bot(config):
    """Запуск только бота (для потока). Бот — для подтверждений /start и т.п."""
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    client = loop.run_until_complete(_run_bot_async(config))
    with client:
        client.run_until_disconnected()


def _run_user_session_daemon(user_config, row: dict, stop_event: threading.Event) -> None:
    """Запускает одного user-клиента для одной DB-сессии (в отдельном потоке)."""
    logger = logging.getLogger("ApiXS")
    session_id = int(row.get("id") or 0)
    encrypted = row.get("encrypted_session") or ""
    tg_id = row.get("telegram_id")
    account_name = str(row.get("username") or tg_id or f"db_{session_id}")

    try:
        session_str = decrypt_session(encrypted)
    except Exception as e:
        logger.error("Session %s decrypt failed: %s", session_id, e)
        return

    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    client = None
    try:
        client = create_telegram_client(user_config, session_str=session_str, loop=loop)
        loop.run_until_complete(client.connect())
        if not loop.run_until_complete(client.is_user_authorized()):
            logger.warning("DB session '%s' not authorized, skipping.", account_name)
            try:
                loop.run_until_complete(client.disconnect())
            except Exception:
                pass
            return

        install_handlers(client, user_config, allowed_users=user_config.allowed_users, account_name=account_name)
        try:
            me = loop.run_until_complete(client.get_me())
            user_id = me.id if me else 0
        except Exception:
            user_id = 0
        start_reminder_worker(client, user_id, loop)
        try:
            register_online_tracker_worker(client, user_id, loop)
        except Exception:
            pass
        logger.info("User session connected: %s (session_id=%s).", account_name, session_id)

        def watcher():
            # stop or periodic touch
            while not stop_event.is_set():
                stop_event.wait(timeout=120)
                if stop_event.is_set():
                    break
                try:
                    store_mod.web_touch_session_last_used(session_id)
                except Exception:
                    pass
            try:
                asyncio.run_coroutine_threadsafe(client.disconnect(), loop).result(timeout=10)
            except Exception:
                pass

        threading.Thread(target=watcher, name=f"ApiXS-stopwatch-{session_id}", daemon=True).start()
        with client:
            client.run_until_disconnected()
    finally:
        try:
            loop.close()
        except Exception:
            pass


def _run_user_sessions_manager(config) -> None:
    """
    Менеджер мультисессий:
    - читает все active+approved сессии из БД
    - поднимает по user-клиенту на каждую
    - периодически добавляет/останавливает без перезапуска
    """
    logger = logging.getLogger("ApiXS")
    poll_sec = 30
    user_config = replace(config, telegram_bot_token=None)
    running: dict[int, tuple[threading.Thread, threading.Event]] = {}

    while True:
        try:
            rows = store_mod.web_list_active_approved_sessions(limit=200) or []
        except Exception as e:
            logger.error("DB list sessions failed: %s", e)
            rows = []

        desired_ids = {int(r.get("id") or 0) for r in rows if int(r.get("id") or 0) > 0}

        # stop removed
        for sid in list(running.keys()):
            if sid not in desired_ids:
                t, ev = running.pop(sid)
                ev.set()

        # start new
        for r in rows:
            sid = int(r.get("id") or 0)
            if sid <= 0 or sid in running:
                continue
            ev = threading.Event()
            t = threading.Thread(
                target=_run_user_session_daemon,
                args=(user_config, r, ev),
                name=f"ApiXS-user-{sid}",
                daemon=True,
            )
            running[sid] = (t, ev)
            t.start()

        time.sleep(poll_sec)


def main() -> int:
    config = load_config()

    logging.basicConfig(
        level=getattr(logging, config.log_level, logging.INFO),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    logger = logging.getLogger("ApiXS")
    logger.info("Starting ApiXS (Groq, .axs commands)")

    # Groq проверка в изолированном loop — не трогает глобальный
    groq_loop = asyncio.new_event_loop()
    try:
        groq_loop.run_until_complete(_check_groq(config))
    except Exception as e:
        error_msg = str(e)
        if "403" in error_msg or "Forbidden" in error_msg or "PermissionDenied" in error_msg:
            print(
                "\033[33m⚠️  AI недоступен (требуется VPN). Продолжаем работу без AI функций.\033[0m",
                file=sys.stdout,
            )
        else:
            print(
                "\033[33m⚠️  GROQ_API_KEY недоступен. AI функции будут недоступны.\033[0m",
                file=sys.stdout,
            )
    finally:
        try:
            groq_loop.close()
        except Exception:
            pass

    accounts = config.telegram_accounts
    has_bot = config.is_bot

    if has_bot:
        thread_bot = threading.Thread(target=_run_bot, args=(config,), name="ApiXS-bot", daemon=True)
        thread_user = threading.Thread(target=_run_user_sessions_manager, args=(config,), name="ApiXS-users", daemon=True)
        thread_bot.start()
        thread_user.start()
        logger.info("Bot started (confirmations). User sessions starting (DB multi-session).")
        print("ApiXS: бот (подтверждения) + мультисессия из БД (все одобренные). Ctrl+C — выход.")
        try:
            thread_bot.join()
            thread_user.join()
        except KeyboardInterrupt:
            pass
        return 0

    if not accounts:
        print("⚠️  Нет валидных аккаунтов. Статус-сайт работает. Press Ctrl+C to stop.")
        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            pass
        return 0

    if len(accounts) == 1:
        acc = accounts[0]
        # Изолированный loop для одиночной сессии
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        client = create_telegram_client(config, session_str=acc["session"], loop=loop)
        loop.run_until_complete(client.connect())
        if not loop.run_until_complete(client.is_user_authorized()):
            logger.warning("Session '%s' not authorized. Login via /connect page.", acc["name"])
            try:
                loop.run_until_complete(client.disconnect())
            except Exception:
                pass
            loop.close()
            try:
                while True:
                    time.sleep(5)
            except KeyboardInterrupt:
                pass
            return 0
        install_handlers(client, config, allowed_users=acc.get("allowed_users"), account_name=acc["name"])
        try:
            me = loop.run_until_complete(client.get_me())
            user_id = me.id if me else 0
        except Exception:
            user_id = 0
        start_reminder_worker(client, user_id, loop)
        try:
            register_online_tracker_worker(client, user_id, loop)
        except Exception:
            pass
        print("ApiXS is running ({}). Press Ctrl+C to stop.".format(acc["name"]))
        with client:
            client.run_until_disconnected()
    else:
        threads = [
            threading.Thread(
                target=_run_session,
                args=(config, acc["session"], i, i == 0, acc.get("allowed_users"), acc["name"]),
                name="ApiXS-{}".format(acc["name"]),
            )
            for i, acc in enumerate(accounts)
        ]
        for t in threads:
            t.daemon = True
            t.start()
        names = ", ".join(a["name"] for a in accounts)
        print("ApiXS is running ({} accounts: {}). Press Ctrl+C to stop.".format(len(accounts), names))
        try:
            for t in threads:
                t.join()
        except KeyboardInterrupt:
            pass
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
