"""Отдельное хранилище anti-delete в MySQL (AD_DATABASE_URL).

Схема:
- axs_anti_delete_config: включён ли антиделит для чата конкретного аккаунта
- axs_message_cache: кэш последних сообщений (для сопоставления при удалении/редактировании)
- axs_deleted_log: лог удалённых сообщений
"""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import functools
import logging
import os
import threading
from contextlib import contextmanager
from datetime import datetime
from typing import Any, Callable, List, Optional, Tuple
from urllib.parse import urlparse

import pymysql
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)


def _sanitize_log_msg(msg: str) -> str:
    """Удаляет токены и чувствительные данные из логов."""
    if not msg:
        return msg
    import re

    # Telegram bot tokens
    msg = re.sub(r"\b\d{8,10}:[A-Za-z0-9_-]{35}\b", "[TOKEN]", msg)
    # API keys
    msg = re.sub(r"\b(gsk_|sk-|AIza)[A-Za-z0-9_-]{20,}\b", "[API_KEY]", msg)
    # Database URLs (маскируем пароль)
    msg = re.sub(r"(mysql|postgres)://[^:]+:[^@]+@", r"\1://user:***@", msg)
    return msg


_CACHE_MAX_AGE_HOURS = 48
_tls = threading.local()

_AD_SCHEMA_INIT_DONE = False
_AD_SCHEMA_INIT_LOCK = threading.Lock()
_PING_THROTTLE_SEC = 60


def _get_conn() -> Optional[pymysql.Connection]:
    return getattr(_tls, "conn", None)


def _set_conn(conn: Optional[pymysql.Connection]) -> None:
    _tls.conn = conn


def _get_last_ping() -> float:
    return getattr(_tls, "last_ping", 0.0)


def _set_last_ping(t: float) -> None:
    _tls.last_ping = t


def _parse_mysql_url(url: str) -> dict:
    u = urlparse(url)
    path = (u.path or "").strip("/")
    return {
        "host": u.hostname or "localhost",
        "port": int(u.port or 3306),
        "user": u.username or "root",
        "password": u.password or "",
        "database": path or "your_database",
        "charset": "utf8mb4",
    }


def _get_url() -> str:
    # Отдельный URL для антиделита
    return (os.getenv("AD_DATABASE_URL") or "").strip()


def _connect() -> pymysql.Connection:
    url = _get_url()
    if not url:
        raise RuntimeError("AD_DATABASE_URL not set")
    params = _parse_mysql_url(url)
    params["connect_timeout"] = 10
    conn = pymysql.connect(**params)
    _set_conn(conn)
    return conn


def _close_conn() -> None:
    conn = _get_conn()
    if conn:
        try:
            conn.close()
        except Exception:
            pass
        _set_conn(None)


_CONN_ERRORS = (
    pymysql.err.OperationalError,
    pymysql.err.InterfaceError,
    ValueError,
)


def _retry_on_conn_error(fn: Callable) -> Callable:
    """Повтор операции при ошибке соединения (Lost connection, read of closed file)."""

    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        for attempt in range(2):
            try:
                return fn(*args, **kwargs)
            except _CONN_ERRORS as e:
                if attempt == 0:
                    _close_conn()
                    logger.info("AD MySQL reconnect after: %s", _sanitize_log_msg(str(e)))
                    continue
                logger.warning("ad_db: %s", _sanitize_log_msg(str(e)))
                raise
        return None  # unreachable

    return wrapper


@contextmanager
def _conn_cursor(commit: bool = True):
    """Контекстный менеджер для курсора. commit=False для read-only."""
    import time as _time
    url = _get_url()
    if not url:
        raise RuntimeError("AD_DATABASE_URL not set")
    conn = _get_conn()
    if conn is None:
        _connect()
        conn = _get_conn()
    else:
        now = _time.time()
        if (now - _get_last_ping()) >= _PING_THROTTLE_SEC:
            try:
                conn.ping(reconnect=True)
                _set_last_ping(now)
            except Exception:
                _close_conn()
                _connect()
                conn = _get_conn()
                _set_last_ping(_time.time())
    cur = conn.cursor(pymysql.cursors.DictCursor)
    try:
        yield cur
        if commit:
            conn.commit()
    except Exception as e:
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
        if isinstance(e, _CONN_ERRORS):
            _close_conn()
        logger.warning("ad_db: %s", _sanitize_log_msg(str(e)))
        raise
    finally:
        cur.close()


@_retry_on_conn_error
def _init_schema():
    """Создание таблиц anti-delete. Совместимо со старой схемой без account_id."""
    with _conn_cursor() as cur:
        # Пользователи (телеграм-аккаунты), у которых работает антиделит
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS axs_ad_users (
                account_id BIGINT PRIMARY KEY,
                account_name VARCHAR(64),
                created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
                last_seen_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6)
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS axs_anti_delete_config (
                account_id BIGINT NOT NULL DEFAULT 0,
                chat_id BIGINT NOT NULL,
                is_on TINYINT(1) NOT NULL DEFAULT 1,
                PRIMARY KEY (account_id, chat_id)
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS axs_message_cache (
                account_id BIGINT NOT NULL DEFAULT 0,
                chat_id BIGINT NOT NULL,
                msg_id INT NOT NULL,
                text TEXT,
                sender_id BIGINT,
                is_bot TINYINT(1) NOT NULL DEFAULT 0,
                created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
                PRIMARY KEY (account_id, chat_id, msg_id),
                INDEX (account_id, msg_id)
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS axs_deleted_log (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                account_id BIGINT NOT NULL DEFAULT 0,
                chat_id BIGINT NOT NULL,
                msg_id INT NOT NULL,
                text TEXT,
                sender_id BIGINT,
                deleted_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
                INDEX (account_id, chat_id, deleted_at)
            )
            """
        )
        # Миграция: если старая схема без account_id, пересоздаём таблицы
        try:
            cur.execute("SELECT account_id FROM axs_anti_delete_config LIMIT 1")
        except Exception:
            for t in ("axs_deleted_log", "axs_message_cache", "axs_anti_delete_config"):
                try:
                    cur.execute(f"DROP TABLE IF EXISTS {t}")
                except Exception:
                    pass
            for stmt in (
                """
                CREATE TABLE IF NOT EXISTS axs_anti_delete_config (
                    account_id BIGINT NOT NULL DEFAULT 0,
                    chat_id BIGINT NOT NULL,
                    is_on TINYINT(1) NOT NULL DEFAULT 1,
                    PRIMARY KEY (account_id, chat_id)
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS axs_message_cache (
                    account_id BIGINT NOT NULL DEFAULT 0,
                    chat_id BIGINT NOT NULL,
                    msg_id INT NOT NULL,
                    text TEXT,
                    sender_id BIGINT,
                    is_bot TINYINT(1) NOT NULL DEFAULT 0,
                    created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
                    PRIMARY KEY (account_id, chat_id, msg_id),
                    INDEX (account_id, msg_id)
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS axs_deleted_log (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    account_id BIGINT NOT NULL DEFAULT 0,
                    chat_id BIGINT NOT NULL,
                    msg_id INT NOT NULL,
                    text TEXT,
                    sender_id BIGINT,
                    deleted_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
                    INDEX (account_id, chat_id, deleted_at)
                )
                """,
            ):
                try:
                    cur.execute(stmt)
                except Exception as e:
                    # 1050: table already exists
                    if getattr(e, "args", (None,))[0] != 1050:
                        raise

        # Миграция: добавляем флаг is_bot в кэш сообщений (если старые таблицы без колонки).
        try:
            cur.execute(
                "ALTER TABLE axs_message_cache ADD COLUMN is_bot TINYINT(1) NOT NULL DEFAULT 0"
            )
        except Exception:
            pass


def _ensure_init():
    global _AD_SCHEMA_INIT_DONE
    if _AD_SCHEMA_INIT_DONE:
        return
    with _AD_SCHEMA_INIT_LOCK:
        if _AD_SCHEMA_INIT_DONE:
            return
        try:
            _init_schema()
            _AD_SCHEMA_INIT_DONE = True
        except Exception as e:
            logger.exception("ad schema init: %s", e)
            raise


# --- anti-delete config ---


@_retry_on_conn_error
def ad_user_upsert(account_id: int, account_name: str = "") -> None:
    """Регистрирует/обновляет пользователя (владельца аккаунта) в отдельной таблице."""
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_ad_users (account_id, account_name, created_at, last_seen_at)
            VALUES (%s, %s, NOW(6), NOW(6))
            ON DUPLICATE KEY UPDATE
                account_name = VALUES(account_name),
                last_seen_at = NOW(6)
            """,
            (account_id, (account_name or "").strip()[:64]),
        )


@_retry_on_conn_error
def anti_delete_set(chat_id: int, is_on: bool, account_id: int = 0) -> None:
    """Включает/выключает антиделит для чата конкретного аккаунта."""
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_anti_delete_config (account_id, chat_id, is_on)
            VALUES (%s, %s, %s)
            ON DUPLICATE KEY UPDATE is_on = VALUES(is_on)
            """,
            (account_id, chat_id, 1 if is_on else 0),
        )


@_retry_on_conn_error
def anti_delete_get(chat_id: int, account_id: int = 0) -> bool:
    """Возвращает True, если антиделит включён для чата и аккаунта.

    По умолчанию (если записи нет) считаем, что антиделит ВКЛЮЧЁН.
    """
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT is_on FROM axs_anti_delete_config WHERE account_id = %s AND chat_id = %s",
            (account_id, chat_id),
        )
        row = cur.fetchone()
        if row is None:
            return True
        return bool(row["is_on"])


@_retry_on_conn_error
def anti_delete_chats_on(account_id: int = 0) -> List[int]:
    """Список chat_id, где включён антиделит для заданного аккаунта."""
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT chat_id FROM axs_anti_delete_config WHERE account_id = %s AND is_on = 1",
            (account_id,),
        )
        return [r["chat_id"] for r in cur.fetchall()]


# --- message cache ---


@_retry_on_conn_error
def anti_delete_cache_add(
    chat_id: int,
    msg_id: int,
    text: str,
    sender_id: Optional[int],
    is_bot: bool = False,
    account_id: int = 0,
) -> None:
    """Кладём сообщение в кэш (по аккаунту, чату и msg_id)."""
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_message_cache (account_id, chat_id, msg_id, text, sender_id, is_bot)
            VALUES (%s, %s, %s, %s, %s, %s)
            ON DUPLICATE KEY UPDATE
                text = VALUES(text),
                sender_id = VALUES(sender_id),
                is_bot = VALUES(is_bot),
                created_at = CURRENT_TIMESTAMP(6)
            """,
            (account_id, chat_id, msg_id, text or "", sender_id, 1 if is_bot else 0),
        )
        # Cleanup вынесен в anti_delete_cache_cleanup(), вызывать периодически из фона


@_retry_on_conn_error
def anti_delete_cache_cleanup(max_age_hours: int = None) -> None:
    """Периодическая очистка старого кэша сообщений. Вызывать из фона раз в N минут."""
    _ensure_init()
    hours = max_age_hours if max_age_hours is not None else _CACHE_MAX_AGE_HOURS
    with _conn_cursor() as cur:
        cur.execute(
            """
            DELETE FROM axs_message_cache
            WHERE created_at < DATE_SUB(NOW(), INTERVAL %s HOUR)
            """,
            (hours,),
        )


@_retry_on_conn_error
def anti_delete_cache_find(
    chat_id: int,
    msg_id: int,
    account_id: int = 0,
) -> Optional[Tuple[int, str, Optional[int], int]]:
    """Находит кэшированное сообщение и возвращает (chat_id, text, sender_id, is_bot) или None."""
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT chat_id, text, sender_id, is_bot
            FROM axs_message_cache
            WHERE account_id = %s AND chat_id = %s AND msg_id = %s
            """,
            (account_id, chat_id, msg_id),
        )
        row = cur.fetchone()
        if not row:
            return None
        return (
            row["chat_id"],
            (row["text"] or ""),
            row["sender_id"],
            int(row.get("is_bot") or 0),
        )


@_retry_on_conn_error
def anti_delete_cache_remove(chat_id: int, msg_id: int, account_id: int = 0) -> None:
    """Удаляет запись из кэша."""
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            "DELETE FROM axs_message_cache WHERE account_id = %s AND chat_id = %s AND msg_id = %s",
            (account_id, chat_id, msg_id),
        )


# --- deleted log ---


@_retry_on_conn_error
def anti_delete_log_add(
    chat_id: int,
    msg_id: int,
    text: str,
    sender_id: Optional[int],
    account_id: int = 0,
) -> None:
    """Добавляет запись о удалённом сообщении в лог."""
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_deleted_log (account_id, chat_id, msg_id, text, sender_id)
            VALUES (%s, %s, %s, %s, %s)
            """,
            (account_id, chat_id, msg_id, text or "", sender_id),
        )


@_retry_on_conn_error
def anti_delete_log_list(
    chat_id: Optional[int] = None,
    limit: int = 30,
    account_id: int = 0,
) -> List[Tuple[int, int, str, Optional[int], Any]]:
    """Список последних удалённых сообщений.

    Возвращает список кортежей (chat_id, msg_id, text, sender_id, deleted_at).
    """
    _ensure_init()
    limit = max(1, min(200, int(limit or 30)))
    with _conn_cursor(commit=False) as cur:
        if chat_id is not None:
            cur.execute(
                """
                SELECT chat_id, msg_id, text, sender_id, deleted_at
                FROM axs_deleted_log
                WHERE account_id = %s AND chat_id = %s
                ORDER BY deleted_at DESC LIMIT %s
                """,
                (account_id, chat_id, limit),
            )
        else:
            cur.execute(
                """
                SELECT chat_id, msg_id, text, sender_id, deleted_at
                FROM axs_deleted_log
                WHERE account_id = %s
                ORDER BY deleted_at DESC LIMIT %s
                """,
                (account_id, limit),
            )
        return [
            (
                r["chat_id"],
                r["msg_id"],
                r["text"] or "",
                r["sender_id"],
                r["deleted_at"],
            )
            for r in cur.fetchall()
        ]

