# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Optional


class AIClient(ABC):
    @abstractmethod
    async def complete(self, prompt: str, system: Optional[str] = None) -> str: 
        raise NotImplementedError


class GeminiClient(AIClient):
    def __init__(self, api_key: str, model: str) -> None:
        from google import genai

        self._genai = genai
        self._client = genai.Client(api_key=api_key)
        # Сохраним полное имя модели согласно новому SDK: "models/..."
        self._model_name = model if model.startswith("models/") else f"models/{model}"

    async def complete(self, prompt: str, system: Optional[str] = None) -> str:
        # google-generativeai SDK is sync; run in thread if needed, but simple call is fine here
        from concurrent.futures import ThreadPoolExecutor
        import asyncio

        def _run() -> str:
            full_prompt = f"{system}\n\n{prompt}" if system else prompt
            try:
                resp = self._client.models.generate_content(
                    model=self._model_name,
                    contents=full_prompt,
                    config=self._genai.types.GenerateContentConfig(
                        max_output_tokens=1024,
                        temperature=0.7,
                        safety_settings=[
                            self._genai.types.SafetySetting(
                                category=self._genai.types.HarmCategory.HARM_CATEGORY_HARASSMENT,
                                threshold=self._genai.types.HarmBlockThreshold.BLOCK_NONE,
                            ),
                            self._genai.types.SafetySetting(
                                category=self._genai.types.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                                threshold=self._genai.types.HarmBlockThreshold.BLOCK_NONE,
                            ),
                            self._genai.types.SafetySetting(
                                category=self._genai.types.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
                                threshold=self._genai.types.HarmBlockThreshold.BLOCK_NONE,
                            ),
                            self._genai.types.SafetySetting(
                                category=self._genai.types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                                threshold=self._genai.types.HarmBlockThreshold.BLOCK_NONE,
                            ),
                        ],
                    ),
                )
            except Exception as exc:  # pragma: no cover - SDK/HTTP
                raise RuntimeError(f"Gemini error: {exc}")

            # Безопасно извлекаем текст из кандидатов
            texts: list[str] = []
            for cand in getattr(resp, "candidates", []) or []:
                parts = getattr(getattr(cand, "content", None), "parts", None) or []
                for part in parts:
                    t = getattr(part, "text", None)
                    if t:
                        texts.append(t)
            if texts:
                return texts[0]

            # Пояснение при отсутствии текста
            cand0 = (getattr(resp, "candidates", None) or [None])[0]
            finish_reason = getattr(cand0, "finish_reason", None)
            raise RuntimeError(
                "Gemini returned no text. Possibly blocked by moderation"
                f" (finish_reason={finish_reason})."
            )
 


        loop = asyncio.get_running_loop()
        with ThreadPoolExecutor(max_workers=1) as pool:
            return await loop.run_in_executor(pool, _run)


def build_ai_client(
    provider: str,
    google_api_key: Optional[str] = None,
    gemini_model: str = "gemini-2.5-pro",
) -> AIClient:
    provider = provider.lower()
    if provider != "gemini":
        raise RuntimeError("Only 'gemini' provider is supported.")
    if not google_api_key:
        raise RuntimeError("GOOGLE_API_KEY is required for provider=gemini")
    return GeminiClient(api_key=google_api_key, model=gemini_model)


