"""
Алиасы префиксов и имён команд.
Подгружается в handler для разрешения шорткатов (.r, .im, .tk и т.д.) и синонимов (conn -> connections).
"""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



# Короткий префикс -> (имя_модуля, rest_full или None = брать tail как есть)
# Значение str означает (str, None)
SHORTCUT_ALIASES = {
    ".ping": "ping",
    ".n": "notes",
    ".w": "weather",
    ".te": "templates",
    ".tr": "translate",
    ".ai": "ai",
    ".an": "anim",
    ".ad": "anti-delete",
    ".v": "voice",
    ".im": "improve",
    ".r": "remind",
    ".tk": "track",
    ".dl": "downloader",
    ".ynow": ("ym", "np"),
}

# Синонимы имени команды -> имя модуля (при вводе .axs conn или .axs template)
# anti-delete -> anti_delete (имя файла с подчёркиванием)
SUB_ALIASES = {
    "conn": "connections",
    "template": "templates",
    "anti-delete": "anti_delete",
    "unpin": "pin",
}


def resolve_shortcut(used_prefix: str, tail: str) -> tuple[str, str] | None:
    """
    Если used_prefix — шорткат, возвращает (sub, rest_full). Иначе None.
    """
    raw = SHORTCUT_ALIASES.get(used_prefix)
    if raw is None:
        return None
    if isinstance(raw, tuple):
        return (raw[0], raw[1] or tail)
    return (raw, tail)


def resolve_sub_alias(sub: str) -> str:
    """Подменяет синоним имени команды на имя модуля."""
    return SUB_ALIASES.get(sub, sub)


def shortcut_prefixes() -> tuple[str, ...]:
    """Кортеж префиксов-шорткатов для проверки в handler."""
    return tuple(SHORTCUT_ALIASES.keys())
