# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually

import json
import os
import struct
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv
from telethon.sessions import StringSession

from ApiXS.session_crypto import decrypt_session


def _validate_session_string(s: str) -> bool:
    """Проверяет, что строка похожа на валидную Telethon StringSession (без API)."""
    if not s or not s.strip():
        return False
    try:
        StringSession(s.strip())
        return True
    except (struct.error, ValueError, TypeError):
        return False


@dataclass
class Config:
    telegram_bot_id: int

    telegram_api_id: int
    telegram_api_hash: str

    telegram_bot_token: Optional[str]
    telegram_string_session: Optional[str]
    telegram_sessions: List[str]
    telegram_accounts: List[Dict[str, Any]]

    command_prefix: str
    allowed_users: List[str]

    groq_api_key: str
    groq_model: str

    database_url: str

    log_level: str
    
    @property
    def is_bot(self) -> bool:
        return bool(self.telegram_bot_token)

    @property
    def is_user_session(self) -> bool:
        return bool(self.telegram_string_session)

def _parse_allowed_list(value: Optional[str]) -> List[str]:
    if not value:
        return []
    parts = [p.strip() for p in value.split(",")]
    return [p for p in parts if p]


APIXS_VERSION = "4.0.0"


def _load_latest_approved_session_from_db(database_url: str) -> Optional[str]:
    """
    Загружает последнюю активную сессию только из БД (approved users only).g
    """
    if not database_url:
        return None
    try:
        import pymysql  # важно: импорт внутри функции
        from urllib.parse import urlparse

        u = urlparse(database_url)
        db = (u.path or "").strip("/") or "your_database"
        conn = pymysql.connect(
            host=u.hostname or "localhost",
            port=int(u.port or 3306),
            user=u.username or "root",
            password=u.password or "",
            database=db,
            charset="utf8mb4",
            connect_timeout=5,
            read_timeout=10,
            write_timeout=10,
        )
        try:
            with conn.cursor(pymysql.cursors.DictCursor) as cur:
                cur.execute(
                    """
                    SELECT s.encrypted_session
                    FROM axs_web_sessions s
                    JOIN axs_web_users u ON u.id = s.user_id
                    WHERE s.is_active = 1 AND u.is_approved = 1
                    ORDER BY s.last_used_at DESC
                    LIMIT 1
                    """
                )
                row = cur.fetchone()
                if not row or not row.get("encrypted_session"):
                    return None
                decrypted = decrypt_session(row["encrypted_session"])
                return decrypted if _validate_session_string(decrypted) else None
        finally:
            try:
                conn.close()
            except Exception:
                pass
    except Exception:
        import logging
        logging.getLogger("ApiXS.config").exception("DB session load failed")
        return None


def load_config() -> Config:
    load_dotenv()

    api_id_str = (
        os.getenv("TELEGRAM_API_ID")
        or os.getenv("TG_API_ID")
        or ""
    ).strip()
    api_hash = (
        os.getenv("TELEGRAM_API_HASH")
        or os.getenv("TG_API_HASH")
        or ""
    ).strip()
    if not api_id_str or not api_hash:
        raise RuntimeError("TELEGRAM_API_ID and TELEGRAM_API_HASH must be set in environment/.env")

    try:
        api_id = int(api_id_str)
    except ValueError as exc:
        raise RuntimeError("TELEGRAM_API_ID must be an integer") from exc

    telegram_bot_token = os.getenv("TELEGRAM_BOT_TOKEN", "").strip() or None
    telegram_string_session: Optional[str] = None
    telegram_sessions: List[str] = []

    # Мультиаккаунт: ACCOUNTS из файла, JSON из env или sessions по умолчанию
    telegram_accounts: List[Dict[str, str]] = []
    try:
        import sys
        root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        if root not in sys.path:
            sys.path.insert(0, root)
        from accounts_config import ACCOUNTS as _ACCOUNTS  # type: ignore
        if _ACCOUNTS:
            for acc in _ACCOUNTS:
                name = (acc.get("name") or "account").strip() or "account"
                sess = (acc.get("session") or "").strip()
                if sess and _validate_session_string(sess):
                    allowed = acc.get("allowed_users")
                    if isinstance(allowed, str):
                        allowed = [x.strip() for x in allowed.split(",") if x.strip()]
                    elif not isinstance(allowed, list):
                        allowed = []
                    telegram_accounts.append({"name": name, "session": sess, "allowed_users": allowed})
                elif sess:
                    import logging
                    logging.getLogger("ApiXS.config").warning(
                        "Account %r: invalid session string, skip", name
                    )
    except ImportError:
        pass
    if not telegram_accounts:
        json_raw = os.getenv("TELEGRAM_ACCOUNTS_JSON", "").strip()
        if json_raw:
            try:
                data = json.loads(json_raw)
                for acc in data if isinstance(data, list) else []:
                    name = (acc.get("name") or "account").strip() or "account"
                    sess = (acc.get("session") or "").strip()
                    if sess and _validate_session_string(sess):
                        allowed = acc.get("allowed_users", [])
                        if isinstance(allowed, str):
                            allowed = [x.strip() for x in allowed.split(",") if x.strip()]
                        elif not isinstance(allowed, list):
                            allowed = []
                        telegram_accounts.append({"name": name, "session": sess, "allowed_users": allowed})
            except json.JSONDecodeError:
                pass
    database_url = (os.getenv("DATABASE_URL", "") or "").strip()
    if not database_url:
        raise RuntimeError("DATABASE_URL must be set in environment/.env (e.g. mysql://user:password@localhost:3306/your_database")

    # Single-session режим: берём Telegram StringSession только из БД (approved + active).
    # Мультиаккаунты из accounts_config.py / TELEGRAM_ACCOUNTS_JSON не трогаем.
    db_session = _load_latest_approved_session_from_db(database_url)
    if db_session:
        telegram_string_session = db_session
        if not telegram_accounts:
            telegram_accounts = [{
                "name": "db_session",
                "session": db_session,
                "allowed_users": _parse_allowed_list(os.getenv("ALLOWED_USERS")),
            }]

    command_prefix = (os.getenv("COMMAND_PREFIX", ".axs").strip() or ".axs")
    allowed_users = _parse_allowed_list(os.getenv("ALLOWED_USERS"))

    groq_api_key = (os.getenv("GROQ_API_KEY", "") or "").strip()
    groq_model = os.getenv("GROQ_MODEL", "openai/gpt-oss-120b")

    log_level = (os.getenv("LOG_LEVEL", "INFO").strip() or "INFO").upper()

    if not groq_api_key:
        raise RuntimeError("GROQ_API_KEY must be set in environment/.env (free at https://console.groq.com)")

    telegram_bot_id = int(os.getenv("TELEGRAM_BOT_ID", "0").strip() or "0")

    return Config(
        telegram_bot_id=telegram_bot_id,
        telegram_api_id=api_id,
        telegram_api_hash=api_hash,
        telegram_bot_token=telegram_bot_token,
        telegram_string_session=telegram_string_session,
        telegram_sessions=telegram_sessions,
        telegram_accounts=telegram_accounts,
        command_prefix=command_prefix,
        allowed_users=allowed_users,
        groq_api_key=groq_api_key,
        groq_model=groq_model,
        database_url=database_url,
        log_level=log_level,
    )
