"""Groq chat completions — бесплатный тир, без ограничений по ключам."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import logging
from typing import Optional

logger = logging.getLogger(__name__)


def _as_msg(role: str, content: str) -> dict:
    return {"role": role, "content": (content or "").strip()}


async def complete(
    api_key: str,
    model: str,
    prompt: str,
    system: Optional[str] = None,
    history: Optional[list] = None,
) -> str:
    from groq import AsyncGroq

    messages = []
    if system:
        messages.append(_as_msg("system", system))
    for h in (history or []):
        r = (h.get("role") or "user").lower()
        if r not in ("user", "assistant"):
            continue
        messages.append(_as_msg(r, h.get("content") or ""))
    messages.append(_as_msg("user", prompt))

    async with AsyncGroq(api_key=api_key) as client:
        try:
            chat = await client.chat.completions.create(
                model=model,
                messages=messages,
                temperature=0.5,
                max_completion_tokens=2048,
            )
        except Exception as exc:
            logger.exception("Groq API error")
            raise RuntimeError(f"Groq: {exc}") from exc

    choice = (chat.choices or [None])[0]
    if not choice or not getattr(choice.message, "content", None):
        raise RuntimeError("Groq вернул пустой ответ")

    return (choice.message.content or "").strip()
