"""Точка входа: клиент Telegram и регистрация обработчиков .axs."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import os
import re
import time
import asyncio
from importlib import import_module
from typing import Optional, Callable, Any

from telethon import TelegramClient, events
from telethon.sessions import StringSession
from .config import Config
from .command_aliases import resolve_shortcut, resolve_sub_alias, shortcut_prefixes
from .commands import (
    ALIAS_TEMPLATES,
    MAX_MSG,
    help_link_message,
    parse_args,
    register_ai_mode_handler,
    register_anti_delete_handlers,
    start_reminder_worker,
)
from .commands.security import sanitize_text
from .store import prefix_get, status_metric_add
from .session_crypto import decrypt_session  
import logging

logger = logging.getLogger(__name__)

_ONLINE_WORKERS_STARTED: set[int] = set()
# Кэш обработчиков команд: sub -> handle/main/cmd, чтобы не импортировать и не искать каждый раз
_handler_cache: dict[str, Callable[..., Any]] = {}
# Кэш get_me() по client, чтобы не дергать API на каждое сообщение (снижает пинг в ЛС)
_get_me_cache: dict[int, tuple[Any, float]] = {}
_GET_ME_CACHE_TTL = 60.0  # секунд


def register_online_tracker_worker(client: TelegramClient, user_id: int, loop: Optional[asyncio.AbstractEventLoop] = None) -> None:
    """Запускает один воркер для онлайн-слежек (на аккаунт)."""
    if not user_id:
        return
    if user_id in _ONLINE_WORKERS_STARTED:
        return
    if loop is None:
        loop = getattr(client, "loop", None)
    if loop is None:
        return
    from .commands.online import _online_worker_loop

    _ONLINE_WORKERS_STARTED.add(user_id)
    loop.create_task(_online_worker_loop(client, int(user_id)))

def _user_filter(config: Config, allowed_list: list | None):
    """
    allowed_list: изначально разрешенные ID из конфига.
    Теперь также проверяет БД динамически.
    """
    static_allowed = set()
    if allowed_list:
        for u in allowed_list:
            s = str(u).strip()
            if s.isdigit():
                static_allowed.add(int(s))

    async def check(event) -> bool:
        try:
            sender = await event.get_sender()
            if not sender:
                return False
            
            user_id = sender.id

            if user_id in static_allowed:
                return True

            from .store import is_user_confirmed
            if is_user_confirmed(user_id):
                return True

            return False
        except Exception as e:
            logger.error(f"Error checking user permissions: {e}")
            return False

    return check


def create_telegram_client(
    config: Config,
    session_str: Optional[str] = None,
    loop: Optional[asyncio.AbstractEventLoop] = None,
) -> TelegramClient:
    if config.is_bot:
        client = TelegramClient(
            StringSession(),
            config.telegram_api_id,
            config.telegram_api_hash,
            loop=loop,
        )
    else:
        sess = (session_str or "").strip()
        if not sess:
            raise RuntimeError("Telegram user session is not provided (DB-only mode).")
        client = TelegramClient(
            StringSession(sess),
            config.telegram_api_id,
            config.telegram_api_hash,
            loop=loop,
        )
    return client


def _discover_command_modules() -> list[str]:
    """Сканирует ApiXS.commands и возвращает имена модулей с handle/main/cmd."""
    pkg = __package__ or "ApiXS"
    commands_pkg = f"{pkg}.commands"
    loaded: list[str] = []
    try:
        import pkgutil
        mod = __import__(commands_pkg, fromlist=["__path__"])
        path = getattr(mod, "__path__", None)
        if not path:
            return loaded
        for imp, name, _ in pkgutil.iter_modules(path, prefix=commands_pkg + "."):
            if name in (f"{commands_pkg}.__init__", f"{commands_pkg}.common", f"{commands_pkg}.security"):
                continue
            short = name.split(".")[-1]
            try:
                m = import_module(name)
                if getattr(m, "handle", None) or getattr(m, "main", None) or getattr(m, "cmd", None):
                    loaded.append(short)
            except Exception as e:
                logger.debug("skip command module %s: %s", short, e)
    except Exception as e:
        logger.debug("discover commands: %s", e)
    return sorted(loaded)


async def _get_me_cached(client: TelegramClient):
    """Возвращает get_me() с кэшем по client, чтобы не дергать API на каждое сообщение."""
    cid = id(client)
    now = time.monotonic()
    if cid in _get_me_cache:
        me, cached_at = _get_me_cache[cid]
        if now - cached_at < _GET_ME_CACHE_TTL:
            return me
    me = await client.get_me()
    _get_me_cache[cid] = (me, now)
    return me


def _get_cached_handler(sub: str):
    """Возвращает обработчик команды по имени модуля; кэширует после первой загрузки."""
    if sub in _handler_cache:
        return _handler_cache[sub]
    pkg = __package__ or "ApiXS"
    try:
        dyn_mod = import_module(f"{pkg}.commands.{sub}")
    except Exception as e:
        logger.debug("get_cached_handler %s: %s", sub, e)
        return None
    handler = (
        getattr(dyn_mod, "handle", None)
        or getattr(dyn_mod, "main", None)
        or getattr(dyn_mod, "cmd", None)
    )
    if handler is not None:
        _handler_cache[sub] = handler
    return handler


def install_handlers(client: TelegramClient, config: Config, allowed_users: list | None = None, account_name: str = "unknown") -> None:
    """
    allowed_users: переопределить для аккаунта (из accounts_config).
    account_name: имя аккаунта для логирования.
    """
    dyn = _discover_command_modules()
    # Прогрев кэша: загружаем обработчики при старте, чтобы первый вызов команды был быстрым
    for sub in dyn:
        _get_cached_handler(sub)
    logger.info(
        "ApiXS start: загружено командных модулей: %s (%s)",
        len(dyn),
        ", ".join(dyn) if dyn else "—",
    )
    check_user = _user_filter(config, allowed_users if allowed_users is not None else config.allowed_users)
    # Широкий паттерн: любой префикс вида .xxx (кастомный префикс пользователя или shortcuts)
    pattern = re.compile(r"^(\.[a-zA-Z0-9_]+)(?:@\w+)?\s*(.*)$", re.DOTALL)

    async def _respond(evt, txt: str, **kwargs) -> None:
        s = sanitize_text((txt or "")[:MAX_MSG])
        if config.is_bot:
            await evt.reply(s, **kwargs)
        else:
            try:
                await evt.edit(s, **kwargs)
            except Exception:
                await evt.reply(s, **kwargs)

    @client.on(events.NewMessage(pattern=r"^/start(?:@\w+)?(?:\s+(.+))?$"))
    async def on_start(event):
        tail = (event.pattern_match.group(1) or "").strip()
        if config.is_bot:
            if not event.is_private:
                return
        else:
            try:
                me = await event.client.get_me()
                if not me or event.sender_id != me.id:
                    return
            except Exception:
                return
        if not tail:
            await event.reply(
                "ApiXS init!\n\n"
                "Чтобы привязать веб‑кабинет, перейдите на страницу профиля и следуйте инструкции."
            )
            return
        token = tail
        # Login callback для веб‑кабинета
        # Сначала пробуем внутренний URL (для бота и сайта на разных хостах/контейнерах),
        # затем внешний. Если оба не заданы — не пытаемся ходить на 127.0.0.1.
        base_url = (os.getenv("STATUS_INTERNAL_URL") or "").strip()
        if not base_url:
            base_url = (os.getenv("STATUS_EXTERNAL_URL") or "").strip()
        if not base_url:
            await event.reply(
                "⚠️ Адрес веб‑кабинета не настроен.\n"
                "Укажи в .env переменную STATUS_INTERNAL_URL или STATUS_EXTERNAL_URL "
                "с адресом сайта (например, https://example.com)."
            )
            return
        url = base_url.rstrip("/") + "/user/login/callback"
        try:
            import requests
            if config.is_bot:
                telegram_id = int(event.sender_id or 0)
                username = None
                try:
                    sender = await event.get_sender()
                    username = getattr(sender, "username", None) if sender else None
                except Exception:
                    username = None
            else:
                me = await event.client.get_me()
                telegram_id = int(getattr(me, "id", 0) or event.sender_id or 0)
                username = getattr(me, "username", None) if me else None
            resp = requests.post(
                url,
                data={
                    "token": token,
                    "telegram_id": str(telegram_id),
                    "username": username or "",
                },
                timeout=10,
            )
            if resp.status_code == 200:
                await event.reply(
                    "✅ Вход для веб‑кабинета подтверждён.\n"
                    "Вернитесь на страницу профиля и обновите её."
                )
            else:
                msg = (
                    "⚠️ Не удалось подтвердить вход на сайте.\n"
                    "Попробуйте ещё раз с новой ссылкой из профиля."
                )
                try:
                    data = resp.json()
                except Exception:
                    data = {}
                err_code = (data.get("error") or data.get("detail") or "").lower()
                if err_code in ("invalid_token", "token_used", "token_expired"):
                    msg = "Ссылка устарела. Зайди в /user и получи новую."
                await event.reply(msg)
        except Exception as e:
            print(f"login callback error: {e}")
            await event.reply(
                "⚠️ Внутренняя ошибка при подтверждении входа. Попробуйте ещё раз позже."
            )

    @client.on(events.NewMessage(pattern=pattern))
    async def on_axs(event):
        t_start = time.monotonic()
        if config.is_bot:
            return
        try:
            me = await _get_me_cached(event.client)
            if not me or event.sender_id != me.id:
                return
        except Exception:
            return
        text = getattr(event.message, "message", None) or ""
        m = pattern.match(text)
        if not m:
            return
        used_prefix = (m.group(1) or "").strip()
        tail = (m.group(2) or "").strip()
        user_id = event.sender_id
        username = getattr(event.sender, "username", None) or ""
        user_prefix = prefix_get(user_id) or ""
        main_prefixes = {user_prefix} if user_prefix else {config.command_prefix}
        if used_prefix not in main_prefixes and used_prefix not in shortcut_prefixes():
            return
        try:
            status_metric_add("command_executed")
        except Exception:
            pass
        prefix = user_prefix or config.command_prefix
        if (not tail or tail.lower() == "help") and used_prefix in main_prefixes:
            if check_user is not None and not await check_user(event):
                await _respond(event, "<blockquote>⛔ Доступ запрещён.</blockquote>", parse_mode="html")
                return
            await _respond(event, help_link_message(prefix), parse_mode="html")
            return

        resolved = resolve_shortcut(used_prefix, tail)
        if resolved is not None:
            sub, rest_full = resolved
        else:
            parts = parse_args(tail)
            sub = (parts[0] if parts else "").lower()
            rest_full = " ".join(parts[1:]).strip() if len(parts) > 1 else ""

        # Специальная подстановка tail для .te и .n
        if used_prefix == ".te":
            parts_t = parse_args(tail)
            if len(parts_t) == 1 and parts_t[0].lower() not in ALIAS_TEMPLATES:
                rest_full = "get " + tail
        elif used_prefix == ".n":
            parts_n = parse_args(tail)
            if parts_n and parts_n[0].lower() not in ("add", "last", "search", "list", "del", "delete", "rm", ""):
                rest_full = "add " + tail

        async def respond(txt: str, **kwargs) -> None:
            await _respond(event, txt, **kwargs)

        if check_user is not None and not await check_user(event):
            await respond("<blockquote>⛔ Доступ запрещён.</blockquote>", parse_mode="html")
            return

        prefix = user_prefix or config.command_prefix

        from .store import alias_get as _alias_get
        user_alias = _alias_get(user_id, sub)
        if user_alias:
            sub_parts = parse_args(user_alias)
            sub = (sub_parts[0] if sub_parts else "").lower()
            rest_full = (" ".join(sub_parts[1:]) + " " + rest_full).strip()

        # Синонимы имени команды -> имя модуля (conn -> connections, unpin -> pin и т.д.)
        sub_raw = sub
        sub = resolve_sub_alias(sub)
        if sub_raw == "unpin":
            rest_full = "unpin"

        handler = _get_cached_handler(sub)
        if handler is not None:
                try:
                    await handler(
                        event=event,
                        tail=rest_full,
                        user_id=user_id,
                        respond=respond,
                        config=config,
                        prefix=prefix,
                        t_start=t_start,
                    )
                    elapsed = time.monotonic() - t_start
                    if elapsed > 0.5:
                        logger.name = "ApiXS Success"
                        logger.info("Command ( %s ) by user ( %s | %s ) took --> %.2fs", sub, username, user_id, elapsed)
                    return
                except Exception as e:
                    logger.name = "ApiXS Error"
                    logger.exception("Command ( %s ) by user ( %s | %s ) FAILED: %s", sub, username, user_id, e)

        elapsed = time.monotonic() - t_start
        if elapsed > 0.5:
            logger.name = "ApiXS Help"
            logger.info("Command ( help ) by user ( %s | %s ) took --> %.2fs", username, user_id, elapsed)
        await respond(help_link_message(prefix), parse_mode="html")

    register_ai_mode_handler(client, config)
    register_anti_delete_handlers(client, account_name=account_name)