# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually

from __future__ import annotations

"""
Отдельный скрипт для авторизации через QR-код.
Использует только низкоуровневый API Telethon для обхода проблем с телефонной авторизацией.
Поддерживает 2FA (облачный пароль).

Использование:
  python -m ApiXS.qr_login
  python -m ApiXS.qr_login --password "ваш_2fa_пароль"
"""

import argparse
import os
import asyncio
import sys
import base64
import time
import getpass
from typing import Optional, Tuple

try:
    import qrcode
    QR_AVAILABLE = True
except ImportError:
    QR_AVAILABLE = False

from telethon import TelegramClient
from telethon.sessions import StringSession
from telethon.tl import functions
from telethon.tl.types.auth import LoginTokenSuccess
from telethon.tl.types import UpdateLoginToken
from telethon.errors import SessionPasswordNeededError
from dotenv import load_dotenv


def resolve_api_credentials(
    flag_api_id: Optional[str],
    flag_api_hash: Optional[str],
) -> Tuple[int, str]:
    """Получает API credentials из аргументов или переменных окружения"""
    api_id_str = (
        (flag_api_id or "").strip()
        or (os.getenv("TELEGRAM_API_ID") or "").strip()
        or (os.getenv("TG_API_ID") or "").strip()
    )
    api_hash = (
        (flag_api_hash or "").strip()
        or (os.getenv("TELEGRAM_API_HASH") or "").strip()
        or (os.getenv("TG_API_HASH") or "").strip()
    )

    if not api_id_str:
        api_id_str = input("Введите TELEGRAM_API_ID (или TG_API_ID): ").strip()
    if not api_hash:
        api_hash = input("Введите TELEGRAM_API_HASH (или TG_API_HASH): ").strip()

    try:
        api_id = int(api_id_str)
    except ValueError:
        raise SystemExit("TELEGRAM_API_ID / TG_API_ID должно быть целым числом")

    if not api_hash:
        raise SystemExit("TELEGRAM_API_HASH / TG_API_HASH не должно быть пустым")

    return api_id, api_hash


async def qr_login_async(api_id: int, api_hash: str, password_2fa: Optional[str] = None) -> str:
    """
    Асинхронная функция для QR-логина через низкоуровневый API Telethon.
    НЕ использует start() или любые методы, которые запрашивают телефон.
    """
    # Создаем клиент БЕЗ использования контекстного менеджера,
    # чтобы полностью контролировать процесс подключения
    client = TelegramClient(StringSession(), api_id, api_hash)
    
    try:
        # Подключаемся к серверу БЕЗ авторизации
        await client.connect()
        
        if not client.is_connected():
            raise RuntimeError("Не удалось подключиться к Telegram")
        
        # Проверяем, не авторизован ли уже клиент
        if await client.is_user_authorized():
            print("⚠ Клиент уже авторизован. Используем существующую сессию.")
            session_string = client.session.save()
            await client.disconnect()
            return session_string
        
        print("Получение токена для QR-кода...")
        
        # Используем низкоуровневый API для экспорта токена логина
        # Это НЕ вызывает start() и не запрашивает телефон
        result = await client(functions.auth.ExportLoginTokenRequest(
            api_id=api_id,
            api_hash=api_hash,
            except_ids=[]
        ))
        
        # Проверяем тип результата
        if isinstance(result, LoginTokenSuccess):
            # Уже авторизован каким-то образом
            print("✓ Клиент уже авторизован!")
            session_string = client.session.save()
            await client.disconnect()
            return session_string
        
        # Получаем токен из результата
        if not hasattr(result, 'token'):
            raise RuntimeError(
                f"Не удалось получить токен логина из ответа. "
                f"Тип результата: {type(result)}"
            )
        
        token = result.token
        
        # Создаем URL для QR-кода
        # Формат: tg://login?token=<base64url_encoded_token>
        token_base64 = base64.urlsafe_b64encode(token).decode('utf-8').rstrip('=')
        qr_url = f"tg://login?token={token_base64}"
        
        print("\n" + "="*60)
        print("QR-КОД ДЛЯ АВТОРИЗАЦИИ")
        print("="*60)
        print("\n1. Откройте Telegram на вашем телефоне")
        print("2. Перейдите в Настройки > Устройства > Подключить устройство")
        print("3. Отсканируйте QR-код ниже\n")
        
        # Отображаем QR-код
        if QR_AVAILABLE:
            try:
                qr = qrcode.QRCode(
                    version=1,
                    box_size=2,
                    border=2
                )
                qr.add_data(qr_url)
                qr.make(fit=True)
                qr.print_ascii(invert=True)
                print(f"\nИли откройте ссылку вручную:\n{qr_url}\n")
            except Exception as qr_exc:
                print(f"QR-код URL: {qr_url}\n")
                print(f"(Не удалось отобразить QR в терминале: {qr_exc})\n")
        else:
            print(f"QR-код URL: {qr_url}\n")
            print("(Установите qrcode для отображения QR-кода: pip install qrcode[pil])\n")
        
        print("="*60)
        print("Ожидание сканирования QR-кода...")
        print("(Нажмите Ctrl+C для отмены)")
        print("="*60 + "\n")
        
        # Ждем обновления UpdateLoginToken
        # После сканирования QR-кода Telegram отправит UpdateLoginToken
        # Затем нужно снова вызвать ExportLoginTokenRequest для получения LoginTokenSuccess
        login_success = False
        max_wait_time = 120  # Максимальное время ожидания в секундах (2 минуты)
        start_time = time.time()
        last_check_time = start_time
        
        # Обработчик для UpdateLoginToken
        @client.on(UpdateLoginToken)
        async def on_login_token_update(event):
            nonlocal login_success
            # Когда получаем UpdateLoginToken, пробуем экспортировать токен снова
            try:
                result = await client(functions.auth.ExportLoginTokenRequest(
                    api_id=api_id,
                    api_hash=api_hash,
                    except_ids=[]
                ))
                if isinstance(result, LoginTokenSuccess):
                    login_success = True
            except Exception:
                pass
        
        # Периодически проверяем статус
        while not login_success and (time.time() - start_time) < max_wait_time:
            await asyncio.sleep(2)  # Проверяем каждые 2 секунды
            
            # Пробуем снова экспортировать токен - если QR был отсканирован,
            # получим LoginTokenSuccess
            try:
                result = await client(functions.auth.ExportLoginTokenRequest(
                    api_id=api_id,
                    api_hash=api_hash,
                    except_ids=[]
                ))
                
                if isinstance(result, LoginTokenSuccess):
                    login_success = True
                    print("\n✓ QR-код успешно отсканирован!")
                    print("✓ Авторизация завершена!")
                    break
            except Exception as check_exc:
                # Игнорируем ошибки при проверке (токен может быть еще не принят)
                pass
            
            # Показываем прогресс каждые 10 секунд
            elapsed = time.time() - last_check_time
            if elapsed >= 10:
                remaining = int(max_wait_time - (time.time() - start_time))
                if remaining > 0:
                    print(f"Ожидание... (осталось ~{remaining} сек)")
                last_check_time = time.time()
        
        if not login_success:
            await client.disconnect()
            raise RuntimeError(
                f"QR-код не был отсканирован в течение {max_wait_time} секунд.\n"
                "Попробуйте снова или убедитесь, что:\n"
                "  1. QR-код был правильно отсканирован\n"
                "  2. У вас есть активное интернет-соединение\n"
                "  3. Аккаунт Telegram не заблокирован"
            )
        
        # Проверяем сессию и обрабатываем 2FA при необходимости
        try:
            await client.get_me()
        except SessionPasswordNeededError:
            # Требуется пароль двухфакторной аутентификации (облачный пароль)
            print("\n⚠ Требуется пароль двухфакторной аутентификации (2FA / облачный пароль)")
            pwd = password_2fa
            if not pwd:
                pwd = getpass.getpass("Введите пароль 2FA: ").strip()
            if not pwd:
                await client.disconnect()
                raise RuntimeError("Пароль 2FA не введён. Запустите снова с --password или введите пароль при запросе.")
            try:
                await client.sign_in(password=pwd)
            except Exception as pwd_exc:
                await client.disconnect()
                raise RuntimeError(f"Неверный пароль 2FA: {pwd_exc}") from pwd_exc
        
        # Получаем финальную сессию
        session_string = client.session.save()
        await client.disconnect()
        
        return session_string
        
    except KeyboardInterrupt:
        print("\n\nАвторизация отменена пользователем.")
        if client.is_connected():
            await client.disconnect()
        raise
    except Exception as exc:
        if client.is_connected():
            await client.disconnect()
        raise


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Авторизация в Telegram через QR-код (без запроса телефона)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Примеры использования:
  # Базовая авторизация через QR-код
  python -m ApiXS.qr_login
  
  # С указанием API credentials
  python -m ApiXS.qr_login --api-id 123 --api-hash XXX
  
  # С паролем 2FA (если включена двухфакторная аутентификация)
  python -m ApiXS.qr_login --password "ваш_облачный_пароль"

Этот скрипт использует только QR-код для авторизации и НЕ запрашивает
номер телефона, что позволяет обойти ограничения Telegram на SMS-коды.
Поддерживает 2FA (облачный пароль) — будет запрошен при необходимости.
        """.strip()
    )
    parser.add_argument("--api-id", dest="api_id", help="TELEGRAM_API_ID / TG_API_ID")
    parser.add_argument("--api-hash", dest="api_hash", help="TELEGRAM_API_HASH / TG_API_HASH")
    parser.add_argument(
        "--password",
        dest="password_2fa",
        default=None,
        help="Пароль 2FA (облачный пароль). Если не указан, будет запрошен при необходимости.",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    # Подтянем значения из .env, если файл есть
    load_dotenv()

    api_id, api_hash = resolve_api_credentials(args.api_id, args.api_hash)

    print("Авторизация в Telegram через QR-код...")
    print("(Этот метод НЕ запрашивает номер телефона)\n")
    
    try:
        session_string = asyncio.run(qr_login_async(
            api_id, api_hash,
            password_2fa=(args.password_2fa or "").strip() or None,
        ))
    except KeyboardInterrupt:
        print("\n\nАвторизация отменена пользователем.")
        return 130
    except Exception as exc:
        print(f"\n❌ Не удалось авторизоваться: {exc}")
        print("\nВозможные решения:")
        print("  1. Убедитесь, что используете правильные API_ID и API_HASH")
        print("  2. Проверьте интернет-соединение")
        print("  3. Убедитесь, что аккаунт Telegram не заблокирован")
        print("  4. Попробуйте обновить Telethon: pip install --upgrade telethon")
        return 1

    print("\n" + "="*60)
    print("=== ВАША StringSession ===")
    print("="*60 + "\n")
    print(session_string)
    print("\n" + "="*60)
    print("\n⚠ Секьюрность: храните StringSession в секрете и НЕ коммитьте в git.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
