# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually

from __future__ import annotations

"""
CLI-утилита для генерации StringSession (вход в ваш профиль Telegram) и
вывода сессии в консоль.

Примеры:
  python -m ApiXS.session_gen                             # интерактивно, спросит всё
  python -m ApiXS.session_gen --api-id 123 --api-hash XXX # передача API-данных через флаги
  python -m ApiXS.session_gen --qr                        # авторизация через QR-код (обход ограничений)

Поддерживаются алиасы переменных окружения:
  TELEGRAM_API_ID / TG_API_ID
  TELEGRAM_API_HASH / TG_API_HASH
"""

import argparse
import os
import sys
import asyncio
from typing import Optional, Tuple

try:
    import qrcode
    QR_AVAILABLE = True
except ImportError:
    QR_AVAILABLE = False

from telethon import TelegramClient
from telethon.sessions import StringSession
from telethon.errors import SessionPasswordNeededError, PhoneCodeInvalidError
from telethon.tl.functions.auth import ExportLoginTokenRequest, ImportLoginTokenRequest
from telethon.tl.types.auth import LoginToken, LoginTokenSuccess
from telethon.tl.types import UpdateLoginToken
from telethon.tl import functions
import time
import base64
from urllib.parse import quote
from dotenv import load_dotenv


def resolve_api_credentials(
    flag_api_id: Optional[str],
    flag_api_hash: Optional[str],
) -> Tuple[int, str]:
    api_id_str = (
        (flag_api_id or "").strip()
        or (os.getenv("TELEGRAM_API_ID") or "").strip()
        or (os.getenv("TG_API_ID") or "").strip()
    )
    api_hash = (
        (flag_api_hash or "").strip()
        or (os.getenv("TELEGRAM_API_HASH") or "").strip()
        or (os.getenv("TG_API_HASH") or "").strip()
    )

    if not api_id_str:
        api_id_str = input("Введите TELEGRAM_API_ID (или TG_API_ID): ").strip()
    if not api_hash:
        api_hash = input("Введите TELEGRAM_API_HASH (или TG_API_HASH): ").strip()

    try:
        api_id = int(api_id_str)
    except ValueError:
        raise SystemExit("TELEGRAM_API_ID / TG_API_ID должно быть целым числом")

    if not api_hash:
        raise SystemExit("TELEGRAM_API_HASH / TG_API_HASH не должно быть пустым")

    return api_id, api_hash


def generate_session(
    api_id: int,
    api_hash: str,
    phone: Optional[str] = None,
    use_qr: bool = False,
) -> str:
    """
    Генерирует StringSession для Telegram.
    
    Args:
        api_id: Telegram API ID
        api_hash: Telegram API Hash
        phone: Номер телефона (опционально)
        use_qr: Использовать QR-код для авторизации (обход ограничений на коды)
    
    Returns:
        StringSession строка
    """
    if use_qr:
        # Авторизация через QR-код - работает даже при ограничениях на SMS
        print("\n=== Авторизация через QR-код ===")
        print("1. Откройте Telegram на вашем телефоне")
        print("2. Перейдите в Настройки > Устройства > Подключить устройство")
        print("3. Отсканируйте QR-код ниже\n")
        
        # Используем асинхронный API для QR-логина
        # Это позволяет избежать автоматического вызова start()
        print("Получение QR-кода...")
        
        async def qr_login_async():
            """Асинхронная функция для QR-логина через низкоуровневый API"""
            async with TelegramClient(StringSession(), api_id, api_hash) as async_client:
                # Подключаемся без авторизации
                await async_client.connect()
                
                if await async_client.is_user_authorized():
                    print("⚠ Клиент уже авторизован. Используем существующую сессию.")
                    return async_client.session.save()
                
                # Используем низкоуровневый API для экспорта токена логина
                # Это позволяет избежать автоматического вызова start()
                try:
                    # Экспортируем токен логина
                    result = await async_client(functions.auth.ExportLoginTokenRequest(
                        api_id=api_id,
                        api_hash=api_hash,
                        except_ids=[]
                    ))
                    
                    # Проверяем тип результата
                    if isinstance(result, LoginTokenSuccess):
                        # Уже авторизован каким-то образом
                        return async_client.session.save()
                    
                    # Получаем токен из результата
                    if not hasattr(result, 'token'):
                        raise RuntimeError("Не удалось получить токен логина из ответа")
                    
                    token = result.token
                    
                    # Создаем URL для QR-кода
                    # Формат: tg://login?token=<base64url_encoded_token>
                    token_base64 = base64.urlsafe_b64encode(token).decode('utf-8').rstrip('=')
                    qr_url = f"tg://login?token={token_base64}"
                    
                    # Отображаем QR-код
                    if QR_AVAILABLE:
                        try:
                            qr = qrcode.QRCode()
                            qr.add_data(qr_url)
                            qr.make(fit=True)
                            qr.print_ascii(invert=True)
                            print(f"\nИли откройте ссылку вручную: {qr_url}\n")
                        except Exception:
                            print(f"QR-код URL: {qr_url}\n")
                    else:
                        print(f"QR-код URL: {qr_url}\n")
                    
                    print("QR-код готов! Отсканируйте его в приложении Telegram.")
                    print("Ожидание авторизации... (нажмите Ctrl+C для отмены)\n")
                    
                    # Ждем обновления UpdateLoginToken
                    # После сканирования QR-кода Telegram отправит UpdateLoginToken
                    # Затем нужно снова вызвать ExportLoginTokenRequest для получения LoginTokenSuccess
                    login_success = False
                    max_wait_time = 60  # Максимальное время ожидания в секундах
                    start_time = time.time()
                    
                    while not login_success and (time.time() - start_time) < max_wait_time:
                        await asyncio.sleep(1)
                        
                        # Пробуем снова экспортировать токен - если QR был отсканирован,
                        # получим LoginTokenSuccess
                        try:
                            result = await async_client(functions.auth.ExportLoginTokenRequest(
                                api_id=api_id,
                                api_hash=api_hash,
                                except_ids=[]
                            ))
                            
                            if isinstance(result, LoginTokenSuccess):
                                login_success = True
                                print("✓ Авторизация успешна через QR-код!")
                                break
                        except Exception:
                            # Игнорируем ошибки при проверке
                            pass
                    
                    if not login_success:
                        raise RuntimeError(
                            "QR-код не был отсканирован в течение 60 секунд. "
                            "Попробуйте снова."
                        )
                    
                    return async_client.session.save()
                    
                except Exception as api_exc:
                    # Если низкоуровневый API не работает, пробуем использовать qr_login()
                    # но с перехватом вызова start()
                    print(f"Низкоуровневый API не сработал: {api_exc}")
                    print("Пробуем использовать встроенный метод qr_login()...")
                    
                    # Если низкоуровневый API не работает, пробуем использовать qr_login()
                    # но это может не сработать из-за автоматического вызова start()
                    raise RuntimeError(
                        f"Не удалось использовать низкоуровневый API для QR-логина: {api_exc}\n"
                        "Попробуйте обновить Telethon: pip install --upgrade telethon"
                    ) from api_exc
        
        # Запускаем асинхронную функцию
        try:
            session_string = asyncio.run(qr_login_async())
            return session_string
        except KeyboardInterrupt:
            print("\n\nАвторизация отменена пользователем.")
            raise
        except Exception as e:
            error_msg = str(e).lower()
            if "phone" in error_msg or "code" in error_msg or "start" in error_msg:
                raise RuntimeError(
                    "Telethon пытается использовать телефонную авторизацию вместо QR-кода.\n"
                    "Это известная проблема в некоторых версиях Telethon.\n\n"
                    "Решения:\n"
                    "1. Обновите Telethon: pip install --upgrade telethon\n"
                    "2. Используйте официальное приложение Telegram Desktop для авторизации\n"
                    "3. Попробуйте использовать обычную авторизацию с кодом (без --qr)"
                ) from e
            else:
                raise RuntimeError(
                    f"Ошибка при использовании QR-логина: {e}\n"
                    "Попробуйте обновить Telethon: pip install --upgrade telethon"
                ) from e
    else:
        # Используем контекстный менеджер для обычной авторизации
        with TelegramClient(StringSession(), api_id, api_hash) as client:
            return _generate_session_fallback(client, phone)


def _generate_session_fallback(client: TelegramClient, phone: Optional[str] = None) -> str:
    """
    Альтернативный метод авторизации через код подтверждения.
    Используется как fallback или основной метод при отсутствии QR.
    """
    try:
        # Пытаемся использовать стандартный метод
        if phone:
            client.start(phone=phone)
        else:
            client.start()
        return client.session.save()
    except Exception as exc:
        error_msg = str(exc).lower()
        
        # Если проблема с получением кода, предлагаем QR
        if "code" in error_msg or "sms" in error_msg or "phone" in error_msg:
            print(f"\n⚠ Проблема с получением кода: {exc}")
            print("\nРекомендация: используйте авторизацию через QR-код:")
            print("  python -m ApiXS.session_gen --qr")
            print("\nИли попробуйте:")
            print("  1. Проверьте номер телефона")
            print("  2. Убедитесь, что аккаунт не заблокирован")
            print("  3. Подождите несколько минут и попробуйте снова")
            raise SystemExit(1) from exc
        else:
            # Другие ошибки (пароль 2FA и т.д.)
            if isinstance(exc, SessionPasswordNeededError):
                print("\n⚠ Требуется пароль двухфакторной аутентификации (2FA)")
                password = input("Введите пароль 2FA: ").strip()
                try:
                    client.sign_in(password=password)
                    return client.session.save()
                except Exception as pwd_exc:
                    raise SystemExit(f"Неверный пароль 2FA: {pwd_exc}") from pwd_exc
            raise


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Генератор StringSession (Telethon)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Примеры использования:
  # Интерактивная авторизация через код
  python -m ApiXS.session_gen
  
  # Авторизация через QR-код (рекомендуется при проблемах с кодами)
  python -m ApiXS.session_gen --qr
  
  # С указанием номера телефона
  python -m ApiXS.session_gen --phone +1234567890

Примечание: Если коды не приходят из-за ограничений Telegram,
используйте флаг --qr для авторизации через QR-код.
        """.strip()
    )
    parser.add_argument("--api-id", dest="api_id", help="TELEGRAM_API_ID / TG_API_ID")
    parser.add_argument("--api-hash", dest="api_hash", help="TELEGRAM_API_HASH / TG_API_HASH")
    parser.add_argument("--phone", dest="phone", help="Номер телефона в международном формате (опц.)")
    parser.add_argument(
        "--qr",
        dest="use_qr",
        action="store_true",
        help="Использовать авторизацию через QR-код (обход ограничений на SMS-коды)",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    # Подтянем значения из .env, если файл есть
    load_dotenv()

    api_id, api_hash = resolve_api_credentials(args.api_id, args.api_hash)

    print("Авторизация в Telegram...")
    try:
        session_string = generate_session(
            api_id,
            api_hash,
            phone=args.phone,
            use_qr=args.use_qr,
        )
    except KeyboardInterrupt:
        print("\n\nАвторизация отменена пользователем.")
        return 130
    except SystemExit as exc:
        return exc.code if isinstance(exc.code, int) else 1
    except Exception as exc:
        print(f"\n❌ Не удалось авторизоваться: {exc}")
        print("\nВозможные решения:")
        print("  1. Используйте --qr для авторизации через QR-код")
        print("  2. Проверьте правильность API_ID и API_HASH")
        print("  3. Убедитесь, что аккаунт не заблокирован")
        return 1

    print("\n=== ВАША StringSession ===\n")
    print(session_string)
    print("\nСекьюрность: храните StringSession в секрете и НЕ коммитьте в git.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

