# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually

from __future__ import annotations

import base64
import os
from pathlib import Path
from typing import Final

from cryptography.fernet import Fernet, InvalidToken
from dotenv import load_dotenv

# Всегда грузим .env из корня проекта (родитель каталога ApiXS), чтобы
# ApiXS_start и status_site использовали один и тот же SESSION_ENC_KEY.
_project_root = Path(__file__).resolve().parent.parent
load_dotenv(_project_root / ".env")

_enc_key_str = (os.getenv("SESSION_ENC_KEY") or "").strip()
if not _enc_key_str:
    raise RuntimeError("SESSION_ENC_KEY must be set (base64 urlsafe 32 bytes)")

try:
    # Если пользователь положил «сырой» ключ длиной 32 байта — кодируем в urlsafe base64
    if len(_enc_key_str) == 32:
        _enc_key = base64.urlsafe_b64encode(_enc_key_str.encode("utf-8"))
    else:
        _enc_key = _enc_key_str.encode("utf-8")
    FERNET: Final[Fernet] = Fernet(_enc_key)
except Exception as exc:  # pragma: no cover
    raise RuntimeError(f"Invalid SESSION_ENC_KEY: {exc}")


def encrypt_session(session_str: str) -> str:
    token = FERNET.encrypt(session_str.encode("utf-8"))
    return token.decode("utf-8")


def decrypt_session(token_str: str) -> str:
    try:
        data = FERNET.decrypt(token_str.encode("utf-8"))
    except InvalidToken:
        raise RuntimeError("Cannot decrypt session")
    return data.decode("utf-8")

