"""Хранение в MySQL: templates, anim, ai_mode, ai_history."""

# ApiXS Demo — Public source code
# Full version available at https://YOUR_DOMAIN
# Generated by scripts/build_demo.py — do not edit manually



from __future__ import annotations

import functools
import logging
import os
import threading
import time
from contextlib import contextmanager
from datetime import datetime
from typing import Any, Callable, Dict, List, Optional, Tuple
from urllib.parse import urlparse

import pymysql
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)


def _sanitize_log_msg(msg: str) -> str:
    """Удаляет токены из логов."""
    if not msg:
        return msg
    import re
    # Telegram bot tokens
    msg = re.sub(r"\b\d{8,10}:[A-Za-z0-9_-]{35}\b", "[TOKEN]", msg)
    # API keys
    msg = re.sub(r"\b(gsk_|sk-|AIza)[A-Za-z0-9_-]{20,}\b", "[API_KEY]", msg)
    # Database URLs (маскируем пароль)
    msg = re.sub(r"(mysql|postgres)://[^:]+:[^@]+@", r"\1://user:***@", msg)
    return msg

_AI_HISTORY_MAX = 20
_CACHE_MAX_AGE_HOURS = 48
_tls = threading.local()

# One-time schema init: avoid DDL on every request
_SCHEMA_INIT_DONE = False
_SCHEMA_INIT_LOCK = threading.Lock()
_PING_THROTTLE_SEC = 60  # only ping connection at most once per minute

# TTL caches for hot path (30–60s), reduce DB round-trips
_CACHE_TTL_SEC = 60
_PREFIX_CACHE: Dict[int, Tuple[float, Optional[str]]] = {}
_ALIAS_CACHE: Dict[Tuple[int, str], Tuple[float, Optional[str]]] = {}
_IS_USER_CONFIRMED_CACHE: Dict[int, Tuple[float, bool]] = {}
_AI_MODE_CACHE: Dict[int, Tuple[float, Optional[Dict[str, Any]]]] = {}
_CACHE_MAX_ENTRIES = 2000


def _get_conn() -> Optional[pymysql.Connection]:
    return getattr(_tls, "conn", None)


def _set_conn(conn: Optional[pymysql.Connection]) -> None:
    _tls.conn = conn


def _get_last_ping() -> float:
    return getattr(_tls, "last_ping", 0.0)


def _set_last_ping(t: float) -> None:
    _tls.last_ping = t


def _cache_evict_if_needed(cache: Dict, max_entries: int = _CACHE_MAX_ENTRIES) -> None:
    if len(cache) <= max_entries:
        return
    now = time.time()
    expired = [k for k, (ts, _) in list(cache.items()) if (now - ts) > _CACHE_TTL_SEC]
    for k in expired[: max_entries // 2]:
        cache.pop(k, None)


def _parse_mysql_url(url: str) -> dict:
    u = urlparse(url)
    path = (u.path or "").strip("/")
    return {
        "host": u.hostname or "localhost",
        "port": int(u.port or 3306),
        "user": u.username or "root",
        "password": u.password or "",
        "database": path or "your_database",
        "charset": "utf8mb4",
    }


def _get_url() -> str:
    return (os.getenv("DATABASE_URL") or "").strip()


def _connect() -> pymysql.Connection:
    url = _get_url()
    if not url:
        raise RuntimeError("DATABASE_URL not set")
    params = _parse_mysql_url(url)
    params["connect_timeout"] = 10
    conn = pymysql.connect(**params)
    _set_conn(conn)
    return conn


def _close_conn() -> None:
    conn = _get_conn()
    if conn:
        try:
            conn.close()
        except Exception:
            pass
        _set_conn(None)


_CONN_ERRORS = (
    pymysql.err.OperationalError,
    pymysql.err.InterfaceError,
    ValueError,
)


def _retry_on_conn_error(fn: Callable) -> Callable:
    """Повтор операции при ошибке соединения (Lost connection, read of closed file)."""
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        for attempt in range(2):
            try:
                return fn(*args, **kwargs)
            except _CONN_ERRORS as e:
                if attempt == 0:
                    _close_conn()
                    logger.info("MySQL reconnect after: %s", _sanitize_log_msg(str(e)))
                    continue
                logger.warning("db: %s", _sanitize_log_msg(str(e)))
                raise
        return None  # unreachable
    return wrapper


@contextmanager
def _conn_cursor(commit: bool = True):
    """Контекстный менеджер для курсора. commit=False для read-only (не делаем COMMIT после SELECT)."""
    import time as _time
    url = _get_url()
    if not url:
        raise RuntimeError("DATABASE_URL not set")
    conn = _get_conn()
    if conn is None:
        _connect()
        conn = _get_conn()
    else:
        now = _time.time()
        if (now - _get_last_ping()) >= _PING_THROTTLE_SEC:
            try:
                conn.ping(reconnect=True)
                _set_last_ping(now)
            except Exception:
                _close_conn()
                _connect()
                conn = _get_conn()
                _set_last_ping(_time.time())
    cur = conn.cursor(pymysql.cursors.DictCursor)
    try:
        yield cur
        if commit:
            conn.commit()
    except Exception as e:
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
        if isinstance(e, _CONN_ERRORS):
            _close_conn()
        logger.warning("db: %s", _sanitize_log_msg(str(e)))
        raise
    finally:
        cur.close()


@_retry_on_conn_error
def _init_schema():
    with _conn_cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS axs_templates (
                user_id BIGINT NOT NULL,
                name VARCHAR(255) NOT NULL,
                content TEXT,
                PRIMARY KEY (user_id, name)
            )
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS axs_anim (
                user_id BIGINT PRIMARY KEY,
                mode VARCHAR(32) NOT NULL DEFAULT 'instant'
            )
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS axs_ai_mode (
                chat_id BIGINT PRIMARY KEY,
                is_on TINYINT(1) NOT NULL DEFAULT 0,
                prompt_details TEXT
            )
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS axs_ai_history (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                chat_id BIGINT NOT NULL,
                ord_idx INT NOT NULL,
                role VARCHAR(32) NOT NULL,
                content TEXT,
                INDEX (chat_id, ord_idx)
            )
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS axs_notes (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                user_id BIGINT NOT NULL,
                text TEXT NOT NULL,
                created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
                INDEX (user_id, created_at)
            )
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS axs_reminders (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                user_id BIGINT NOT NULL,
                chat_id BIGINT NOT NULL,
                remind_at DATETIME(6) NOT NULL,
                text TEXT NOT NULL,
                created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
                INDEX (remind_at),
                INDEX (user_id)
            )
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS axs_aliases (
                user_id BIGINT NOT NULL,
                alias VARCHAR(64) NOT NULL,
                command TEXT NOT NULL,
                PRIMARY KEY (user_id, alias)
            )
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS axs_user_prefix (
                user_id BIGINT PRIMARY KEY,
                prefix VARCHAR(32) NOT NULL
            )
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS axs_status_metrics (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                metric_type VARCHAR(32) NOT NULL,
                value BIGINT NOT NULL,
                created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
                INDEX (metric_type, created_at)
            )
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS axs_user_settings (
                user_id BIGINT PRIMARY KEY,
                auto_delete_groups TINYINT(1) NOT NULL DEFAULT 1,
                auto_delete_channels TINYINT(1) NOT NULL DEFAULT 1
            )
        """)
        for col, spec in [
            ("anti_delete_enabled", "TINYINT(1) NOT NULL DEFAULT 1"),
            ("seen_date_format", "VARCHAR(32) NOT NULL DEFAULT 'short'"),
        ]:
            try:
                cur.execute(
                    "ALTER TABLE axs_user_settings ADD COLUMN {} {}".format(col, spec)
                )
            except Exception:
                pass
        # Роль пользователя (добавляется к axs_web_users через status_app, но на случай прямого вызова)
        try:
            cur.execute(
                "ALTER TABLE axs_web_users ADD COLUMN "
                "role ENUM('admin','moderator','user') NOT NULL DEFAULT 'user'"
            )
        except Exception:
            pass
        cur.execute("""
            CREATE TABLE IF NOT EXISTS axs_user_tokens (
                user_id BIGINT NOT NULL,
                service VARCHAR(32) NOT NULL,
                token TEXT,
                updated_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6)
                    ON UPDATE CURRENT_TIMESTAMP(6),
                PRIMARY KEY (user_id, service)
            )
        """)
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS axs_online_watch (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                watcher_id BIGINT NOT NULL,
                target_id BIGINT NOT NULL,
                target_username VARCHAR(64),
                notified TINYINT(1) DEFAULT 0,
                created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
                UNIQUE KEY (watcher_id, target_id)
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS axs_online_track (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                tracker_id BIGINT NOT NULL,
                target_id BIGINT NOT NULL,
                target_username VARCHAR(64),
                last_status VARCHAR(32) DEFAULT 'unknown',
                is_active TINYINT(1) DEFAULT 1,
                created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
                UNIQUE KEY (tracker_id, target_id)
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS axs_online_log (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                tracker_id BIGINT NOT NULL,
                target_id BIGINT NOT NULL,
                status VARCHAR(32) NOT NULL,
                recorded_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
                INDEX (target_id, recorded_at)
            )
            """
        )


def _ensure_init():
    global _SCHEMA_INIT_DONE
    if _SCHEMA_INIT_DONE:
        return
    with _SCHEMA_INIT_LOCK:
        if _SCHEMA_INIT_DONE:
            return
        try:
            _init_schema()
            _SCHEMA_INIT_DONE = True
        except Exception as e:
            logger.exception("schema init: %s", e)
            raise


# --- templates ---


@_retry_on_conn_error
def templates_list(user_id: int) -> List[Tuple[str, str]]:
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT name, content FROM axs_templates WHERE user_id = %s ORDER BY name",
            (user_id,),
        )
        return [(r["name"], r["content"] or "") for r in cur.fetchall()]


@_retry_on_conn_error
def template_get(user_id: int, name: str) -> Optional[str]:
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT content FROM axs_templates WHERE user_id = %s AND name = %s",
            (user_id, name),
        )
        row = cur.fetchone()
        return (row["content"] or "").strip() if row else None


@_retry_on_conn_error
def template_set(user_id: int, name: str, content: str) -> None:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_templates (user_id, name, content)
            VALUES (%s, %s, %s)
            ON DUPLICATE KEY UPDATE content = VALUES(content)
            """,
            (user_id, name, content or ""),
        )


@_retry_on_conn_error
def template_delete(user_id: int, name: str) -> bool:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            "DELETE FROM axs_templates WHERE user_id = %s AND name = %s",
            (user_id, name),
        )
        return cur.rowcount > 0


# --- anim ---

ANIM_INSTANT = "instant"
ANIM_TYPE = "type"
ANIM_MODES = (ANIM_INSTANT, ANIM_TYPE)


@_retry_on_conn_error
def anim_get(user_id: int) -> str:
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute("SELECT mode FROM axs_anim WHERE user_id = %s", (user_id,))
        row = cur.fetchone()
        m = (row["mode"] or "").strip() if row else ANIM_INSTANT
        return m if m in ANIM_MODES else ANIM_INSTANT


@_retry_on_conn_error
def anim_set(user_id: int, mode: str) -> bool:
    if mode not in ANIM_MODES:
        return False
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_anim (user_id, mode) VALUES (%s, %s)
            ON DUPLICATE KEY UPDATE mode = VALUES(mode)
            """,
            (user_id, mode),
        )
    return True


# --- ai_mode ---


@_retry_on_conn_error
def ai_mode_get(chat_id: int) -> Optional[Dict[str, Any]]:
    now = time.time()
    cached = _AI_MODE_CACHE.get(chat_id)
    if cached and (now - cached[0]) < _CACHE_TTL_SEC:
        return cached[1]
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT is_on, prompt_details FROM axs_ai_mode WHERE chat_id = %s",
            (chat_id,),
        )
        row = cur.fetchone()
        if not row:
            val = None
        else:
            val = {
                "on": bool(row["is_on"]),
                "prompt_details": (row["prompt_details"] or "").strip(),
            }
    _cache_evict_if_needed(_AI_MODE_CACHE)
    _AI_MODE_CACHE[chat_id] = (now, val)
    return val


@_retry_on_conn_error
def ai_mode_set(chat_id: int, on: bool, prompt_details: str = "") -> None:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_ai_mode (chat_id, is_on, prompt_details)
            VALUES (%s, %s, %s)
            ON DUPLICATE KEY UPDATE is_on = VALUES(is_on), prompt_details = VALUES(prompt_details)
            """,
            (chat_id, 1 if on else 0, (prompt_details or "").strip()),
        )
    _AI_MODE_CACHE.pop(chat_id, None)


@_retry_on_conn_error
def ai_mode_list() -> List[Tuple[int, bool, str]]:
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT chat_id, is_on, prompt_details FROM axs_ai_mode"
        )
        return [(r["chat_id"], bool(r["is_on"]), (r["prompt_details"] or "").strip()) for r in cur.fetchall()]


# --- ai_history ---


@_retry_on_conn_error
def ai_history_get(chat_id: int) -> List[Dict[str, str]]:
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT role, content FROM axs_ai_history
            WHERE chat_id = %s ORDER BY ord_idx
            """,
            (chat_id,),
        )
        return [{"role": r["role"], "content": r["content"] or ""} for r in cur.fetchall()]


@_retry_on_conn_error
def ai_history_add_turn(chat_id: int, user_content: str, assistant_content: str) -> None:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            "SELECT COALESCE(MAX(ord_idx), -1) + 1 AS n FROM axs_ai_history WHERE chat_id = %s",
            (chat_id,),
        )
        start = cur.fetchone()["n"]
        cur.execute(
            "INSERT INTO axs_ai_history (chat_id, ord_idx, role, content) VALUES (%s, %s, %s, %s)",
            (chat_id, start, "user", (user_content or "").strip()),
        )
        cur.execute(
            "INSERT INTO axs_ai_history (chat_id, ord_idx, role, content) VALUES (%s, %s, %s, %s)",
            (chat_id, start + 1, "assistant", (assistant_content or "").strip()),
        )
        cur.execute(
            """
            DELETE FROM axs_ai_history
            WHERE chat_id = %s AND id NOT IN (
                SELECT id FROM (
                    SELECT id FROM axs_ai_history WHERE chat_id = %s ORDER BY id DESC LIMIT %s
                ) t
            )
            """,
            (chat_id, chat_id, _AI_HISTORY_MAX),
        )


@_retry_on_conn_error
def ai_history_clear(chat_id: int) -> None:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute("DELETE FROM axs_ai_history WHERE chat_id = %s", (chat_id,))


# --- notes ---


@_retry_on_conn_error
def notes_add(user_id: int, text: str) -> int:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            "INSERT INTO axs_notes (user_id, text) VALUES (%s, %s)",
            (user_id, (text or "").strip()),
        )
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        return cur.fetchone()["id"]


@_retry_on_conn_error
def notes_last(user_id: int, limit: int = 10) -> List[Tuple[int, str, Any]]:
    """Returns [(id, text, created_at), ...]"""
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT id, text, created_at FROM axs_notes WHERE user_id = %s ORDER BY id DESC LIMIT %s",
            (user_id, max(1, min(100, limit))),
        )
        return [(r["id"], r["text"] or "", r["created_at"]) for r in cur.fetchall()]


@_retry_on_conn_error
def notes_search(user_id: int, query: str, limit: int = 20) -> List[Tuple[int, str, Any]]:
    """Returns [(id, text, created_at), ...]"""
    _ensure_init()
    q = "%" + (query or "").strip().replace("%", "\\%").replace("_", "\\_") + "%"
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT id, text, created_at FROM axs_notes WHERE user_id = %s AND text LIKE %s ORDER BY id DESC LIMIT %s",
            (user_id, q, max(1, min(100, limit))),
        )
        return [(r["id"], r["text"] or "", r["created_at"]) for r in cur.fetchall()]


@_retry_on_conn_error
def notes_delete(user_id: int, note_id: int) -> bool:
    """Удаляет заметку по id. Возвращает True, если удалена."""
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            "DELETE FROM axs_notes WHERE user_id = %s AND id = %s",
            (int(user_id), int(note_id)),
        )
        return cur.rowcount > 0


# --- reminders ---


@_retry_on_conn_error
def reminders_add(user_id: int, chat_id: int, remind_at: Any, text: str) -> int:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            "INSERT INTO axs_reminders (user_id, chat_id, remind_at, text) VALUES (%s, %s, %s, %s)",
            (user_id, chat_id, remind_at, (text or "").strip()),
        )
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        return cur.fetchone()["id"]


@_retry_on_conn_error
def reminders_list(user_id: Optional[int] = None, limit: int = 50) -> List[Tuple[int, int, int, Any, str, Any]]:
    """Returns [(id, user_id, chat_id, remind_at, text, created_at), ...]"""
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        if user_id is not None:
            cur.execute(
                """
                SELECT id, user_id, chat_id, remind_at, text, created_at
                FROM axs_reminders WHERE user_id = %s AND remind_at > NOW()
                ORDER BY remind_at ASC LIMIT %s
                """,
                (user_id, limit),
            )
        else:
            cur.execute(
                """
                SELECT id, user_id, chat_id, remind_at, text, created_at
                FROM axs_reminders WHERE remind_at > NOW()
                ORDER BY remind_at ASC LIMIT %s
                """,
                (limit,),
            )
        return [(r["id"], r["user_id"], r["chat_id"], r["remind_at"], r["text"] or "", r["created_at"]) for r in cur.fetchall()]


@_retry_on_conn_error
def reminders_due(limit: int = 100, now_dt: Optional[Any] = None) -> List[Tuple[int, int, int, Any, str]]:
    """Returns [(id, user_id, chat_id, remind_at, text), ...] where remind_at <= now_dt (default NOW())."""
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        if now_dt is not None:
            cur.execute(
                """
                SELECT id, user_id, chat_id, remind_at, text
                FROM axs_reminders WHERE remind_at <= %s
                ORDER BY remind_at ASC LIMIT %s
                """,
                (now_dt, limit),
            )
        else:
            cur.execute(
                """
                SELECT id, user_id, chat_id, remind_at, text
                FROM axs_reminders WHERE remind_at <= NOW()
                ORDER BY remind_at ASC LIMIT %s
                """,
                (limit,),
            )
        return [(r["id"], r["user_id"], r["chat_id"], r["remind_at"], r["text"] or "") for r in cur.fetchall()]


@_retry_on_conn_error
def reminders_delete(reminder_id: int) -> bool:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute("DELETE FROM axs_reminders WHERE id = %s", (reminder_id,))
        return cur.rowcount > 0


# --- user prefix (кастомный префикс для каждого пользователя) ---


@_retry_on_conn_error
def prefix_get(user_id: int) -> Optional[str]:
    now = time.time()
    cached = _PREFIX_CACHE.get(user_id)
    if cached and (now - cached[0]) < _CACHE_TTL_SEC:
        return cached[1]
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute("SELECT prefix FROM axs_user_prefix WHERE user_id = %s", (user_id,))
        row = cur.fetchone()
        val = (row["prefix"] or "").strip() if row else None
    _cache_evict_if_needed(_PREFIX_CACHE)
    _PREFIX_CACHE[user_id] = (now, val)
    return val


@_retry_on_conn_error
def prefix_set(user_id: int, prefix: str) -> None:
    p = (prefix or "").strip()[:32]
    if not p or not p.startswith("."):
        return
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            "INSERT INTO axs_user_prefix (user_id, prefix) VALUES (%s, %s) ON DUPLICATE KEY UPDATE prefix = VALUES(prefix)",
            (user_id, p),
        )
    _PREFIX_CACHE.pop(user_id, None)


@_retry_on_conn_error
def prefix_reset(user_id: int) -> bool:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute("DELETE FROM axs_user_prefix WHERE user_id = %s", (user_id,))
        ok = cur.rowcount > 0
    if ok:
        _PREFIX_CACHE.pop(user_id, None)
    return ok


# --- aliases ---


@_retry_on_conn_error
def alias_set(user_id: int, alias: str, command: str) -> None:
    alias_n = (alias or "").strip().lower()[:64]
    command = (command or "").strip()[:500]
    if not alias_n or not command:
        return
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_aliases (user_id, alias, command)
            VALUES (%s, %s, %s)
            ON DUPLICATE KEY UPDATE command = VALUES(command)
            """,
            (user_id, alias_n, command),
        )
    _ALIAS_CACHE.pop((user_id, alias_n), None)


@_retry_on_conn_error
def alias_get(user_id: int, alias: str) -> Optional[str]:
    alias_n = (alias or "").strip().lower()[:64]
    if not alias_n:
        return None
    key = (user_id, alias_n)
    now = time.time()
    cached = _ALIAS_CACHE.get(key)
    if cached and (now - cached[0]) < _CACHE_TTL_SEC:
        return cached[1]
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT command FROM axs_aliases WHERE user_id = %s AND alias = %s",
            (user_id, alias_n),
        )
        row = cur.fetchone()
        val = (row["command"] or "").strip() if row else None
    _cache_evict_if_needed(_ALIAS_CACHE)
    _ALIAS_CACHE[key] = (now, val)
    return val


@_retry_on_conn_error
def alias_list(user_id: int) -> List[Tuple[str, str]]:
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT alias, command FROM axs_aliases WHERE user_id = %s ORDER BY alias",
            (user_id,),
        )
        return [(r["alias"], r["command"] or "") for r in cur.fetchall()]


@_retry_on_conn_error
def alias_delete(user_id: int, alias: str) -> bool:
    alias_n = (alias or "").strip().lower()[:64]
    if not alias_n:
        return False
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            "DELETE FROM axs_aliases WHERE user_id = %s AND alias = %s",
            (user_id, alias_n),
        )
        ok = cur.rowcount > 0
    if ok:
        _ALIAS_CACHE.pop((user_id, alias_n), None)
    return ok


# --- status metrics (для сайта статуса) ---

# Буфер: собираем метрики в очередь и пишем пачками раз в 5 секунд.
# Это устраняет 1 DB-запрос на каждую команду бота.
import queue as _queue

_METRIC_QUEUE: "_queue.Queue[tuple[str, int]]" = _queue.Queue()
_METRIC_FLUSH_SEC = 5
_METRIC_BATCH_MAX = 100


def _metric_flusher() -> None:
    """Фоновый поток: пакетная запись накопленных метрик в БД."""
    while True:
        import time as _t
        _t.sleep(_METRIC_FLUSH_SEC)
        batch: list[tuple[str, int]] = []
        try:
            while True:
                batch.append(_METRIC_QUEUE.get_nowait())
                if len(batch) >= _METRIC_BATCH_MAX:
                    break
        except _queue.Empty:
            pass
        if not batch:
            continue
        try:
            _ensure_init()
            with _conn_cursor() as cur:
                cur.executemany(
                    "INSERT INTO axs_status_metrics (metric_type, value) VALUES (%s, %s)",
                    [(mt[:32], v) for mt, v in batch],
                )
        except Exception as e:
            logger.debug("metric flush error: %s", e)


threading.Thread(target=_metric_flusher, name="ApiXS-MetricFlusher", daemon=True).start()


def status_metric_add(metric_type: str, value: int = 1) -> None:
    """Добавляет метрику в очередь — пакетная запись в БД каждые 5 секунд."""
    _METRIC_QUEUE.put_nowait((metric_type, value))


@_retry_on_conn_error
def status_metrics_cleanup(keep_rows: int = 1000) -> None:
    """Периодическая очистка: оставить только последние keep_rows записей. Вызывать раз в N минут из фона."""
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            DELETE FROM axs_status_metrics
            WHERE id NOT IN (
                SELECT id FROM (
                    SELECT id FROM axs_status_metrics ORDER BY id DESC LIMIT %s
                ) t
            )
            """,
            (keep_rows,),
        )


@_retry_on_conn_error
def status_metrics_get(metric_type: str, hours: int = 24) -> List[Tuple[datetime, int]]:
    """Возвращает [(datetime, value), ...] за последние N часов."""
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT created_at, SUM(value) as total
            FROM axs_status_metrics
            WHERE metric_type = %s AND created_at >= DATE_SUB(NOW(), INTERVAL %s HOUR)
            GROUP BY DATE_FORMAT(created_at, '%%Y-%%m-%%d %%H:00:00')
            ORDER BY created_at ASC
            """,
            (metric_type[:32], hours),
        )
        return [(r["created_at"], int(r["total"] or 0)) for r in cur.fetchall()]


@_retry_on_conn_error
def status_metrics_total(metric_type: str) -> int:
    """Общее количество метрик типа."""
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT SUM(value) as total FROM axs_status_metrics WHERE metric_type = %s",
            (metric_type[:32],),
        )
        row = cur.fetchone()
        return int(row["total"] or 0) if row else 0


@_retry_on_conn_error
def status_metrics_sum_since_seconds(metric_type: str, seconds: int) -> int:
    """Сумма value для metric_type за последние N секунд."""
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT COALESCE(SUM(value), 0) as total
            FROM axs_status_metrics
            WHERE metric_type = %s
              AND created_at >= DATE_SUB(NOW(), INTERVAL %s SECOND)
            """,
            (metric_type[:32], int(seconds)),
        )
        row = cur.fetchone()
        return int((row or {}).get("total") or 0)


# --- user settings (auto-delete preferences) ---

_USER_SETTINGS_CACHE_TTL_SEC = 30
_USER_SETTINGS_CACHE: Dict[int, Tuple[float, bool, bool]] = {}

# --- user settings: seen date format cache ---
_SEEN_FORMAT_CACHE_TTL_SEC = 60
_SEEN_FORMAT_CACHE: Dict[int, Tuple[float, str]] = {}

# --- user settings: anti-delete enabled cache ---
_ANTI_DELETE_ENABLED_CACHE_TTL_SEC = 60
_ANTI_DELETE_ENABLED_CACHE: Dict[int, Tuple[float, bool]] = {}


@_retry_on_conn_error
def user_settings_get_auto_delete(user_id: int) -> Dict[str, bool]:
    """Возвращает настройки автоудаления для пользователя с кешированием.

    user_id — Telegram ID пользователя.
    """
    _ensure_init()
    now = time.time()
    cached = _USER_SETTINGS_CACHE.get(int(user_id))
    if cached and (now - cached[0]) < _USER_SETTINGS_CACHE_TTL_SEC:
        _, g, c = cached
        return {"groups": g, "channels": c}

    groups = True
    channels = True
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT auto_delete_groups, auto_delete_channels
            FROM axs_user_settings
            WHERE user_id = %s
            """,
            (int(user_id),),
        )
        row = cur.fetchone()
        if row:
            if "auto_delete_groups" in row and row["auto_delete_groups"] is not None:
                groups = bool(row["auto_delete_groups"])
            if "auto_delete_channels" in row and row["auto_delete_channels"] is not None:
                channels = bool(row["auto_delete_channels"])

    _USER_SETTINGS_CACHE[int(user_id)] = (now, groups, channels)
    return {"groups": groups, "channels": channels}


@_retry_on_conn_error
def user_settings_set_auto_delete(
    user_id: int,
    *,
    groups: Optional[bool] = None,
    channels: Optional[bool] = None,
) -> None:
    """Обновляет настройки автоудаления для пользователя.

    Переданные флаги обновляются, остальные остаются без изменений.
    """
    _ensure_init()
    user_id_int = int(user_id)

    current = user_settings_get_auto_delete(user_id_int)
    if groups is None:
        groups_val = current["groups"]
    else:
        groups_val = bool(groups)
    if channels is None:
        channels_val = current["channels"]
    else:
        channels_val = bool(channels)

    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_user_settings (user_id, auto_delete_groups, auto_delete_channels)
            VALUES (%s, %s, %s)
            ON DUPLICATE KEY UPDATE
                auto_delete_groups = VALUES(auto_delete_groups),
                auto_delete_channels = VALUES(auto_delete_channels)
            """,
            (user_id_int, 1 if groups_val else 0, 1 if channels_val else 0),
        )

    _USER_SETTINGS_CACHE[user_id_int] = (time.time(), groups_val, channels_val)


@_retry_on_conn_error
def user_settings_get_anti_delete_enabled(user_id: int) -> bool:
    """Включён ли anti-delete глобально для пользователя. По умолчанию True. Кэш 60s."""
    uid = int(user_id)
    now = time.time()
    cached = _ANTI_DELETE_ENABLED_CACHE.get(uid)
    if cached and (now - cached[0]) < _ANTI_DELETE_ENABLED_CACHE_TTL_SEC:
        return cached[1]
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT anti_delete_enabled FROM axs_user_settings WHERE user_id = %s",
            (uid,),
        )
        row = cur.fetchone()
    val = True
    if row and "anti_delete_enabled" in row and row["anti_delete_enabled"] is not None:
        val = bool(row["anti_delete_enabled"])
    _ANTI_DELETE_ENABLED_CACHE[uid] = (time.time(), val)
    return val


@_retry_on_conn_error
def user_settings_set_anti_delete_enabled(user_id: int, enabled: bool) -> None:
    _ensure_init()
    uid = int(user_id)
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_user_settings (user_id, anti_delete_enabled)
            VALUES (%s, %s)
            ON DUPLICATE KEY UPDATE anti_delete_enabled = VALUES(anti_delete_enabled)
            """,
            (uid, 1 if enabled else 0),
        )
    _ANTI_DELETE_ENABLED_CACHE.pop(uid, None)


@_retry_on_conn_error
def user_settings_get_seen_date_format(user_id: int) -> str:
    """Формат даты для команды seen: short, long, relative. По умолчанию short. Кэш 60s."""
    uid = int(user_id)
    now = time.time()
    cached = _SEEN_FORMAT_CACHE.get(uid)
    if cached and (now - cached[0]) < _SEEN_FORMAT_CACHE_TTL_SEC:
        return cached[1]
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT seen_date_format FROM axs_user_settings WHERE user_id = %s",
            (uid,),
        )
        row = cur.fetchone()
    v = "short"
    if row and row.get("seen_date_format"):
        candidate = (row["seen_date_format"] or "").strip().lower()
        if candidate in ("short", "long", "relative"):
            v = candidate
    _SEEN_FORMAT_CACHE[uid] = (time.time(), v)
    return v


@_retry_on_conn_error
def user_settings_set_seen_date_format(user_id: int, fmt: str) -> None:
    v = (fmt or "short").strip().lower()
    if v not in ("short", "long", "relative"):
        v = "short"
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_user_settings (user_id, seen_date_format)
            VALUES (%s, %s)
            ON DUPLICATE KEY UPDATE seen_date_format = VALUES(seen_date_format)
            """,
            (int(user_id), v),
        )


# --- online watchers / trackers ---


@_retry_on_conn_error
def online_watch_upsert(watcher_id: int, target_id: int, target_username: str = "") -> None:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_online_watch (watcher_id, target_id, target_username, notified)
            VALUES (%s, %s, %s, 0)
            ON DUPLICATE KEY UPDATE
                target_username = VALUES(target_username),
                notified = 0
            """,
            (int(watcher_id), int(target_id), (target_username or "")[:64]),
        )


@_retry_on_conn_error
def online_watch_list(watcher_id: int, limit: int = 200) -> List[Dict[str, Any]]:
    _ensure_init()
    lim = max(1, min(1000, int(limit or 200)))
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT watcher_id, target_id, target_username, created_at
            FROM axs_online_watch
            WHERE watcher_id = %s
            ORDER BY created_at ASC
            LIMIT %s
            """,
            (int(watcher_id), lim),
        )
        return list(cur.fetchall() or [])


@_retry_on_conn_error
def online_watch_remove(watcher_id: int, target_id: int) -> None:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            "DELETE FROM axs_online_watch WHERE watcher_id = %s AND target_id = %s",
            (int(watcher_id), int(target_id)),
        )


@_retry_on_conn_error
def online_track_upsert(tracker_id: int, target_id: int, target_username: str = "", *, is_active: bool = True) -> None:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_online_track (tracker_id, target_id, target_username, last_status, is_active)
            VALUES (%s, %s, %s, 'unknown', %s)
            ON DUPLICATE KEY UPDATE
                target_username = VALUES(target_username),
                is_active = VALUES(is_active)
            """,
            (int(tracker_id), int(target_id), (target_username or "")[:64], 1 if is_active else 0),
        )


@_retry_on_conn_error
def online_track_stop(tracker_id: int, target_id: int) -> None:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            "UPDATE axs_online_track SET is_active = 0 WHERE tracker_id = %s AND target_id = %s",
            (int(tracker_id), int(target_id)),
        )


@_retry_on_conn_error
def online_track_list(tracker_id: int, *, only_active: bool = True, limit: int = 500) -> List[Dict[str, Any]]:
    _ensure_init()
    lim = max(1, min(2000, int(limit or 500)))
    with _conn_cursor(commit=False) as cur:
        if only_active:
            cur.execute(
                """
                SELECT tracker_id, target_id, target_username, last_status, is_active, created_at
                FROM axs_online_track
                WHERE tracker_id = %s AND is_active = 1
                ORDER BY created_at ASC
                LIMIT %s
                """,
                (int(tracker_id), lim),
            )
        else:
            cur.execute(
                """
                SELECT tracker_id, target_id, target_username, last_status, is_active, created_at
                FROM axs_online_track
                WHERE tracker_id = %s
                ORDER BY created_at ASC
                LIMIT %s
                """,
                (int(tracker_id), lim),
            )
        return list(cur.fetchall() or [])


@_retry_on_conn_error
def online_track_set_last_status(tracker_id: int, target_id: int, last_status: str) -> None:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            UPDATE axs_online_track
            SET last_status = %s
            WHERE tracker_id = %s AND target_id = %s
            """,
            ((last_status or "unknown")[:32], int(tracker_id), int(target_id)),
        )


@_retry_on_conn_error
def online_log_add(tracker_id: int, target_id: int, status: str) -> None:
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_online_log (tracker_id, target_id, status)
            VALUES (%s, %s, %s)
            """,
            (int(tracker_id), int(target_id), (status or "unknown")[:32]),
        )


@_retry_on_conn_error
def online_log_list(tracker_id: int, target_id: int, limit: int = 20) -> List[Dict[str, Any]]:
    _ensure_init()
    lim = max(1, min(200, int(limit or 20)))
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT status, recorded_at
            FROM axs_online_log
            WHERE tracker_id = %s AND target_id = %s
            ORDER BY recorded_at DESC
            LIMIT %s
            """,
            (int(tracker_id), int(target_id), lim),
        )
        return list(cur.fetchall() or [])


@_retry_on_conn_error
def online_log_last(tracker_id: int, target_id: int) -> Optional[Dict[str, Any]]:
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT status, recorded_at
            FROM axs_online_log
            WHERE tracker_id = %s AND target_id = %s
            ORDER BY recorded_at DESC
            LIMIT 1
            """,
            (int(tracker_id), int(target_id)),
        )
        return cur.fetchone()


# --- per-user external tokens (e.g. Yandex Music) ---


@_retry_on_conn_error
def user_token_get(user_id: int, service: str) -> Optional[str]:
    """Возвращает зашифрованный токен сервиса для пользователя или None."""
    _ensure_init()
    svc = (service or "").strip().lower()[:32]
    if not svc:
        return None
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT token
            FROM axs_user_tokens
            WHERE user_id = %s AND service = %s
            """,
            (int(user_id), svc),
        )
        row = cur.fetchone()
        if not row:
            return None
        return row.get("token") or None


@_retry_on_conn_error
def user_token_set(user_id: int, service: str, token: str) -> None:
    """Сохраняет/обновляет зашифрованный токен сервиса для пользователя."""
    _ensure_init()
    svc = (service or "").strip().lower()[:32]
    if not svc:
        return
    with _conn_cursor() as cur:
        cur.execute(
            """
            INSERT INTO axs_user_tokens (user_id, service, token)
            VALUES (%s, %s, %s)
            ON DUPLICATE KEY UPDATE
                token = VALUES(token),
                updated_at = CURRENT_TIMESTAMP(6)
            """,
            (int(user_id), svc, token or ""),
        )


@_retry_on_conn_error
def user_token_delete(user_id: int, service: str) -> None:
    """Удаляет токен сервиса для пользователя."""
    _ensure_init()
    svc = (service or "").strip().lower()[:32]
    if not svc:
        return
    with _conn_cursor() as cur:
        cur.execute(
            "DELETE FROM axs_user_tokens WHERE user_id = %s AND service = %s",
            (int(user_id), svc),
        )


# --- Telegram StringSession, хранение в axs_web_sessions ---


@_retry_on_conn_error
def web_get_latest_active_session() -> Optional[Dict[str, Any]]:
    """
    Возвращает последнюю активную строку сессии Telegram из axs_web_sessions.
    Используется ботом при старте: берём только is_active=1 и только для одобренных пользователей.
    """
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            """
            SELECT s.id,
                   s.encrypted_session,
                   s.user_id,
                   s.last_used_at,
                   u.telegram_id,
                   u.username
            FROM axs_web_sessions AS s
            JOIN axs_web_users AS u ON u.id = s.user_id
            WHERE s.is_active = 1 AND u.is_approved = 1
            ORDER BY s.last_used_at DESC
            LIMIT 1
            """
        )
        row = cur.fetchone()
        if not row:
            return None
        now = datetime.utcnow()
        cur.execute(
            "UPDATE axs_web_sessions SET last_used_at = %s WHERE id = %s",
            (now, row["id"]),
        )
        row["last_used_at"] = now
        return row



@_retry_on_conn_error
def web_list_active_approved_sessions(limit: int = 200) -> List[Dict[str, Any]]:
    """Возвращает список активных сессий одобренных пользователей (для мультисессии)."""
    _ensure_init()
    lim = max(1, min(1000, int(limit or 200)))
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT s.id,
                   s.encrypted_session,
                   s.user_id,
                   s.last_used_at,
                   u.telegram_id,
                   u.username
            FROM axs_web_sessions AS s
            JOIN axs_web_users AS u ON u.id = s.user_id
            WHERE s.is_active = 1 AND u.is_approved = 1
            ORDER BY s.last_used_at DESC
            LIMIT %s
            """,
            (lim,),
        )
        return list(cur.fetchall() or [])


@_retry_on_conn_error
def web_touch_session_last_used(session_id: int) -> None:
    """Обновляет last_used_at для записи axs_web_sessions (best-effort)."""
    _ensure_init()
    sid = int(session_id)
    if sid <= 0:
        return
    now = datetime.utcnow()
    with _conn_cursor() as cur:
        cur.execute(
            "UPDATE axs_web_sessions SET last_used_at = %s WHERE id = %s",
            (now, sid),
        )


@_retry_on_conn_error
def is_user_confirmed(telegram_id: int) -> bool:
    tid = int(telegram_id)
    now = time.time()
    cached = _IS_USER_CONFIRMED_CACHE.get(tid)
    if cached and (now - cached[0]) < _CACHE_TTL_SEC:
        return cached[1]
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT id FROM axs_web_users WHERE telegram_id = %s AND is_approved = 1 LIMIT 1",
            (str(telegram_id),),
        )
        val = cur.fetchone() is not None
    _cache_evict_if_needed(_IS_USER_CONFIRMED_CACHE)
    _IS_USER_CONFIRMED_CACHE[tid] = (now, val)
    return val


# ── Роли пользователей ────────────────────────────────────────────────────────

_VALID_ROLES = {"admin", "moderator", "user"}


@_retry_on_conn_error
def user_get_role(telegram_id: int) -> str:
    """Возвращает роль пользователя: 'admin', 'moderator' или 'user'."""
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            "SELECT role FROM axs_web_users WHERE telegram_id = %s LIMIT 1",
            (str(telegram_id),),
        )
        row = cur.fetchone()
        if not row:
            return "user"
        return row.get("role") or "user"


@_retry_on_conn_error
def user_set_role(telegram_id: int, role: str) -> None:
    """Устанавливает роль пользователя."""
    if role not in _VALID_ROLES:
        raise ValueError(f"Invalid role: {role!r}. Valid: {_VALID_ROLES}")
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute(
            "UPDATE axs_web_users SET role = %s WHERE telegram_id = %s",
            (role, str(telegram_id)),
        )


@_retry_on_conn_error
def user_get_by_telegram_id(telegram_id: int) -> Optional[Dict[str, Any]]:
    """Возвращает пользователя по telegram_id или None."""
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT id, telegram_id, username, first_name, last_name,
                   last_login_at, is_approved, role, created_at
            FROM axs_web_users WHERE telegram_id = %s LIMIT 1
            """,
            (str(telegram_id),),
        )
        return cur.fetchone()


@_retry_on_conn_error
def user_list_all(limit: int = 1000, offset: int = 0) -> List[Dict[str, Any]]:
    """Возвращает список всех пользователей для админки."""
    _ensure_init()
    with _conn_cursor(commit=False) as cur:
        cur.execute(
            """
            SELECT id, telegram_id, username, first_name, last_name,
                   last_login_at, is_approved, role, created_at
            FROM axs_web_users
            ORDER BY created_at ASC
            LIMIT %s OFFSET %s
            """,
            (limit, offset),
        )
        return cur.fetchall() or []


@_retry_on_conn_error
def user_ensure_first_is_admin(telegram_id: int) -> None:
    """Если в таблице ровно 1 пользователь — автоматически назначает его admin."""
    _ensure_init()
    with _conn_cursor() as cur:
        cur.execute("SELECT COUNT(*) AS cnt FROM axs_web_users")
        row = cur.fetchone()
        if row and int(row.get("cnt") or 0) == 1:
            cur.execute(
                "UPDATE axs_web_users SET role = 'admin' WHERE telegram_id = %s",
                (str(telegram_id),),
            )